### ISSUE TITLE
Nemoh to Bemio to WEC-sim: .h5 Dataset issues

### ISSUE THREAD

**Issue by MattSharman** [WEC-Sim/WEC-Sim#10]
Hi All, 

I'm still getting up to speed on WEC-sim the dynamics and the code so please bear with me on this!

I'm running a test case using hydro data from Nemoh. I've managed to create a .h5 from bemio however when I go to run WEC-sim I get this error:

===============================================================================
WEC-Sim Wave Setup & Model Setup & Run WEC-Sim ...   
Error using griddedInterpolant
The grid vectors do not define a grid of points that match
the given values.

Error in interp1 (line 186)
        F = griddedInterpolant(X,V,method);

Error in bodyClass/irrExcitation (line 165)
                obj.hydroForce.fExt.re(:,ii) =
                interp1(obj.hydroData.simulation_parameters.w,obj.hydroData.hydro_coeffs.excitation.re(:,ii),wv,'spline');
                
Error in bodyClass/hydroForcePre (line 93)
                    obj.irrExcitation(w,numFreq);

Error in wecSim (line 55)
    body(kk).hydroForcePre(waves.w,simu.CIkt,waves.numFreq,simu.dt,simu.rho,waves.type,kk,simu.numWecBodies,simu.ssCalc); 

===============================================================================

Searching through my .h5 file and the RM3.h5 example case I see that the datasets under question (hydro_coeffs.excitation.im & re) are 3 dimensional in my case but 2D in the WEC-sim example  case (RM3.h5).

I also looked at the Bemio Nemoh tutorial output and found those datasets also to be 3D.

In my case bemio creates a (6x6x40) dataset with the 40 corresponding to the amount of wave frequencies i've asked Nemoh to use.
In the RM3 case the .h5 shows a 198x6 table.
RM3 runs, mine doesn't.

Anyone know where the error lies? In my Nemoh sim, how bemio populates the .h5 or how WEC-sim reads the .h5?

**Comment by lawsonro3** [comment]
Hi Matt,

Just fixed a small bug in the nemoh.py output - should now be good to go. Update to the latest version and try again.

Thanks for catching that and let me know if you have any other troubles.

-Mike
