### ISSUE TITLE
Unrecognized method, property, or field 'plotEta' for class 'waveClass'

### ISSUE THREAD

**Issue by sung2799** [WEC-Sim/WEC-Sim#1009]
Thanks for any insight into this - I had reinstalled WEC-SIM (due to computer crash) and am now unable to fully run any previously working simulations.  It runs partially, and I get the output file before the error occurs, so the error seems to occur after the output data structure is created.

I'm running on MATLAB R2022a.  It looks like something to do with the 'slx' file, though I have a pretty simple model.  I've attached a screenshot of the simulink file, and cut and paste the whole error message:

"Error using wecSim
Error evaluating 'StopFcn' callback of Frames block (mask) 'test/Global Reference Frame'.
Callback string is 'run('stopWecSim')'
Caused by:
    Error using wecSim
    Unrecognized method, property, or field 'plotEta' for class 'waveClass'."

![slx](https://user-images.githubusercontent.com/62447204/225119537-189df03f-055f-4fc6-8a2f-3f2250d81982.PNG)

Since I'm getting an output, I'm still able to use the program, though it would be nice to get full functionality back with the automated plots / graphics.  Thanks again!

Li

**Comment by dforbush2** [comment]
Please re-post using the provided issue templates. This is likely a version issue and the template will provide us the information needed to better assist you.
