### ISSUE TITLE
[BUG] 6 DOF constraint

### ISSUE THREAD

**Issue by hachikoi1** [WEC-Sim/WEC-Sim#1014]

**Comment by kmruehl** [comment]
@hachikoi1 it looks like your comment was edited and accidentally deleted. Can you please update it to include the original post?

**Comment by hachikoi1** [comment]
Dear [kmruehl](https://github.com/kmruehl)

I found it's mu fault. Could you please delete this post?

Best regards,

**Comment by kmruehl** [comment]
Will do, thanks!
