### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tedman223** [WEC-Sim/WEC-Sim#1027]
Hello I am an MECC team member. I am having a few issues with my wecSim model. In my sim mechanics I currently have two separate water lines. In addition there is no vertical motion in the float. I am also having a very low Power output which I believe is related to this lack of vertical motion. I have checked on the origins for my STL files in geometry, and I increased the diameter of the float hole to make sure that there is no overlap between the float and spar. 

![double waterline](https://user-images.githubusercontent.com/126424529/230454226-61fe7881-a005-4d6f-ab8d-60505442fcfa.jpg)

![code](https://user-images.githubusercontent.com/126424529/230451400-f1e19b17-c89e-4d60-9e32-873a0dd151a3.jpg)

![output](https://user-images.githubusercontent.com/126424529/230451427-55719a79-0f13-495f-b158-f41058818225.jpg)

![phase](https://user-images.githubusercontent.com/126424529/230451444-3de53d1c-536a-418b-957a-be46e095c3a4.jpg)

![current](https://user-images.githubusercontent.com/126424529/230451457-ca4bd0bb-fcbb-4cf2-bd45-8d7fc7b35405.jpg)

**Comment by nathanmtom** [comment]
@tedman223 Thank you for your question. We have begun requiring users to open GitHub issues using an appropriate template. This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "**WEC-Sim applications specific issue or question**" template and include more details on your setup and error message, We are happy to help. Please maintain the template structure and the issue type in the title.

**Refer to WEC-Sim issue templates and encourage user to re-submit issue (long)**
Thank you for your question. When creating an issue, please use the GitHub templates:
![image](https://user-images.githubusercontent.com/72414466/136063813-fd362db2-9943-4d45-a596-1b0c6fe6ba18.png)
![image](https://user-images.githubusercontent.com/72414466/136063890-8065ff72-f963-476e-a1cc-5cc4b813269d.png)
![image](https://user-images.githubusercontent.com/72414466/136064000-a42c5d5b-0950-4c00-95c2-e5596294675a.png)

This information is important for us to accurately assess what an issue is, how it occurs, and most quickly create a solution for you. It also helps us categorize our issues to determine areas of future improvement. Please maintain the template structure (bold headings). ​

**Comment by nathanmtom** [comment]
@tedman223 Thank you again for your question. I wanted to reach out to ask if you are able to edit or open a new issue following one of the issues templates. If we do not hear from you or see edits by the end of the week we will close this issue.

**Comment by tedman223** [comment]
I was actually able to resolve my issue, and was adressing the wrong questions for it, so I think it would be best to close the issue. I am however having some issues with getting my linear generator values correct and was wondering if you had any advice on where to research these?

cheers, Ted
________________________________

**Comment by nathanmtom** [comment]
Thanks for the update @tedman223 and glad to hear you resolved your first issue. 

If you are still having questions about your generator values, I am going to recommend closing this issue and you resubmitting a new issue while following the issues templates as illustrated in my first response. Apologies if this is an inconvenience, but following the templates helps ensure we have enough information to provide useful feedback.
