### ISSUE TITLE
PTO-Sim Variable Documentation Request

### ISSUE THREAD

**Issue by ccz359** [WEC-Sim/WEC-Sim#1035]
Hello, 

@ratanakso @nathanmtom 

Could you provide more documentation on what the following PTO-Sim variables are? And how to calculate them for altered examples?

From RM3 Compressible Hydraulic ptoSimInputFile:
ptosim.checkValve.k1 - This variable is within the Check Valve library block, it is a gain. Can you give more detail on how to calculate this value for modified examples?

ptosim.pistonCF.pBi - This variable is within the piston library block, it appears to be a pressure. Can you give more details on what this variable represents and how to calculate its value for a modified example? (I've been interpreting its meaning as the initial pressure in the bottom piston.)

Thank you!
Chelsea Kimball

**Comment by dav-og** [comment]
Hi Chelsea,

We request that users fill in one of our Issues templates first:

![image](https://user-images.githubusercontent.com/12831266/233157008-4ccb913b-4220-4f8f-aab5-0c19239c81bf.png)

Please fill in the 4th one, 'Theory or implementation clarification' with as much info as you can. In the meantime I also suggest checking out Ratanak's PTO-Sim paper if you haven't already? (https://energy.sandia.gov/wp-content/uploads/2014/06/SAND2015-2069C.pdf)

Cheers,
Dave
