### ISSUE TITLE
PTO-Sim Variable Documentation

### ISSUE THREAD

**Issue by ccz359** [WEC-Sim/WEC-Sim#1036]
**The development team requests that before submitting a question on the theory and implementation behind WEC-Sim to first please:**
1. Read through our [WEC-Sim Documentation](http://wec-sim.github.io/WEC-Sim/man/theory.html) with additional description found in our [Advanced Features Section](http://wec-sim.github.io/WEC-Sim/man/advanced_features.html)
1. Review MATLAB source code ([functions](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions), [objects](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/objects)) and the Simulink blocks ([libraries](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/lib))
1. Review the curated [WEC-Sim Examples](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples) and the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications)
1. Review the [WEC-Sim issues page](https://github.com/WEC-Sim/WEC-Sim/issues) which allows you to search past resolved issues or questions that might help answer your own question.

**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
I am attempting to model a WEC by modifying the RM3 Compressible Hydraulic PTO-Sim example. I do not see the information needed about some variables in the currently published PTO-Sim documentation (https://energy.sandia.gov/wp-content/uploads/2014/06/SAND2015-2069C.pdf).

**Describe the theory or implementation approach that you have a question**
Within PTO-Sim's Compressible Hydraulic RM3 example ptoSimInputFile.m are the following variables:
ptosim.checkValve.k1 
ptosim.pistonCF.pBi

How are these values calculated? How can they be calculated for a modified example?

**Personal project context**
I am modifying the RM3 Compressible Hydraulic PTO-Sim example to create a single piston pump with two check valves. This project is to model a wave-powered upwelling device.

**Describe the type of conclusion or resolution you are looking for**
I am looking for information on how to calculate the following for a modified version of RM3:
ptosim.checkValve.k1 
ptosim.pistonCF.pBi

**Additional context**
ptosim.checkValve.k1 appears to be a gain within the check valve library block; in the documentation k1 is listed as being >>0, however I am only able to have a working simulation if this value is very small (1*10^-7)
ptosim.pistonCF.pBi I'm currently interpreting this as the initial pressure within the bottom piston chamber - is that correct?

**Comment by jleonqu** [comment]
@ccz359 
The value of k1 for the check valve depends on the specific dynamic characteristics of the valve that you need to model. You need to choose the value depending on how fast your valve opens when it reaches the cracking pressure. Usually, you can find this information in the datasheet of the valve. To calculate the value of k1, you can use equation 3 from the reference in this [link](https://energy.sandia.gov/wp-content/uploads/2014/06/SAND2015-2069C.pdf).
Form the datasheet, you can have the cracking pressure of your valve, the flow rate, and the discharge coefficient. Then you can use equation 3 to calculate the value of k1.
This is a plot of the tanh(k1*deltaP) function for different values of k1:
![image](https://user-images.githubusercontent.com/72461917/233749611-29420a1d-e71b-4229-9d0d-1fd06a80338f.png)

As you can see, the value of the function changes more quickly for lower values of k1. You need to choose one that resembles the dynamic of your valve.

Regarding ptosim.pistonCF.pBi: Yes, it is the initial pressure in the bottom chamber of the piston.

**Comment by ccz359** [comment]
Hi @jleonqu ,

Thank you for the explanation regarding calculating the k1 value. 

To confirm, the Vi, or valve volumetric flow rate, is found from the valve's manufacturer's spec sheet and does not vary with time, is that correct? 

This would also mean that the units of k1 are an inverse pressure (1/Pa), correct?

Thank you!
