### ISSUE TITLE
[BUG] Mooring Library in wrong MATLAB Version and crashing MATLAB

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#1038]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
The mooring library was updated in PR #1012 to fix some moordyn crashing issues, but it was saved in R2022b, when we specify R2020b in our documentation (Issue #1037). I tried to revert the mooring library to R2020b and confirm that the PR's changes are still present, but my MATLAB crashes every time I try to look under the Mooring or MoorDyn block masks. 

**WEC-Sim file(s)**
_If known, please identify the the WEC-Sim files causing the bug or error:_
_Please upload relevant case files if possible to speed debugging._

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open WECSim_Lib_Moorings.slx
2. Click on the Mooring Matrix or MoorDyn block

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/87095491/233647818-bdf5cc0f-fe5d-4b11-b986-59e747315e27.png)

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2021b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v5.0.1]

**Additional context**

**Comment by akeeste** [comment]
I also tried saving the library version back to R2020b. I used R2022b to do this and do not have any crashing problems afterwards. #1040 should resolve this issue
