### ISSUE TITLE
[Feature request] Resampling WEC-Sim Output

### ISSUE THREAD

**Issue by jleonqu** [WEC-Sim/WEC-Sim#1039]
**Note: italicized text below is included as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.** 

**Is your feature request related to a problem? Please describe.**
_When running long WEC-Sim cases the output data can be very heavy to upload to GitHub, share drive, or email. It would be useful to have a function to resample the output data or select and specific time frame for the data_

**Describe the solution you'd like**
_Create a function to resample the output data or select and specific time frame for the data_

**Describe alternatives you've considered**
_Create a function in the output class to edit and post-process the results from WEC-Sim simulations_

**Personal project context**
_It is not related to any specific project_

**Additional context**
_N/A_

**Comment by akeeste** [comment]
5/2/2023 after team discussion. Closing this as an issue. Will add to project board or add to end of an application case as a reference that is outside of the source
