### ISSUE TITLE
[Theory or Implementation] Simulation Finishes but Unable to Stop Properly

### ISSUE THREAD

**Issue by yman95** [WEC-Sim/WEC-Sim#1043]
**Is your question request related to a problem? Please describe.**
When implementing WEC-Sim using a spherical shell, WEC-Sim will run and finish with animation and figures, but it can't properly stop. MATLAB gives the following error code:
```
Error using wecSim
Error evaluating 'StopFcn' callback of Frames block (mask) 'sphere_r5_archimedes/Global Reference Frame'.
Callback string is 'run('stopWecSim')'
Caused by:
    Error using wecSim
    Index exceeds the number of array elements. Index must not exceed 1.
```

I understand that it's a simple error throwing an out-of-bound array exception. I assume it tries to access more cases or geometries, but I have defined one body and one constraint in wecSimInputFile.m, so I don't understand where the error is coming from.

**Describe the theory or implementation approach that you have a question**
I have attached NEMOH's calculation and WEC-Sim folder for devs to reproduce. The folders should have all the information.

Calculated properties of the spherical shell:
Radius =5m
Thickness =0.1m
Material = aluminium, rho = 2710 kg/m^3
Mass = 83445.7693 kg
Weight = 818602.996833 N

Moment of inertia 1.3633E6 kg*m^2

**Personal project context**
Running a simple example to learn WEC-Sim

**Describe the type of conclusion or resolution you are looking for**
I would like to know where in the code was my error. Hopefully it's a simple fix.

[[WEC-Sim]sphere_r5_Cg0_CM1.zip](https://github.com/WEC-Sim/WEC-Sim/files/11334287/WEC-Sim.sphere_r5_Cg0_CM1.zip)

[[NEMOH]sphere_r5_Cg0_CM1.zip](https://github.com/WEC-Sim/WEC-Sim/files/11334291/NEMOH.sphere_r5_Cg0_CM1.zip)

**Comment by dforbush2** [comment]
1) Try 

>>clear; close all;

before running WEC-Sim

2) Check your path. This error happens a lot of times when the userDefinedFunctions.m is not included in the case directory (the location you are in in your path when you execute wecSim.m or run the simulink model). If you do not have a userDefinedFunctions.m somewhere in your case directory, wecSim.m will attempt to execute one found elsewhere in your file path. If this function errors, which is quite likely, given that it was made to post-process an entirely different model, it can create errors like this.

As a quick fix, try creating an empty script called userDefinedFunctions.m and save it to your case directory. This worked for me when tried with the *zip files you sent.

**Comment by yman95** [comment]
It worked, cheers. Thanks for the tip.
