### ISSUE TITLE
[BUG] Dev branch plotBEMIO

### ISSUE THREAD

**Issue by dforbush2** [WEC-Sim/WEC-Sim#1062]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
Try to run plotBEMIO w/ any run w/ >6 DOF. The following error appears:

```
Dot indexing is not supported for variables of this type.

Error in checkAndFormatPlotVars (line 33)
    if isequal(size(varargin{1}{ii}.plotDofs),[1 2]) && max(varargin{1}{ii}.plotDofs)-min(varargin{1}{ii}.plotDofs) == 0

Error in plotAddedMass (line 19)
varargin = checkAndFormatPlotVars(varargin);

Error in plotBEMIO (line 36)
plotAddedMass(varargin{:})

Error in bemio (line 8)

plotBEMIO([1,1;3,3;5,5;7,7],hydro);
```

**WEC-Sim file(s)**
_If known, please identify the the WEC-Sim files causing the bug or error:_
_Please upload relevant case files if possible to speed debugging._

**To Reproduce**
Run bemio on WAMIT data with a gbm or free-surface mode.

**Expected behavior**
Actually plot

**Screenshots**
_If applicable, add screenshots to help explain your problem. For example, a screen shot of the exact error message from the MATLAB command line._

**Workstation Information (this section MUST BE completed):**
Windows 10, matlab2022a and matlab2022b

**Comment by jtgrasb** [comment]
The format for the DOF specification has changed. Instead of specifying them before the hydro structure, they should be specified as part of the hydro structure. In this case, you can use:

hydro.plotDofs = [1,1;3,3;5,5;7,7];
plotBEMIO(hydro);
