### ISSUE TITLE
[Developer Issue] Wave markers documentation needs update

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#1066]
**Project**
The documentation for the wave markers (in advanced features section) needs to be updated to the latest variable names.

**Describe the issue**
The advanced features documentation for the wave markers is referring to outdated variables such as waves.markLoc when it should refer to waves,marker.location.

**Comment by salhus** [comment]
@jtgrasb 
Hi Jeff,
The documentation has been updated along with #1130
