### ISSUE TITLE
Does the PTO-Sim block in  WEC-Sim v2.0 (pre-release) “can accept  user defined forces/values in hopes of providing real-time control. “? 

### ISSUE THREAD

**Issue by wyg110** [WEC-Sim/WEC-Sim#107]
Dear  Dr.  Nathan Tom:   
 
      It is my pleasure to contact you again, and I am  a researcher from the Ocean Engineering 
Department of Shanghai Jiao Tong University.  I am  very interested in the WEC-Sim 
(Wave Energy Converter SIMulator) software. I wrote you a year ago regarding whether
the WEC-Sim software include any controller rountine or controller design rountine. 
 You replied me that “In the future, it is hoped that the PTO blocks will accept 
user defined forces/values in hopes of providing real-time control. “.

Now I find that WEC-Sim v2.0 (pre-release) have the following features: 
•	More general constraint, PTO, and mooring implementation
•	More realistic PTO and mooring modelling through PTO-Sim and integration with MoorDyn
Does the PTO-Sim block in  WEC-Sim v2.0 (pre-release) “can accept 
user defined forces/values in hopes of providing real-time control. “? 
Please kindly reply me regarding this issue. Many thanks.

Sincerely,
 
Yingguang Wang,  Ph. D

发件人: Tom, Nathan [mailto:Nathan.Tom@nrel.gov] 
发送时间: 2015年4月2日 2:29
收件人: wyg110
主题: RE: whether the WEC-Sim software include any controller rountine or controller design rountine?

Yingguang Wang,
                Thank you for your interest in WEC-Sim.  WEC-Sim currently does not have the ability to implement its own control routine.  In the future, it is hoped that the PTO blocks will accept user defined forces/values in hopes of providing real-time control.  At the moment, in order to obtain the maximum energy generation one would have to iterate though various PTO coefficient values and simulate each case.  If you have any other questions please do not hesitate to ask.

Nathan Tom, Ph.D. | Postdoctoral Researcher| Marine Hydrokinetic Division| National Wind Technology Center| National Renewable Energy Laboratory| Work: 303-384-7159|

From: wyg110 [mailto:wyg110@sjtu.edu.cn] 
Sent: Monday, March 30, 2015 2:25 AM
To: Tom, Nathan
Subject: whether the WEC-Sim software include any controller rountine or controller design rountine?

Dear  Dr.  Nathan Tom:   
 
      It is our pleasure to contact you, and we are researchers from the Ocean Engineering 
Department of Shanghai Jiao Tong University.  We are very interested in the WEC-Sim 
(Wave Energy Converter SIMulator) software. Especially, can you please kindly tell us whether
the WEC-Sim software include any controller rountine or controller design rountine? 
 
      How can you achieve maximun energy generation with you WEC using some robust control
or optimal control algorithm?
 
    Thank you for your consideration, and I am looking forward to hearing from you at your convenience.
 
Sincerely,
 
Yingguang Wang,  Ph. D

 
 
    

__________ Information from ESET NOD32 Antivirus, version of virus signature database 11408 (20150401) __________

The message was checked by ESET NOD32 Antivirus.

http://www.eset.com

**Comment by yuyihsiang** [comment]
Hi Yingguang

Short answer is yes. You can pass user defined forces into the the PTO as needed. Please check "PTOs Sub-library" under code structure in WEC-Sim document

http://wec-sim.github.io/WEC-Sim/code_structure.html#wec-sim-library-input-simulink-model

Thanks,

--Yi-Hsiang
