### ISSUE TITLE
[Theory or Implementation]

### ISSUE THREAD

**Issue by Omirzadeh** [WEC-Sim/WEC-Sim#1074]
Dear sirs,
I have a problem with the state space model of radiation forces in Wec Sim. 
Why Wec Sim returns a non-zero Dr matrix?

**Comment by dforbush2** [comment]
Hi @Omirzadeh 

We require submitted issues to follow templates. The template for your question is found here:

 https://github.com/WEC-Sim/WEC-Sim/issues/new?assignees=&labels=&projects=&template=theory-or-implementation-clarification.md&title=%5BTheory+or+Implementation%5D

This will allow us to assist you more effectively. Please re-submit your issue using the appropriate template.
