### ISSUE TITLE
Issue with installing BEMIO

### ISSUE THREAD

**Issue by mprevisic1** [WEC-Sim/WEC-Sim#1077]
**Describe the bug**
I cloned Bemio and try to run install.py, but it gives me an error message that it cannot find a module called bemio._version_

**WEC-Sim file(s)**
NA

**To Reproduce**
1. I installed the latest version of python (I am on 3.11.4)
2. I used pip install to add the required libraries including: numpy, script, matplotlib, progressbar2, astrophy, h5py
3. I cloned Bemio from GitHub using the git install command
3. I used the command line to execute install.py.

**Expected behavior**
Installation

**Screenshots**
![image](https://github.com/WEC-Sim/WEC-Sim/assets/101606944/10e43b5b-8f68-437a-a2ce-3c486dc5f55e)

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10 Pro

**Additional context**
NA

**Comment by mprevisic1** [comment]
I downloaded instead of cloning the repository and now it seems to find the required file during install (the download version seems to have many more files then the cloned version). However, now I have issues running the install_test.py file. Here is the error:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/101606944/985aea51-bcaa-454b-82ba-bf64278d875d)

**Comment by dav-og** [comment]
Hi @mprevisic1
Its been a while since we supported the Python version of BEMIO - we've only been working on the MATLAB version over the past couple of years. However, I have heard from a few people recently that they would benefit from having the Python BEMIO "revived" - is that something you need in your project? or could you just use the MATLAB version of BEMIO?
Cheers,
Dave

**Comment by mprevisic1** [comment]
David,

I did not know that there was a Matlab version. Where would I find that?

Thanks,

Mirko

**Comment by mprevisic1** [comment]
Dave,

I was wondering why Bemio was a python code - seemed like unnecessary
complexity :-) I would suggest you update the Bemio documentation online (
http://wec-sim.github.io/bemio/) and point to the fact that Bemio can now
be found in Matlab.

Thanks,

Mirko
