### ISSUE TITLE
[Theory or Implementation]

### ISSUE THREAD

**Issue by benhopkinson** [WEC-Sim/WEC-Sim#1089]
Hi guys, 

I am new to WEC-sim and am trying to load the example OSWEC files in matlab, I am coming across these error messages and I am stumpt. apologies for the simplicity but if someone could give me a hand with this it would be great. Cheers!
<img width="1064" alt="Screen Shot 2023-07-30 at 10 47 31 pm" src="https://github.com/WEC-Sim/WEC-Sim/assets/140963622/8969dfb7-fcc2-42ee-93f6-59be345e5476">

**Comment by nathanmtom** [comment]
Thank you for your question at @benhopkinson . We have begun requiring users to open GitHub issues using an appropriate template. This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "**XXXXX**" template and include more details on your setup and error message, I am happy to help. Please maintain the template structure and the issue type in the title. When creating an issue, please use the GitHub templates:
![image](https://user-images.githubusercontent.com/72414466/136063813-fd362db2-9943-4d45-a596-1b0c6fe6ba18.png)
![image](https://user-images.githubusercontent.com/72414466/136063890-8065ff72-f963-476e-a1cc-5cc4b813269d.png)
![image](https://user-images.githubusercontent.com/72414466/136064000-a42c5d5b-0950-4c00-95c2-e5596294675a.png)

This information is important for us to accurately assess what an issue is, how it occurs, and most quickly create a solution for you. It also helps us categorize our issues to determine areas of future improvement. Please maintain the template structure (bold headings). ​

**Comment by nathanmtom** [comment]
@benhopkinson We are still waiting back for you about this issue. Please provide an update by this Friday, August 11th or else we will close this issue due to inactivity.

**Comment by benhopkinson** [comment]
Apologies @nathanmtom
I will make sure to follow this format from now on. FYI My error occured due to matlab simulink not being installed properly. 
Cheers
