### ISSUE TITLE
[BUG] Potential Bug: Accelerator and Rapid Accelerator modes giving errors

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#1099]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
When trying to run WEC-Sim using the accelerator or rapid-accelerator mode, I get the following error:
<img width="721" alt="image" src="https://github.com/WEC-Sim/WEC-Sim/assets/87095491/13cd9db5-19b8-423f-ad5d-f30a019827cb">

**WEC-Sim file(s)**
Unknown

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to RM3 example
2. Set simu.mode = 'accelerator'
3. Run WecSim from command window

**Expected behavior**
WEC-Sim to run without error

**Screenshots**

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) 2021b and 2022b
 - [WEC-Sim Release] v5.0

**Additional context**_

**Comment by kmruehl** [comment]
resolved by #1100
