### ISSUE TITLE
OSWEC Tutorial (rotational PTO?) problem

### ISSUE THREAD

**Issue by cmcnatt** [WEC-Sim/WEC-Sim#111]
Hi, I need a rotational PTO. I'm trying the OSWEC tutorial example. When I run it, I get the following error:

['OSWEC/Flap/Hydrodynamic Body/Structure/Body Properties', 'OSWEC/Flap/Hydrodynamic Body/Structure/External Force and Torque', 'OSWEC/Flap/Hydrodynamic Body/Structure/Motion Sensor', 'OSWEC/Flap/Hydrodynamic Body/Structure/RigidTransform (Setup CG)', 'OSWEC/Flap/Hydrodynamic Body/Structure/Rigid Transform (Setup Initial Disp)',
'OSWEC/Flap/Hydrodynamic Body/Structure/Simulink-PS Converter1', 'OSWEC/Flap/Hydrodynamic
Body/Structure/Simulink-PS Converter2', 'OSWEC/Flap/Hydrodynamic Body/Structure/World Frame']: Each physical network must be connected to exactly one Solver Configuration block. There is no Solver Configuration block connected to Physical Network with the following blocks: 'OSWEC/Flap'

The RM3 example works fine (unless I switch the translational PTO with a rotational one).

Thanks!
Cameron

**Comment by yuyihsiang** [comment]
Hi Cameron

It was a broken link in the Simulink Lib. I have fixed it and update the WEC-Sim source code. Please download the latest version.

Thanks,

--Yi-Hsiang
