### ISSUE TITLE
[BUG] WEC-Sim Applications Free_Decay Tests Are Not Passing

### ISSUE THREAD

**Issue by nathanmtom** [WEC-Sim/WEC-Sim#1129]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
The WEC-Sim Applications Tests for Free Decay are not passing online, but passing locally.

**WEC-Sim file(s)**
The issue appears to be in the `Dev` branch being used to run the Free Decay Tests. Impacting all new WEC-Sim Applications Pull Requests.

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to WEC-Sim_Applications_
2. _Go to Free_Decay_
3. _runtests("TestFreeDecay.m")_

**Expected behavior**
Expect the tests to be passing

**Screenshots**
![image](https://github.com/WEC-Sim/WEC-Sim/assets/7635064/e827dda0-420d-4bf3-bba7-cda1a9e13d6a)

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 10]
 - [MATLAB/Simulink Release] [2022b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v5.0.1]

**Additional context**
_WEC-Sim Team will need to investigate why the simu.adjMassFactor is not being recognized_

**Comment by akeeste** [comment]
Hi @nathanmtom 

This bug was resolved in the Applications repo in https://github.com/WEC-Sim/WEC-Sim_Applications/pull/47
