### ISSUE TITLE
Center of gravity problem [BUG]

### ISSUE THREAD

**Issue by Tytoubi** [WEC-Sim/WEC-Sim#1137]
Hello, 

I'm having an issue to add the good center of gravity on my wecSim model based on RM3.
How can I change the Body CG variable that appear when we run the simulation ? 

	***** Body Number 1, Name: float *****
	Body CG                          (m) = [0,0,-0.72]
	Body Mass                       (kg) = 7000 
	Body Diagonal MOI              (kgm2)= [2.09073E+07,2.13061E+07,3.70855E+07]

	***** Body Number 2, Name: spar *****
	Body CG                          (m) = [0,0,-21.29]
	Body Mass                       (kg) = 9000 
	Body Diagonal MOI              (kgm2)= [9.44196E+07,9.44071E+07,2.85422E+07]
	
Thanks for your support

**Comment by jtgrasb** [comment]
@Tytoubi  Thank you for your question. When creating an issue, please use the GitHub templates:

![image](https://user-images.githubusercontent.com/72414466/136063813-fd362db2-9943-4d45-a596-1b0c6fe6ba18.png)
![image](https://user-images.githubusercontent.com/72414466/136063890-8065ff72-f963-476e-a1cc-5cc4b813269d.png)
![image](https://user-images.githubusercontent.com/72414466/136064000-a42c5d5b-0950-4c00-95c2-e5596294675a.png)

This information is important for us to accurately assess what an issue is, how it occurs, and most quickly create a solution for you. It also helps us categorize our issues to determine areas of future improvement. Please maintain the template structure (bold headings). ​

Please either modify your initial issue to follow the template or close this issue and re-open a new issue.
