### ISSUE TITLE
addWecsimsource.m

### ISSUE THREAD

**Issue by Khalid-1994-06-17** [WEC-Sim/WEC-Sim#1146]
Hello for the addWecsimsource.m, do I have to copy the code into startup.m or do I have to run addWecsimsource.m?

**Comment by dav-og** [comment]
Hi again @Khalid-1994-06-17,

Again, please fill in an issue template in the future (refer to my previous post for more information about that).

I think your question is answered in the YouTube video that I shared in my previous post: https://youtu.be/SUA_6Nd1w9g

I would recommend checking out all of these YouTube training videos, as they probably contain the answers to a lot of the questions you're asking.

Cheers,
Dave
