### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by Khalid-1994-06-17** [WEC-Sim/WEC-Sim#1147]
Is there a way I can use Reinforcement Learning from the WEC-Sim?

**Comment by dav-og** [comment]
Hi @Khalid-1994-06-17,

We have looked into using MATLAB's RL toolboxes in the past, but we don't yet have a public demo for this. Hopefully that will be coming soon.

If you're working on this topic too, perhaps we should combine our efforts? Feel free to reach out to me directly: david.ogden.nrel@outlook.com

Cheers,
Dave
