### ISSUE TITLE
Added mass instability for free falling object

### ISSUE THREAD

**Issue by BjarkeEltardLarsen** [WEC-Sim/WEC-Sim#1157]
**The development team requests that before submitting a question on the theory and implementation behind WEC-Sim to first please:**
1. Read through our [WEC-Sim Documentation](http://wec-sim.github.io/WEC-Sim/man/theory.html) with additional description found in our [Advanced Features Section](http://wec-sim.github.io/WEC-Sim/man/advanced_features.html)
1. Review MATLAB source code ([functions](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions), [objects](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/objects)) and the Simulink blocks ([libraries](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/lib))
1. Review the curated [WEC-Sim Examples](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples) and the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications)
1. Review the [WEC-Sim issues page](https://github.com/WEC-Sim/WEC-Sim/issues) which allows you to search past resolved issues or questions that might help answer your own question.

**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
I am simulating a falling object using a morison element. If I do not include the added mass terms (either by setting VME=0 or ca=0) I get the desired result. If I include added mass (for this case it should not be important, but I want to use it for other cases) the simulation goes unstable. I have tried simulating a moored buoy including added mass and here it does not go unstable, and I actually need it for good results. However, if I cannot even solve a falling object I have little faith in the implementation. 

**Describe the theory or implementation approach that you have a question**
I am asking about the usage of morison elements. Specifically how to best include the added mass and avoid it going unstable. In some of the application examples provided, the VME setting is extremely low compared to the size of the structure. For a fully submerged structure I was under the impression that body(ii).morisonElement.VME should be equal to the volume of the structure. Is this correct? 
Could my issues be related to body(iBod).adjMassFactor. I have tried different values but the problem persists.

**Personal project context**
I am attempting to use WEC-SIM for simulating the movement of moored musselfarms. I am going to have a combination of floating and non-floating object. Before simulating the really complex cases I wanted to validate WEC-SIM for the simple case of a falling object (basically I wanted to see that I get the terminal velocity right). 

**Describe the type of conclusion or resolution you are looking for**
Is there hope for making this kind of simulation with wecsim or is it unavoidable due to the treatment of the added mass

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by akeeste** [comment]
Hello @BjarkeEltardLarsen 

At first read, this free sinking case does not seem to fit with the intended use of WEC-Sim. It may work, but with an atypical set-up. The hydrodynamic forces that WEC-Sim applies to a hydro body are derived for a system oscillating about the still waterline. If stiffness, radiation damping, or added mass (whether through hydrodynamic forces or a Morison Element) are being applied to the body, I would not expect a free falling case to perform well. If you simulate a drag body with viscous drag (i.e. a body with mass, buoyancy, drag and without hydrodynamic or Morison element forces) then I expect your case to perform better. I suggest using noWave and regular wave cases with a typical hydro body set-up for your validation and testing.

It would be very helpful if you can upload your case file for us to understand what instability is going on. Also, please describe the case that you're describing further, including:
- What geometry are you simulating?
- Is this shape freely falling down to the seabed?
- Are hydrodynamic forces (excitation, radiation damping, added mass, etc) being applied in addition to the Morison Element forces?
- What wave conditions are you testing in?

**Comment by BjarkeEltardLarsen** [comment]
Thank you for your fast reply.
I know my usage is outside the intended usage, but I did not use a hydrobody for this case but rather just a morison element. Therefore the geometry is not that important. I specified drag coefficients, volumes and areas in correspondance with a cube.  I think you are right that a pure drag body would work. This is also indicated by the fact that I get good results with the Morison Element when I turn off the added mass. 
In my simple test case here with a freely falling object I do not have waves, though the problem persist in waves. With out the added mass in the Morison elements I can also match theoretical settling trajectories in waves reasonably well. 

I have tried to upload the file but github will not accept it. Below follows my script. The simulink model is simple it is just a body with a six degree of freedom constraint. I have tried both versions of the Morison Elements and they all give the same result. Reducing the time step significantly also does not help. When I run with the added mass on the fist few time steps give the same results as when it is off, before going unstable. I have attached images of the vertical velocity with and without the added mass included in the morison calculations. 
![admass](https://github.com/WEC-Sim/WEC-Sim/assets/41331462/612ae7d6-93dc-4515-9065-b041eb40f5ed)
![noadmass](https://github.com/WEC-Sim/WEC-Sim/assets/41331462/9ed6d57e-bb0a-4542-b5b2-324ad4cd4804)


%% Simulation Data
simu = simulationClass();                
simu.simMechanicsFile = 'cylinderNoMooring.slx';  
simu.solver='ode4';                    % 'ode4' for fixed step or 'ode45' for variable step 
simu.mode = 'normal';                   % Specify Simulation Mode ('normal','accelerator','rapid-accelerator')
simu.explorer='off';                     % Turn SimMechanics Explorer (on/off)
simu.startTime = 0;                     
simu.rampTime = 0;                        
simu.endTime=10;        
simu.dt = 0.001;    
%simu.dtOut=100*simu.dt
simu.rho=1025;                                                                                                           
%% Wave Information
% Regular Waves 
waves = waveClass('noWave');                 
waves.height = 10;                            
waves.period = 8.33;    
waves.current.option=0;
waves.current.speed=0;
waves.current.direction=0;
waves.current.depth       =70;  
waves.bem.range = [0 10]; % Must define wave frequency range without an .h5 / hydro body
waves.waterDepth = 30;    % Must define water depth without an .h5 / hydro body

%% Body Data
%body(1) = bodyClass('hydroData/MPParticle.h5');
body(1) = bodyClass('..');
          
body(1).inertia = [1e0 1e0 1e0];      %does not affect the solution as it is only a morison element
body(1).centerGravity=[0 0 0];
body(1).centerBuoyancy=[0 0 0];
body(1).volume=1.5e-7;
body(1).mass = body(1).volume*1030; 
body(1).initial.displacement = [0 0 -6];
body(1).nonHydro = 2; 
body(1).morisonElement.option = 1;

body(1).morisonElement.VME = body(1).volume;
%body(1).morisonElement.VME = 0;
body(1).morisonElement.rgME = [0 0 0];
body(1).morisonElement.z = [0 0 1];
body(1).morisonElement.cd = [1 1 1];
body(1).morisonElement.ca = [0.5 0.5 0.5];
body(1).morisonElement.area = [2.5e-5 2.5e-5 2.5e-5];
%body(1).adjMassFactor=2
%body(1).largeXYDisplacement.option = 1

% Fixed Constraint
constraint(1) = constraintClass('Constraint1'); 
constraint(1).location = [0 0 0];

**Comment by akeeste** [comment]
@BjarkeEltardLarsen 

I replicated your case and tested different settings. I agree that the Morison Element added mass force is driving the instability, as you correctly identified above. However I do not think we should expect the added mass to be stable in this situation. Since this case is not a thin cylinder in an oscillating flow, the Morison Element derivation does not apply and added mass force should not be used.

Additionally, the initial condition, scale of the mass, and scale of the time step combine to create a very difficult numerical problem at the start of the simulation. The body is not at equilibrium at the start of the simulation, so there is an initial acceleration, both physical and likely numerical as well. Because the mass is so small (~ 1e-4) and the time step relatively large compared to the mass, the initial acceleration causes in an inaccurately large added mass force which immediately makes the simulation oscillate unstably. Simulink will require an incredibly small time step to simulate the initial motion correctly. If you drastically increase the body mass and apply a smaller time step, I think you would eventually see that the initial condition is satisfied correctly. Note the ramp function only applies to excitation and current forces and does not help in this case. 

The better solutions to test the terminal velocity are to remove the Morison Element added mass components (Ca=0) or use the drag body with viscous drag, as we discussed above. In those cases, I see that the velocity exponentially decays to its terminal value as we expect.

**Comment by BjarkeEltardLarsen** [comment]
I had actually implemented my code slightly different that wecSim. I added the mass and added mass together when solving the system WECSIM does not.

**Comment by akeeste** [comment]
@BjarkeEltardLarsen This last point is actually a very critical part of this instability. What degrees of freedom are you accounting for in your simulations?

We are currently limited by Simscape Multibody's definition of mass, which does not allow a 6x6 mass matrix. I believe it could be feasible for a single body, but can't be done generally for a multibody system with off-diagonal added mass terms. So, we move part of the added mass into the body mass during simulation to decrease the magnitude of the added mass force, which is dependent on the previous acceleration interpolated to the current time step. I recommend reviewing our [Developer Manual's section on WEC-Sim's added mass implementation](https://wec-sim.github.io/WEC-Sim/master/developer/advanced_features.html#added-mass).

If you have other thoughts or suggestions on how we can improve the added mass implementation, please let me know.

**Comment by BjarkeEltardLarsen** [comment]
When not considering hydrobodies and mooring I have confirmed that isolating dv/dt in the governing equations and replacing the acceleration in the morison equation with that expression gives the correct stable result when using wecsim. This is however probably not a viable solution when dealing with hydrobodies and moored systems. 

Presently I understand why the instability occurs, but I have not come up with an elegant solution. I have some ideas for hacks which I will try, and if they work I will keep you posted. 

I have also made another small change in my wecsim code (so far only for regular waves). This involves the fluid acceleration term in the morison equation. In the case of non-uniform flow this term should be the material derivative, i.e. also including convective acceleration. For linear waves this can easily be implemented.

**Comment by akeeste** [comment]
@BjarkeEltardLarsen It sounds like we have consensus on why the instability occurs, so I'll close this issue next week. If you ever have a robust solution for the added mass problem and want to contribute, please feel free to re-open this issue for discussion or create a pull request with your suggestion. If you have further questions, feel free to continue our discussion thread.

**Comment by reos-rcrozier** [comment]
I once modified mbdyn to have a more stable version of added mass for my fork of wecsim, see the following mbdyn issue:

https://public.gitlab.polimi.it/DAER/mbdyn/-/issues/58

**Comment by akeeste** [comment]
Thanks @reos-rcrozier I'll review that work and reach out if I have any questions
