### ISSUE TITLE
[WEC-Sim Applications] RM3 simulation problems

### ISSUE THREAD

**Issue by Wilton3737** [WEC-Sim/WEC-Sim#1158]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
RM3 simulation is not running after i typed wecSim
it display an error code that states it is trying to locate OSWEC while I am trying to run RM3. This has got me confused.

however, I made the extra effort to build the OSWEC Simulink model following the tutorial but the error persisted

I have checked through my path and made sure that all the path is added into matlab.

**WEC-Sim file(s)**
_If known, please identify the the WEC-Sim files causing the bug or error:_
i do not know the source of this problem
_Please upload relevant case files if possible to speed debugging._

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

_State method of running WEC-Sim (command line, from simulink with input file, from simulink with custom parameters)_
everything is following the tutorial nicely
**Expected behavior**
error code displaying of not locating OSWEC sls

**Screenshots**
_If applicable, add screenshots to help explain your problem. For example, a screen shot of the exact error message from the MATLAB command line._

![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/eb96d228-9385-49e6-93f8-10768edf9c0b)
FIGURE 1: error code

![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/0591a72e-46aa-4366-ade2-670d7bb3e703)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/407f0049-706a-44d6-8b6a-c12dfe0a6b13)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/3bb554f4-8515-4f41-b716-59d8350097bb)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/9a33c79b-d86b-4682-a39f-ca5f785f65f5)
FIGURE 2,3,4,5: matlab path

Thanks in advance for addressing my issue. thank you very much

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 11 version22H2]
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2022b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v6]

**Additional context**
_Add any other context about the problem here._

**Comment by akeeste** [comment]
Hello @Wilton3737 

 Thank you for your question. We require users to open GitHub issues using an appropriate template. This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

Please reopen or modify your issue using the "Edit" button above to add the template back in and fill out the corresponding sections. I suggest using the bug template as the most appropriate for your question. Additionally, I suggest searching closed issues for similar problems as the solutions may be available.

**Comment by Wilton3737** [comment]
hello @akeeste 

thanks for replying. Note that i have edited my issue according to the template provided. Please have a look. Please let me know if u need further information. 
thank you very much

**Comment by akeeste** [comment]
Hi @Wilton3737

Thank you for following our template. I have a few solutions for you to try first:

1. Remove ``WEC-Sim`` from the MATLAB path. There are multiple example and tutorial models files contained there, and this may cause ``OSWEC/wecSimInputFile.m`` to be used before ``RM3/wecSimInputFile.m``. Only add the subdirectory ``WEC-Sim/source`` to the MATLAB path. 
2. If the above does no work, confirm that  ``simu.simMechanicsFile`` is set to ``'RM3.slx';`` Refer to ``examples/RM3/wecSimInputFile.m`` if needed as that is a fully set-up case that should function as is.

If those two solutions do not work, please let me know and we can look at other solutions.

**Comment by Wilton3737** [comment]
Hi @akeeste 
I have done the following, now this is my path description
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/23a0ff39-cbfd-4f8e-be82-86b2716856cd)
set simu.simMechanicsFile  to RM3.slx
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/cae258ca-612f-4b0c-96db-ad6dac5acf60)

However, here pops up another error code stating that it cant locate rm3.h5 file
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/58c60614-91ca-405d-91d7-0ca217841355)
meanwhile my rm3.h5 file is located at wecSim
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/25b6c5df-6d3c-4933-a1df-363b2c307e93)

Please guide me to fix this error. Thank you very much

**Comment by akeeste** [comment]
Hello @Wilton3737 

The file is not being found because it appears that the path input to the bodyClass is incorrect. The body class is looking for ``hydroData/rm3.h5`` but the .h5 file is located in the WEC-Sim directory. Update the path pointing to the the H5 file used in 
``body(1 = bodyClass('FILEPATH')``

To help organize the case files and run your simulation smoothly, I suggest keeping all case-specific input files (wecSimInputFile.m, userDefinedFunctions.m, \*.slx, hydroData/rm3.h5, geometry/\*.stl, etc) inside of a single directory, such as ``tutorials/RM3/``

The our [RM3 Tutorial Documentation](https://wec-sim.github.io/WEC-Sim/master/user/tutorials.html#rm3-tutorial) can assist in walking through the creation of your first case. When completing the files in ``WEC-Sim/tutorials/RM3``, refer to ``WEC-Sim/examples/RM3`` for a complete, correct version of each file.

**Comment by Wilton3737** [comment]
Hi @akeeste 
thanks for your support, i have successfully run the RM3
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/b8d75d4e-ea84-4c49-95e9-22e0151cc78c)

Now, I still need your support to teach me how to generate a graph for power production
to specify the scope 
i need a WEC system uses direct drive linear generator to produce a power output. then save the power output in Matlab data format. 
this power output will be further put into a simulink model to smooth out the graph( dont worry about this part as i alr have a solution)
all in all, please teach me how to use a linear drive generator and RM3 to generate a power output data

**Comment by akeeste** [comment]
@Wilton3737 I suggest reviewing our documentation on [Constraints/PTOs](https://wec-sim.github.io/WEC-Sim/master/user/advanced_features.html#constraint-and-pto-features) and our[ PTO-Sim application](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim/RM3/RM3_DD_PTO) that uses an [RM3 with linear generator](https://wec-sim.github.io/WEC-Sim/master/user/advanced_features.html#rm3-with-direct-drive-pto). Please let me know if you have further questions are reviewing these documentation cases and the RM3 PTO-Sim cases.

**Comment by Wilton3737** [comment]
Hi @akeeste 
thanks for your guidance. I have successfully generated the power profile
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/a9dfa388-6222-4190-ab5f-dda8cda14276)

Now. I would have to design a small linear drive generator, something that looks similar to RM3.
How can I generate the out file?
I read that it requires running WAMIT but I am having problems downloading it.
Can I just modify the dimensions of RM3, generate a stl file to replace the previous RM3 and run BEMIO?

Hope you can clarify my questions. Thank you.

**Comment by akeeste** [comment]
@Wilton3737 do you have any additional questions on this issue? if not, I'll close this out next week.

Thanks, Adam

**Comment by Wilton3737** [comment]
@akeeste 
Thanks for your help. I am currently dealing with capytaine to produce BEM code. you may close this issue.
thank you
