### ISSUE TITLE
[Theory or Implementation]

### ISSUE THREAD

**Issue by Wilton3737** [WEC-Sim/WEC-Sim#1161]
**The development team requests that before submitting a question on the theory and implementation behind WEC-Sim to first please:**
1. Read through our [WEC-Sim Documentation](http://wec-sim.github.io/WEC-Sim/man/theory.html) with additional description found in our [Advanced Features Section](http://wec-sim.github.io/WEC-Sim/man/advanced_features.html)
1. Review MATLAB source code ([functions](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions), [objects](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/objects)) and the Simulink blocks ([libraries](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/lib))
1. Review the curated [WEC-Sim Examples](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples) and the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications)
1. Review the [WEC-Sim issues page](https://github.com/WEC-Sim/WEC-Sim/issues) which allows you to search past resolved issues or questions that might help answer your own question.

**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I do not understand why I get 'X' result when running 'Y' simulation [...]_
I would like to generate a new out file from a self-designed stl file. I have read that I need to run WAMIT. 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/149406844/edd989b1-8e7a-40d4-8228-922d0d22d6a3)
this is the WAMIT I have installed, but nothing happens after I click it

**Describe the theory or implementation approach that you have a question**
_Please clearly describe the assumptions, equations, or code script that you would like clarification. Also, please provide references to other research papers, open-source material, or other information that may be relevant in the WEC-Sim developers understanding your question._

**Personal project context**
_If this request is related to your project, please describe what you are attempting to do in your project so the WEC-Sim development team knows your end goal._
I am trying to investigate about small scale wave energy genrator. this is my project title: Small-scale wave energy microgenerators and storage for offshore power generation. 
the methodology is:
1. use WecSim to generate a power output data 
    1.1 the WEC is new self drawn model, so i have to use WAMIT to produce out file
    1.2 the power output data is load into a simulink model to smooth out the power (this part i already have a solution)

**Describe the type of conclusion or resolution you are looking for**
1. how to generate out file
2. how to generate a power output data

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by akeeste** [comment]
Hello @Wilton3737 

Thanks for using our issue template. Unfortunately the WEC-Sim Development Team are not involved with WAMIT development and cannot provide help on generally installing or running WAMIT. I recommend reaching out to WAMIT developers for assistance. WEC-Sim can also read Boundary Element Method data from NEMOH, Capytaine, or Aqwa.

**Comment by Wilton3737** [comment]
Hi @akeeste 
I have downloaded NEMOH but find no clue to use. Do you have relevant tutorials i can refer to?

thanks

**Comment by akeeste** [comment]
@Wilton3737 If you want to pursue a free, open-source BEM software, I recommend using Capytaine. NEMOH is no longer  supported. Capytaine is based on NEMOH's core functionality, has been greatly refactored in Python, and is currently supported. [Capytaine](https://github.com/capytaine/capytaine)

**Comment by Wilton3737** [comment]
@akeeste noted with thanks. appreciated your help

**Comment by akeeste** [comment]
@Wilton3737 do you have any additional questions on the BEMIO side or about the hydrodynamics going into WEC-Sim? Unfortunately we can't give further support on using BEM codes themselves. I encourage you to reach out to those developers if you have questions.
