### ISSUE TITLE
[WEC-Sim Applications]

### ISSUE THREAD

**Issue by LiyangMa1277** [WEC-Sim/WEC-Sim#1163]
Hi, I'm studying this program and using the RM3 model to run and get data. In the workspace data, I noticed that the AmpTime variable and elevation variable data are the same. Are these two the same physical quantity? Many thanks.

**Comment by nathanmtom** [comment]
Thank you for your question at @LiyangMa1277. We have begun requiring users to open GitHub issues using an appropriate template. This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "**WEC-Sim Applications**" template and include more details on your setup and error message, we are happy to help. Please maintain the template structure and the issue type in the title. When creating an issue, please use the GitHub templates.

This information is important for us to accurately assess what an issue is, how it occurs, and most quickly create a solution for you. It also helps us categorize our issues to determine areas of future improvement. Please maintain the template structure (bold headings). ​
