### ISSUE TITLE
Questions about MOST output

### ISSUE THREAD

**Issue by cc200528** [WEC-Sim/WEC-Sim#1168]
Hi, I have read your WEC-Sim Documentation,  if I want to use MOST to generate displacement time history, velocity time history, acceleration time history, etc., for some points on the top of the tower, what should I do

**Comment by jtgrasb** [comment]
Thank you for your question at @cc200528 . We have begun requiring users to open GitHub issues using an appropriate template. This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "WEC-Sim Applications" template and include more details on your setup and error message, I am happy to help. Please maintain the template structure and the issue type in the title. When creating an issue, please use the GitHub templates.

This information is important for us to accurately assess what an issue is, how it occurs, and most quickly create a solution for you. It also helps us categorize our issues to determine areas of future improvement. Please maintain the template structure (bold headings). ​
