### ISSUE TITLE
Unable to add wec-Sim path to Matlab [BUG]

### ISSUE THREAD

**Issue by BinoBK** [WEC-Sim/WEC-Sim#1174]
**Describe the bug**
I am unable to add the wecSim path to Matlab even after following the instructions as per documentation.

**WEC-Sim file(s)**
_addWecSimSource.m

**To Reproduce**
_Steps to reproduce the behavior:_
1. Add WEC-Sim to the MATLAB Path as per Option 1 or Option 2 of Documentation. 
2. Verify the path by typing "path" in command window. 

**Expected behavior**
_I am trying to add the source directory 'C:\3.0 WEC-Sim v6.0\source'. 
The source directory, and its subfolders should be listed in Matlab path. 

**Screenshots**
1. Screenshot of 'Set path' in Matlab where intended 'source' directory is not getting populated.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/77161641/01237bce-17f3-4432-a8b9-8d933fd7b6ba)

2. Screenshot of results after typing "path" in command window where intended 'source' directory is not getting populated.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/77161641/7abc1683-deb9-4bad-9133-a24e2dd01a07)

3. Screenshot of Simulink window where wecSim Library is not getting populated. 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/77161641/6da918bb-3fba-43b2-8a1b-0f733b953d62)

**Workstation Information:**
 - OS: Windows 11
 - MATLAB/Simulink Release 2023b
 - WEC-Sim Release v6.0

**Additional context**
_NA

**Comment by nathanmtom** [comment]
Hello @BinoBK thank you for your question about the installation process and getting the path directory set. 

Reviewing your issue description, I believe you are not following the guidance properly. 

For Option 1 you need to put the `startup.m` in the MATLAB startup folder which should be your...\bino2\onedrive\Documents\MATLAB. The `startup.m` will not be set-up if kept in the WEC-Sim source directory. 

For Option 2, you do not edit `addWECSimSource.m` and need to navigate to the WEC-Sim Source Directory within MATLAB and run the function. The easiest way to do this is close MATLAB and then double click on `addWECSimSource.m` which will open MATLAB pointing to the folder where the function is located. 

Please try to implement these changes to your process to confirm you are able to add the path correctly.

**Comment by BinoBK** [comment]
Hello @nathanmtom, Thank you for the reply. I already tried both the options but in vain. 

For Option1, I pasted startup.m in the MATLAB startup folder. Screenshot is below: 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/77161641/87d9deed-c79e-4062-ade8-7615d55f6881)


For Option2, I executed the file addWECSimSource.m. Screenshot is here:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/77161641/0f1a154c-c1db-4750-b7ba-29462c055e0a)

 I am still not able to add wecSim to MATLAB path. Kindly advice and correct me if something I have done is wrong.

**Comment by nathanmtom** [comment]
@BinoBK Thank you for following up after my recommendation. 

It is hard to see from your screenshots as the Set Path overlaps with your MATLAB interface. I am going to focus on Option 2 as this should not require ensuring that the startup.m is in the right folder. 

I want to make sure that the following steps are being followed: 

1. The `addWecSimSource.m` is unmodified and is sitting in the folder above source (see red arrow in image below)
2. You run `addWECSimSource.m` with MATLAB pointing to the folder that holds all of the WECSim files (see green circle below).
3. Type `path` in the command line and see the WECSim added to path.

![image](https://github.com/WEC-Sim/WEC-Sim/assets/7635064/9241e24d-4368-4b83-a4d8-a4734af4cb46)

Based on your images below it looks like you moved `addWECSimSource.m` into the source folder which is not the appropriate installation procedure. 

Please confirm or attempt these steps and report back on your progress.

**Comment by BinoBK** [comment]
@nathanmtom The issue has been resolved. I had incorrectly placed addWecSimSource.m file inside 'source' folder. 

Thank you.
