### ISSUE TITLE
NL Hydro - Negative Hydrostatic Pressure?

### ISSUE THREAD

**Issue by bradling** [WEC-Sim/WEC-Sim#118]
When running `simu.nlhydro = 2;`, it appears that some cells have a negative hydrostatic pressure. Below is a histogram of all hydrostatic pressure values for an irregular wave case. 

I am having a hard time understanding how there could be negative values for hydrostatic pressure. Is there a physical meaning to these negative values, or is it an artifact of either the wheeler stretching or another numerical cause?

`hist(data.output.bodies(1).cellPressures_hydrostatic(:),100)` yields

![untitled](https://cloud.githubusercontent.com/assets/10558137/17495150/bc10ba08-5d6c-11e6-9b10-d281d403d604.png)

**Comment by yuyihsiang** [comment]
Hi Brad

The hydrostatic term represents the static part of the pressure from the hydrodynamic interaction. It is just the -rho*g*z term. The value will be negative if z is larger than zero. The dynamic part the pressure from the waves is calculated in the nonlinear FK force when the body is subject to waves. This is why simu.nlhydro = 2 is suggested for nonlinear hydrodynamic calculations.

-Yi-Hsiang

**Comment by bradling** [comment]
Ok I think I understand now. Thanks for the explanation.
