### ISSUE TITLE
Trying to run the wecSim on Python From MATLAB

### ISSUE THREAD

**Issue by Khalid-1994-06-17** [WEC-Sim/WEC-Sim#1197]
Hello just recently I was running wecSim on Python I was trying to call my MATLAB function to Python, everything seems to be working very well when running these codes

import subprocess
import matlab.engine
eng = matlab.engine.start_matlab()

# 1. Run addWecSimSource.m
print("> Step 1: Running addWecSimSource.m...")
eng.run('/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/addWecSimSource.m', nargout=0)
print("> Step 1 executed successfully!")
print("####################################################################################")

# 2. Run bemio.m from the hydrodata folder in the RM3 folder
print("> Step 2: Running bemio.m...")
eng.run('/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/hydroData/bemio.m', nargout=0)
print("> Step 2 executed successfully!")
print("####################################################################################")

# Full path to the template file
template_path = '/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/wecSimInputFile.TEMPLATE.m'
# Full path where you want to output the modified file
output_path = '/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/wecSimInputFile.m'

# Variables

time_start=0 # Write this in (seconds)
time_end=600 # Write this in (seconds)
dt=0.1 # Write this in (seconds)

waves_height = 8 # Write this in (meters)
waves_period = 5 # Write this in (seconds)
pto_stiffness = 0 # Write this in (Newtons/meters)
pto_damping = 1200000 # Write this in (Newtons/(meters/seconds))

# Define the command with the full paths and variables using f-string formatting
command = (
    f"sed 's/WAVES_HEIGHT/{waves_height}/g' '{template_path}' | "
    f"sed 's/WAVES_PERIOD/{waves_period}/g' | "
    f"sed 's/PTO_STIFFNESS/{pto_stiffness}/g' | "
    f"sed 's/TIME_START/{time_start}/g' | "
    f"sed 's/TIME_END/{time_end}/g' | "
    f"sed 's/DT/{dt}/g' | "
    f"sed 's/PTO_DAMPING/{pto_damping}/g' > '{output_path}'"
)

# Run the command
process = subprocess.run(command, shell=True, check=True)

# 3. Run wecSimInputFile.m
print("> Step 3: Running wecSimInputFile.m...")
eng.run('/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/wecSimInputFile.m', nargout=0)
print("> Step 3 executed successfully!")
print("####################################################################################")

# 4. Change directory
print("> Step 4: Changing directory...")
eng.cd('/Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/')
print("> Step 4 executed successfully!")
print("####################################################################################")

until I ran the code:

# 5. Execute wecSim
print("> Step 5: Executing wecSim...")
eng.eval('wecSim', nargout=0)
print("> Step 5 executed successfully!")
print("####################################################################################")

I got this output:
> Step 5: Executing wecSim...
WEC-Sim: An open-source code for simulating wave energy converters
Version: 5.0.1

Initializing the Simulation Class...
	Case Dir: /Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3 

WEC-Sim Input From Standard wecSimInputFile.m Of Case Directory... 
WEC-Sim: An open-source code for simulating wave energy converters
Version: 5.0.1

Initializing the Simulation Class...
	Case Dir: /Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3 
Elapsed time is 0.661502 seconds.

WEC-Sim Pre-processing ...   
	Infinite water depth specified in BEM and "waves.waterDepth" not specified in input file.
Set water depth to 200m for visualization.
Elapsed time is 0.147299 seconds.

WEC-Sim Simulation Settings:
	Start Time                     (sec) = 0
	End Time                       (sec) = 600
	Time Step Size                 (sec) = 0.1
	Ramp Function Time             (sec) = 100
	 Number of Time Steps     = 6000 

Wave Environment: 
	Wave Type                            = Regular Waves (Constant Hydrodynamic Coefficients)
	Wave Height, height (m)                   = 8
	Wave Period, period (sec)                 = 5

List of Body: Number of Bodies = 2 

	***** Body Number 1, Name: float *****
	Body CG                          (m) = [0,0,-0.72]
	Body Mass                       (kg) = 725833 
	Body Diagonal MOI              (kgm2)= [2.09073E+07,2.13061E+07,3.70855E+07]

	***** Body Number 2, Name: spar *****
	Body CG                          (m) = [0,0,-21.29]
	Body Mass                       (kg) = 886687 
	Body Diagonal MOI              (kgm2)= [9.44196E+07,9.44071E+07,2.85422E+07]

List of PTO(s): Number of PTOs = 1 

	***** PTO Name: PTO1 *****
	PTO Stiffness           (N/m;Nm/rad) = 0
	PTO Damping           (Ns/m;Nsm/rad) = 1.2E+06

List of Constraint(s): Number of Constraints = 1 

	***** Constraint Name: Constraint1 *****

Simulating the WEC device defined in the SimMechanics model /Users/khalidalnahyan/Documents/GitHub/WEC-Sim-master/examples/RM3/RM3.slx...   
Warning: Model 'RM3' was created with a newer version (R2023b) of Simulink
To create a model that is compatible with this version of Simulink, load the model in Simulink R2023b and select Save > Export Model to > Previous Version.
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 8): Tag "PortCounts" was not expected here
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 48): Tag "PortCounts" was not expected here
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 83): Tag "PortCounts" was not expected here
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 123): Tag "PortCounts" was not expected here
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 162): Tag "PortCounts" was not expected here
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 203): Attempt to set SrcPort with invalid Source
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 205): Attempt to set DstPort with invalid Destination
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 210): Attempt to set DstPort with invalid Destination
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 212): Attempt to set SrcPort with invalid Source
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 216): Attempt to set SrcPort with invalid Source
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 222): Attempt to set SrcPort with invalid Source
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: RM3 (systems/system_root.xml, line 224): Attempt to set DstPort with invalid Destination
> In load_system (line 21)
In simulationClass/loadSimMechModel (line 194)
In initializeWecSim (line 463)
In run (line 91)
In wecSim (line 43)
Warning: Cannot load version 'R2023a_20220628' of family 'slid'.
Warning: Cannot load version 'R2023a_202209151115' of family 'sltp_mm'.
Elapsed time is 0.331276 seconds.
------Error in the Model, Error-Causes/Messsages are :
> Step 5 executed successfully!
####################################################################################

When I tried to do these steps manually from MATLAB using the 2023b version it worked fine, the simulation managed to work, I am managing to get results from the manual work but when trying to call it on Python it won't be able to work and show the simulation, could you please help me find some guidance here are the specifications I am using:

Computer: iMac Pro 2017
Processor: 3.2 GHz 8-Core Intel Xeon W
Graphics: Radeon Pro Vega 56 8 GB
Memory: 32 GB 2666 MHz DDR4
Startup Disk: Macintosh HD
Serial Number: C02WC0C6HX87
macOS: 14.1.1 (23B81)

MATLAB version (academic use): R2023b Update 5 (23.2.0.2459199), 64-bit (maci64), November 28 2023

Python: I used Jupyter Lab version 3.2.1 from the Anaconda Navigator

It would be very helpful if you would reply back to me as soon as possible please since my semester is coming up and I might need to use this for my projects and my PhD thesis research.

**Comment by salhus** [comment]
@Khalid-1994-06-17 
Exciting to see you got it going.  I am not sure I quite followed the question or the issue?  
Maybe try a simple python file. I am afraid this could be due jupyter and ipynb not supporting the matlab engine..  
Let me know if you have any more details and clarify what is working and what isnt..

Cheers,
sal

--
Salman Husain, MSc, PhD.
National Renewable Energy Laboratory.

**Comment by Khalid-1994-06-17** [comment]
But before when I ran this code last year it would work but now I don't know why recently it would not work. I tried a simple example called matlabenginetest.ipynb with the MATLAB file MATLABtest.m and it would work without any issues

**Comment by salhus** [comment]
@Khalid-1994-06-17 
That is interesting.. could you share a folder with files for me to probe. This is strictly speaking not a WEC-Sim issue but I can take a quick look.

**Comment by Khalid-1994-06-17** [comment]
Hey the issue was that I needed to update the MATLAB engine on terminal then reset the kernels and it worked

**Comment by salhus** [comment]
Great! glad you figured it out.
