### ISSUE TITLE
http://ost.io/@WEC-Sim/WEC-Sim/topics/7

### ISSUE THREAD

**Issue by cmichelen** [WEC-Sim/WEC-Sim#12]

**Comment by kmruehl** [comment]
@cmichelen 

To specify wave direction first your BEM solution must include several wave directions, encompassing the range of desired directions.

Then, in your `wecSimInputFile.m` file you need to specify the 'waves.waveDir' property. For example if you want the wave to come from 45 degrees you would specify:
```matlab
waves.waveDir = 45;
```
WEC-Sim will interpolate between the different wave directions from your BEM. Note, direction is specified in degrees.
