### ISSUE TITLE
[WEC-Sim Applications] Question about MPC in Controls section

### ISSUE THREAD

**Issue by DeminLiLi** [WEC-Sim/WEC-Sim#1206]
**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
problem path: WEC-Sim_Applications-master\Controls\MPC

**Describe the issue**
Hi Sir,

When I used MPC for control calculations, I found that there was a coeff.mat file in the folder. The use of data in this file is in the makePlantModel.m file, but I do not understand how the data in the coeff.mat file is calculated, so I would like to ask about the meaning and calculation method of the data in the coeff.mat file. Thanks.

Demin

**Comment by kmruehl** [comment]
Hi @DeminLiLi Thank you for your question and for using the issue template. This is helpful for the WEC-Sim team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

**Comment by jtgrasb** [comment]
Hi @DeminLiLi, 
Thank you for your question. The coeff.mat includes the coefficients for frequency dependence, which are calculated by the plotFreqDep.m file. To read more about the MPC controller, please refer to the corresponding [documentation](https://wec-sim.github.io/WEC-Sim/dev/user/advanced_features.html#model-predictive-control-mpc) section and accompanying sources. 

If you have further questions, please provide more information regarding your current approach and issues.

**Comment by DeminLiLi** [comment]
Hi @kmruehl  and @jtgrasb，

Many thanks for your help. Due to my negligence, I did not view the plotFreqDep.m file. I have re-run the working condition test based on your information. Currently, everything is fine under the test cases. Once again I would like to express my sincerest gratitude.

Demin

**Comment by jtgrasb** [comment]
Great, glad we could help!
