### ISSUE TITLE
[WEC-Sim Applications] Variant Issues when trying to create a new project

### ISSUE THREAD

**Issue by pjpatio** [WEC-Sim/WEC-Sim#1208]
**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
I used WEC-Sim and PTO-Sim for this project

**Describe the bug or issue**
Im new to this program and have been trying to learn. I keep getting issues regarding Variant control with multiples factors such as in the global reference frame and the rigid body system. I cant seem to find the variables they are referring to and cant proceed further

This was based on the RM3 code provided in the website. I wanted to create the same PTO system described for PTO-Sim but using a rigid body instead.

**To Reproduce**
To reproduce i simply changed out the flex body with a rigid body but havent been able to make the hydraulic motor work as well as the global reference frame having issues with WaveVis. The code used is the RM3 PTO codec. Afterwards when i revert all changes the same issues persist

**Expected behavior**
I just wanted to output the power generation of the PTO alongside the otehr outputs but using a rigid body instead

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - MATLAB/Simulink Release 2023b
 - WEC-Sim Release Latest

The ZIP file and error messages are provided below

[PTO.zip](https://github.com/WEC-Sim/WEC-Sim/files/14023922/PTO.zip)

Variant control 'sv_b_AnalyticalEfficiency' of variant block '[PTO/PTO-SIM/Hydraulic Motor](matlab:open_and_hilite_hyperlink ('PTO/PTO-SIM/Hydraulic Motor','error'))' must be a condition expression or name of a Simulink.VariantExpression object in the global scope workspace of the model. Ensure that the condition does not match the model name.

Component:Simulink | Category:Model error
Variant control 'sv_b_TabulatedEfficiency' of variant block '[PTO/PTO-SIM/Hydraulic Motor](matlab:open_and_hilite_hyperlink ('PTO/PTO-SIM/Hydraulic Motor','error'))' must be a condition expression or name of a Simulink.VariantExpression object in the global scope workspace of the model. Ensure that the condition does not match the model name.

Variant control 'sv_b_hydroBody' of variant block '[PTO/Rigid Body](matlab:open_and_hilite_hyperlink ('PTO/Rigid Body','error'))' must be a condition expression or name of a Simulink.VariantExpression object in the global scope workspace of the model. Ensure that the condition does not match the model name.

Component:Simulink | Category:Model error
Variant control 'sv_b_nonHydroBody' of variant block '[PTO/Rigid Body](matlab:open_and_hilite_hyperlink ('PTO/Rigid Body','error'))' must be a condition expression or name of a Simulink.VariantExpression object in the global scope workspace of the model. Ensure that the condition does not match the model name.

**Comment by kmruehl** [comment]
Hi @pjpatio Thank you for your question. We ask users to open GitHub issues using an appropriate template. This is helpful for the WEC-Sim team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "WEC-Sim applications specific issue or question" template and include more details on your setup and error message, I am happy to help. Please maintain the template structure and the issue type in the title.

Thanks again.

**Comment by pjpatio** [comment]
Could i follow up this issue?

**Comment by jleonqu** [comment]
Hello @pjpatio 
The PTO-Sim example available [here](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim/RM3/RM3_cHydraulic_PTO) uses the rigid body blocks. If you want to use the rigid body blocks, it should work just as in the example.
If you want to use the nonHydro option, you need to edit your wecSimInput.m to create the body object, for this you need to start the definition of the body variables with this line: body(#) = bodyClass(''); In addition o this you need to define different parameters for your nonHydro body such as the center of gravity and the displaced volume. There is an example on how to use the nonHydro body option in the applications repo, [here](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/Nonhydro_Body)
I hope this can help you to continue with your work.

**Comment by jleonqu** [comment]
I am closing this issue, but feel free to open a new one in case you have more questions.
