### ISSUE TITLE
[WEC-Sim Applications] Rotating Mass

### ISSUE THREAD

**Issue by NateHixon73** [WEC-Sim/WEC-Sim#1209]
Can you simulate a rotating mass power take off in WECSIM?

**Comment by dav-og** [comment]
Hello @NateHixon73, do you mean this type of thing?

![Gyroscope1](https://github.com/WEC-Sim/WEC-Sim/assets/12831266/d735ab23-3ed3-4ec3-87c4-37f76dba40ba)

Yes, this is possible - you can define the hull as a hydrodynamic body, the internal mass as a 'nonhydro' body and connect them via a revolute PTO.

If you have any further issues, **please fill in one of our issue templates.**

Cheers,
Dave

**Comment by NateHixon73** [comment]
Thank you!
