### ISSUE TITLE
Multiple Run simulation

### ISSUE THREAD

**Issue by SudharsanKalidoss** [WEC-Sim/WEC-Sim#121]
How to write output in multiple run simulation? And How should input is to be given to wecsim through spreadsheet for multiple run simulation?

**Comment by Sire79** [comment]
Hi Sudharsan,
If I understand you properly, output are given by the multiple run model that is run by running "wecSimMCR" input file. There is a command to call a spreadsheet to wecsim but it does not working properly for me.

Regards

**Comment by yuyihsiang** [comment]
Hi SudharsanKalidoss

To write output in multiple run simulation, our suggest is to write matlab script in userDefinedFunctions.m file. Normally, we would use that to copy the output file in the output folder to another place and rename it. 

Thanks,

--Yi-Hsiang

**Comment by SudharsanKalidoss** [comment]
Hi Yi-Hsiang,

    Can I write a script to copy and paste folder in userDefinedFunction.m? Or else is there any particular format to do the same?

Thanks,

Sudharsan

**Comment by yuyihsiang** [comment]
I believe you can. Any MATLAB function will work in the userDefinedFunction.m file.

See MathWorks for more details: http://www.mathworks.com/help/matlab/ref/copyfile.html?requestedDomain=www.mathworks.com

--Yi-Hsiang

**Comment by kmruehl** [comment]
@SudharsanKalidoss @Sire79 have your MCR questions been resolved?
