### ISSUE TITLE
[Developer Issue] ParaView Videos on YouTube were made private

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#1210]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Project**
WEC-Sim Documentation

**Describe the issue**
Within the [Advanced Features - ParaView Visualization](https://wec-sim.github.io/WEC-Sim/dev/user/advanced_features.html#paraview-visualization) section of the documentation, there are links to 2 YouTube videos, one for each of the 2 ParaView examples. The links are not working because the videos are private now. To solve this issue, either the owner (if known) of the YouTube account could make them public again or we could just reference the visualization training course (probably simpler option).

**Comment by kmruehl** [comment]
@jtgrasb this issues should be resolved now. I'm going to close this issue.
