### ISSUE TITLE
[Theory or Implementation] [Documentation] Error in documentation related to Paraview

### ISSUE THREAD

**Issue by CesarSurf** [WEC-Sim/WEC-Sim#1225]
[Paraview use documentation in the Advanced Features portion of the wiki ](https://wec-sim.github.io/WEC-Sim/dev/user/advanced_features.html#paraview-visualization) is misleading. It states _"When simu.paraview=1 a vtk..."_  In  the current version, simu.paraview has been updated to be a struct with a field "option" which now serves as a flag. Documentation at the moment does not explain how to use the feature.

**Comment by jtgrasb** [comment]
Thank you for letting us know about this issue. The documentation will be updated accordingly. 

If you have further questions, please use an issue template and include more detail about your setup and model? Thank you.
