### ISSUE TITLE
[WEC-Sim Applications] Discussion on the optimal PTO parameters

### ISSUE THREAD

**Issue by hachikoi1** [WEC-Sim/WEC-Sim#1230]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
_Please identify the WEC-Sim applications case in question._

**Describe the bug or issue**
_A clear and concise description of what the perceived bug or issue is._
Hello, guys. I opened this thread for help on PTO optimization.
The problem originated when I added two other common PTO types (constant, quadratic damping) to the translational PTOs. Thus three PTO types can be implemented via the translational PTO.
For a linear damping PTO: `pto.stiffness ~= 0; pto.damping ~= 0; pto.constant = 0; pto.quadDamping = 0;`
For a quadratic damping PTO: `pto.stiffness = 0; pto.damping = 0; pto.constant = 0; pto.quadDamping ~= 0;`
For a constant PTO: `pto.stiffness = 0; pto.damping = 0; pto.constant ~= 0; pto.quadDamping = 0;`
`pto.oscillation = 100*(body.mass+body.addedMass);` is used to avoid numerical oscillations of the velocity around 0 for the constant PTO, see _'Numerical benchmarking study of a selection of wave energy converters'_.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/9a416277-cdce-454f-a67f-96483883a810)

**The problem currently encountered is that, when a very large _constant or quadratic damping_ PTO parameter is applied (this parameter may generate a PTO force that is much larger than the total hydrodynamic force of the floating body), the simulation runs normally, but the optimal energy gain is always not achieved.**

For example, for the RM3 device, **the total hydrodynamic forces of the float and spar have a magnitude of 1e5~1e6, `pto.oscillation = 100*(725833+1.232838000000000e03*1000);` has a magnitude of 1e8.** The capture width ratio is defined as time-averaged PTO power/(time-averaged wave power*float diameter).
```
powerInstant     = -WECSimOutputs.ptos(1).powerInternalMechanics(:,3);
powerTimeAverage =  trapz(powerInstant)/(length(powerInstant)-1);
powerCWR         =  powerTimeAverage/(20*waves.power) % waves.power is calculated in waveClass.m
```

Total hydrodynamic force of the float in the heave direction, total hydrodynamic force of the spar in the heave direction, PTO force, relative displacement, relative velocity and relative acceleration are:
`pto.stiffness = 0; pto.damping = 0; pto.constant = 0; pto.quadDamping = 0; `
![result](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/a6e04bb7-6bb5-48d1-9f9f-2573669f7558)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e5; pto.quadDamping = 0;` CWR = 0.0560
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/288cf31b-6e4e-42f2-b16b-828658a970c0)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e6; pto.quadDamping = 0;` CWR = 0.5603
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/c90f86d1-43c0-4163-bd35-83c2731eca73)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e8; pto.quadDamping = 0;` CWR = 52.3493
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/ceea2e89-f11d-4648-be63-7078a93bc612)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e10; pto.quadDamping = 0;` CWR = 73.0147
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/8b22ed92-89e9-407a-a590-328e23fe814f)

Similarly, 
`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e5; pto.quadDamping = 0;` CWR = 0.0270
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/8755bf0d-fa62-4995-ba87-9a4d4bb4b2e2)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e6; pto.quadDamping = 0;` CWR = 0.2698
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/327dac45-20dc-4231-8d2d-d2503d21c30d)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e8; pto.quadDamping = 0;` CWR = 26.9828
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/44c6215e-fe20-4193-97a6-d54d446e4e0f)

`pto.stiffness = 0; pto.damping = 0; pto.constant = 1e10; pto.quadDamping = 0;` CWR = 2.6983e+03
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/44c6215e-fe20-4193-97a6-d54d446e4e0f)

**For the constant and quadratic damping PTOs, it seems that an increasing PTO coefficient cannot further restrain the relative motion of the floating bodies. It's non-physical. Could anyone give me some advice on how to model reasonable constant and quadratic damping PTOs?** 

**To Reproduce**
_Steps to reproduce the behavior:_

1. _Go to '...'_
1. _Click on '....'_
1. _Scroll down to '....'_
1. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem. For example, a screen shot of the exact error message from the MATLAB command line._

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 11
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2023b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v6.0]

**Additional context**
_Add any other context about the problem here._

**Comment by dforbush2** [comment]
Hi @hachikoi1 

I'm a little unclear what model you are talking about. Can you please provide a *zip of your simulink run directory or a more specific description of the model you are trying to run? Or if you could please populate these fields of the template.

To Reproduce
Steps to reproduce the behavior:

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error

**Comment by hachikoi1** [comment]
Dear @dforbush2 
Sorry for my unclear description. I'm trying to add more features to the translational PTO. In addition to the original stiffness and linear damping terms, the translational PTO now contains constant and quadratic damping terms. The modifications in the **\WEC-Sim\source\lib\WEC-Sim\WECSim_Lib_PTOs.slx** are as follow:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/d0a5113d-d011-4da6-9831-7a5e6036e3c4)

For a linear damping PTO used to simulate a permanent magnet linear generator: `pto.stiffness ~= 0; pto.damping ~= 0; pto.constant = 0; pto.quadDamping = 0;`
For a quadratic damping PTO used to simulate a turbine converter: `pto.stiffness = 0; pto.damping = 0; pto.constant = 0; pto.quadDamping ~= 0;`
For a constant PTO used to simulate a hydraulic generator: `pto.stiffness = 0; pto.damping = 0; pto.constant ~= 0; pto.quadDamping = 0;`

`pto.oscillation = 100*(body.mass+body.addedMass);` is used to avoid numerical oscillations of the velocity around 0 for the constant PTO, see 'Numerical benchmarking study of a selection of wave energy converters'.

The modified lib file is attached [here](https://github.com/WEC-Sim/WEC-Sim/files/14416276/objects.zip).

What I am confused is, for constant and quadratic damping PTOs, the instantaneous or total power always increases monotonically with increasing PTO parameters. That is,  the parameter for maximum output power can not be found.

Do you have any insight on this?

Best regards,

Tianyuan

**Comment by dforbush2** [comment]
Ah @hachikoi1 I've got to the bottom of this. If you'll note, adding PTO forces of any magnitude are not affecting your velocity, so it seems like they are not actually being delivered through the PTO as intended. 
Let's look at this screenshot of your library block one level up.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/30122876/7eae0242-cbe8-4db3-8f38-1f3151aaa8ef)


Note that all of your modifications are in the "InternalMechanics" block in grey here actually only output to the "Response" and the "To Workspace" logging blocks (red paths): nothing from this internal mechanics block is applied between the Body-Follower frame (green path). The only parameters that affect that here are the linear damping and stiffness that are parameters _inside_ the Translational PCC blocks (pto.stiffness, pto.damping). Thats why these linear stiffness/damping will affect dynamics, but the additional terms you added do not. Your logged forces always changed as you varied their parameters but the velocity remained the same: these forces were not actually applied to the bodies. 

The best way to do this probably is not to modify the Translational PTO block but instead add a custom function and use it to define the actuation force input to "Translational PTO Actuation Force". Doing this directly to the Translational PTO block, as you attempted, would require modifying the Translational PCC (Prismatic Joint) block from the multi-body library, which is not impossible but best avoided unless there is a need.

**Comment by hachikoi1** [comment]
Dear @dforbush2 

Many thanks for your clarification.

The modification is feasible.

Best regards,

Tianyuan
