### ISSUE TITLE
[WEC-Sim Applications] MOST / Offshore wind simulation inputs

### ISSUE THREAD

**Issue by irfankhandgk** [WEC-Sim/WEC-Sim#1231]
I am currently working on integrating a wind turbine model with a Wave Energy Converter (WEC) using the WEC-Sim simulation tool. My goal is to evaluate the combined performance and dynamics of these two renewable energy systems in various sea states. However, I have encountered an issue that I have not been able to resolve through the existing documentation or community forums.
could anyone have suggesteion ?

**Comment by irfankhandgk** [comment]
> Assigned @akeeste but I recommend you look at the MOST applications case which does exactly this. You may need to open an issue with a more complete template so we have the necessary specific information to help you.

Hello, Thankyou for your response, I found 15MW wind turbine case from MOST, are you aware of the 5-MW case so I can use already exisiting files instead of creating them from scratch?

**Comment by akeeste** [comment]
Hi @irfankhandgk

We do not have any other example input files. I recommend reviewing the special pre-processing steps in the [MOST WEC-Sim Application](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/MOST/mostData). If you have any further questions on MOST, I recommend reaching out to @MOREnergylab.

**Comment by akeeste** [comment]
Hi @irfankhandgk 

Do you have any further questions on the pre-processing steps within the MOST application? If not, I'll go ahead and close this issue next week.
