### ISSUE TITLE
Hydrodynamic analysis of two floaters

### ISSUE THREAD

**Issue by lianggege** [WEC-Sim/WEC-Sim#124]
Hi, everyone,
I am doing time domain simulation of the hydrodynamic interaction between a FPSO and a shuttle ship. Unlike wave energy system, such as RM3, the two floaters (FPSO and shuttle ship) in my study have only 
hydrodynamic interaction and no mechanical couplings exist. 
Could I ask whether my following modeling is correct and would anyone kindly offer a help if there is something wrong?
![capture](https://cloud.githubusercontent.com/assets/16103563/17696817/d212bcec-63a8-11e6-97f4-5d2385f4949a.JPG)

Thanks a lot
Liang

**Comment by yuyihsiang** [comment]
Hi Lianggege 

Theoretically, it is correct. You can also try another option by connecting the Base of the Floating (6DOF)1 directly to Coon of the Global Reference Frame. 

However, it will be great if you can provide a little more information on what you are trying to investigate, such as the interaction between FPSO and shuttle ship or something else. There could be a simpler approach, depending on what you are trying to do here.

Thanks,

--Yi-Hsiang

**Comment by lianggege** [comment]
Hi, Yi-Hsiang,
Thanks for your reply! 
I just want to calculate the motions of each floater when they are placed side by side.

**Comment by yuyihsiang** [comment]
Hi lianggege

I see. It would be easier for me to give further suggestion if you are welling to sharing the model. I am more than happy to take a look if you can send me your model and input files.

Thanks,

--Yi-Hsiang

**Comment by kmruehl** [comment]
@lianggege @yuyihsiang  has this issue be resolved?
