### ISSUE TITLE
Issue with Creating ".gdf" Files for WEC-Sim

### ISSUE THREAD

**Issue by samir-miloud** [WEC-Sim/WEC-Sim#1243]
Hello everyone,
I am currently working on a research project using WEC-Sim for wave energy conversion system simulation. However, I am facing difficulties with creating ".gdf" (GEOMETRIC DATA FILE) files on Ubuntu.
I am using Gmsh for geometry and mesh creation, but I haven't found a way to generate ".gdf" files compatible with WEC-Sim. Despite my efforts in searching, I haven't been able to find a suitable solution.
Does anyone have any advice on how to create or convert ".gdf" files using Gmsh or other tools on Ubuntu? Or perhaps you could recommend another CAD software that might better meet my needs?
Any help or suggestion would be greatly appreciated. Thank you in advance for your assistance!

Best regards,

**Comment by samir-miloud** [comment]
Hello everyone,
I am currently working on a research project using WEC-Sim for wave energy conversion system simulation. However, I am facing difficulties with creating ".gdf" (GEOMETRIC DATA FILE) files on Ubuntu.
I am using Gmsh for geometry and mesh creation, but I haven't found a way to generate ".gdf" files compatible with WEC-Sim. Despite my efforts in searching, I haven't been able to find a suitable solution.

Does anyone have any advice on how to create or convert ".gdf" files using Gmsh or other tools on Ubuntu? Or perhaps you could recommend another CAD software that might better meet my needs?
Any help or suggestion would be greatly appreciated. Thank you in advance for your assistance!

Best regards,

**Comment by dforbush2** [comment]
Hi @samir-miloud 

I think we may have resolved this via email, I will summarize here for the community:
1) WEC-Sim does not require GDF files: it requires an H5 file containing the hydrodynamic coefficients. It is WAMIT that requires a GDF mesh. This GDF mesh is used by WAMIT to solve the boundary element method equations for this geometry and produce the *out file that, among others, is then used to create the H5 file via tools included in WEC-Sim/source/functions/BEMIO. 
2) GDF files can be created easily in Rhino, and there are a handful of free tools that can also do so. In particular, MeshMagick https://lheea.github.io/meshmagick/command_line/cli_usage.html#converting-a-mesh-file can create a GDF file from a variety of other mesh formats. ***Note: it is specifically not recommended to convert solidworks stl files to gdf (or any other mesh format) intended for BEM. This can cause a variety of issues ***
3) If you are not planning to use WAMIT specifically, you can generate another mesh format. In particular, it is recommended that users without WAMIT access consider using Capytaine (https://capytaine.github.io/stable/) as their BEM solver, which accepts a variety of mesh formats (as well as GDF).
