### ISSUE TITLE
About running the model

### ISSUE THREAD

**Issue by rz311** [WEC-Sim/WEC-Sim#125]
I got the error: The variant block 'RM3/Float/Hydrodynamic Body/B2B Subsystem/B2B' does not have same number of input ports
as Variant Subsystem block 'RM3/Float/Hydrodynamic Body/B2B Subsystem'.
Is it caused by a lower version of Matlab?
Could anyone help?

**Comment by yuyihsiang** [comment]
Which version of MTALAB are you using? Currently, the WEC-Sim model only supports MATLAB 2015b or later version.

**Comment by rz311** [comment]
Hi,
It's 2013b. Do you think this problem is caused by the version problem?

Thanks

Steven

On Aug 26, 2016, at 21:06, yuyihsiang <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of MTALAB are you using? Currently, the WEC-Sim model only supports MATLAB 2015b or later version.

-

**Comment by yuyihsiang** [comment]
ya, 2013b won't work. Many of our blocks developed in WEC-Sim lib use functions of SimMechanics (now SimScape Multibody in 2016a) that only exist in later version of MATLAB.

**Comment by rz311** [comment]
Thanks.

That helps.

Steven

On Aug 26, 2016, at 21:11, yuyihsiang <notifications@github.com<mailto:notifications@github.com>> wrote:


ya, 2013b won't work. Many of our blocks developed in WEC-Sim lib use functions of SimMechanics (now SimScape Multibody in 2016a) that only exist in later version of MATLAB.

-

**Comment by rz311** [comment]
Hi,
Again I got errors with a 2015B version: 
Caused by:
    Error using wecSim (line 232)
    Error in port widths or dimensions. Invalid dimension has been specified for input port 1 of 'RM3/Float/Hydrodynamic
    Body/Hydrostatic Restoring Force Calculation/Add'.
    Error using wecSim (line 232)
    Error in port widths or dimensions. Output port 1 of 'RM3/Float/Hydrodynamic Body/Hydrostatic Restoring Force
    Calculation/Displacement' is a one dimensional vector with 4 elements.

Thanks

Steven

**Comment by kmruehl** [comment]
@rz311 are you running the RM3 tutorial (https://github.com/WEC-Sim/WEC-Sim/tree/master/tutorials/RM3), and have you added the wec-sim source code and all of the sub-directories to your path? If so, you should not have this error. 
-Kelley

**Comment by rz311** [comment]
Hi,
I think so. Is this error coming from the mismatch of the dimension for different signals?

Steven


On Aug 31, 2016, at 16:29, Kelley Ruehl <notifications@github.com<mailto:notifications@github.com>> wrote:


@rz311<https://github.com/rz311> are you running the RM3 tutorial (https://github.com/WEC-Sim/WEC-Sim/tree/master/tutorials/RM3), and have you added the wec-sim source code and all of the sub-directories to your path? If so, you should not have this error.
-Kelley

-

**Comment by kmruehl** [comment]
The error is indeed a dimension mismatch error, but without seeing your model I cannot troubleshoot to identify the issue. Would you like to upload the model for the WEC-Sim team to review?

**Comment by rz311** [comment]
Hi,
It’s just the tutorial I downloaded from the website directly…

Thanks

Stven

**Comment by kmruehl** [comment]
@rz311 did this resolve your issue?
