### ISSUE TITLE
[WEC-Sim Applications]MOST /IEA15MW FOWT Free Decay

### ISSUE THREAD

**Issue by wind2021** [WEC-Sim/WEC-Sim#1260]
[WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/main/MOST) 

**Describe the bug or issue**
I think the WEC-Sim+MOST model may have some problem, as the free decay test for IEA15MW FOWT shows some strange results. I used the model download from the link above and set the initial state of the six degrees of freedom to 0, with no wind and no waves, and carried out the free decay test. The results were surprising, because the surge, heave and pitch did not stabilize near 0, and the other three degrees of freedom were not balanced. Here are the 6 DOFs results.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/c9f2078d-daf3-4d12-a603-0ac38d696a1e)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/ebab1f02-088d-47a2-8d9d-c25a32e80da5)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/4a525bf9-7440-4103-b714-04ce6daf5a4b)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/7a8b3b6d-572f-4a1d-92b6-12c741d0efae)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/929a934b-ad8e-4985-a6aa-e5173a617d8c)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/373eabc0-0cd0-4060-acd9-27af72efb9be)

**To Reproduce**
1. Go to WEC-Sim_Applications/MOST
/mostData/mostIO.m to run it and generate file for MOST;
2. Go to WEC-Sim_Applications/MOST/mostData/hydroData/bemio.m to run it and generate file for MOST;
3. Go to WEC-Sim_Applications/MOST/OFWTmodel.slx to separate the Aerodynamics + Control block;
4. Go to WEC-Sim_Applications/MOST/wecSimInputFile.m to set no wave and no wind, omega0 = 0. And set the body(1).initial.displacement = [0 0 0];
5. Run WEC-Sim.

**Screenshots**
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/5e5d0e14-321e-4fa2-b1a7-c23a55b33dc2)
[wecSimInputFile.txt](https://github.com/WEC-Sim/WEC-Sim/files/15495521/wecSimInputFile.txt)

**Expected behavior**
We should expect a response of six degrees of freedom around zero, fluctuating up and down at very small values, 0.001 or something else.

**Workstation Information (this section MUST BE completed):**
 - [MATLAB/Simulink Release][2022b]
 - [WEC-Sim Release] [v6.0]

**Additional context**
After we change the parameters, according to the report(https://www.nrel.gov/docs/fy20osti/76773.pdf)), in WEC-Sim_Applications-6.0\MOST\hydroData\VolturnUS15MW_nemoh\Mesh\Hydrostatics.dat and WEC-Sim_Applications-6.0\MOST\mostData\windTurbine\turbine_properties\WTproperties.m, the response of six degrees of freedom do come around zero. But the structure becomes very strange. Results are here:
[Hydrostatics.txt](https://github.com/WEC-Sim/WEC-Sim/files/15495666/Hydrostatics.txt)
[WTproperties.txt](https://github.com/WEC-Sim/WEC-Sim/files/15495670/WTproperties.txt)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/e699c4ca-cb17-4cd9-b578-ce4a24e4b562)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/cf08b7c7-c31b-4ac6-a573-94bdebb11ef6)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/e6ddb7d8-7756-4493-8fdf-131e30141bd2)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/613e0f74-167b-4901-86e2-4c9782a3ff73)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/37f88ee1-3dd2-4a89-b631-ca08a77b3d21)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/50c70ebe-90b6-43b8-8cea-534ff58c8b05)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/76504585/a875ba1a-296c-45fb-81d5-949902f91417)

Dear friends, can you provide some information? Is this a problem with the model or is there something wrong with my operation?

**Comment by akeeste** [comment]
Hi @wind2021. I see that you closed your issue yesterday. Are you still having problems with this topic or did you find a solution?

**Comment by kangjianfei** [comment]
I’m seeing significant sway, heave, and pitch responses in the IEA-15-240-RWT-UMaineSemi model even in still water, no wind conditions, starting from an initial state of 0,0,0,0,0,0 (m, rad).

Could this be inherent to the reference case (e.g., due to imbalance between PtfmVol0 and total mass, RNA CG offset, or mooring pretension not matching the zero pose), or is it likely due to my setup?

I’d like to request reopening this question so I can share more details and investigate further.
