### ISSUE TITLE
[BUG] - broken url in documentation

### ISSUE THREAD

**Issue by rebeccamccabe** [WEC-Sim/WEC-Sim#1261]
**Describe the bug**
The [getting started page](https://wec-sim.github.io/WEC-Sim/main/user/getting_started.html#step-3-add-wec-sim-library-to-simulink) of the documentation "refresh the simulink library" has a [broken link](http://www.mathworks.com/help/simulink/gui/use-the-library-browser.html) to a MathWorks page. I think the url should be changed to [here](https://www.mathworks.com/help/simulink/slref/librarybrowser.librarybrowser2.refresh.html).

**WEC-Sim file(s)**
N/A

**To Reproduce**
N/A

**Expected behavior**
Link works

**Screenshots**
![image](https://github.com/WEC-Sim/WEC-Sim/assets/32020426/68247b52-65e1-4251-b3c3-c42f6feb0f6f)

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) N/A
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) v6.0

**Additional context**
N/A

**Comment by kmruehl** [comment]
@rebeccamccabe thanks for bringing this to our attention. The broken link should now be resolved.
