### ISSUE TITLE
Regarding about using PTO sim application

### ISSUE THREAD

**Issue by chakramtalla** [WEC-Sim/WEC-Sim#1285]
Please can anyone help with this issue
![image](https://github.com/user-attachments/assets/f2c5c1f3-bad9-429d-a945-6dc1497b0d56)

**Comment by dforbush2** [comment]
To better triage and respond to issues we request that users populate the templates that appear when opening a new issue. Please open a new issue utilizing an existing template.

**Comment by dforbush2** [comment]
![image](https://github.com/user-attachments/assets/ba078827-9313-4830-8ebf-da767b695d85)
