### ISSUE TITLE
constraint conditions

### ISSUE THREAD

**Issue by chakramtalla** [WEC-Sim/WEC-Sim#1286]
How we are giving constraint parameters in WECSIM library link
because all constraint parameters are showing same parameters

**Comment by dforbush2** [comment]
Hi @chakramtalla 

To better triage and respond to issues we request that users populate the templates that appear when opening a new issue. Please open a new issue utilizing an existing template.

**Comment by dforbush2** [comment]
![image](https://github.com/user-attachments/assets/68ee9120-633d-4d12-91d1-80ed0a0b4293)
