### ISSUE TITLE
OWC (7 DOF) Application in WEC-Sim BEMIO/CAPYTAINE

### ISSUE THREAD

**Issue by samir-miloud** [WEC-Sim/WEC-Sim#1292]
Hi,

I’m currently working on modeling the Sparbuoy OWC case using Capytaine, employing the Generalized Body Modes (GBM) method. I need to incorporate 7 degrees of freedom (DoFs) into the simulation. However, Capytaine only provides the 6 standard DoFs (surge, sway, heave, roll, pitch, yaw), and I am missing an additional DoF for the water column height.
Does anyone have experience with adding a 7th DoF in Capytaine, or any suggestions on how to handle this with the GBM method?

Thanks!

**Comment by dforbush2** [comment]
see #1293
