### ISSUE TITLE
An Error using wecSim

### ISSUE THREAD

**Issue by HareendraAmaratunge** [WEC-Sim/WEC-Sim#1302]
I tried wecSim to get some mooring results by modeling a new hemisphere design. I used WAMIT sphere for bemio. And I drove SLX file. and made up a wecsim input file by slightly differentiating the RM3MoorDyn input file. But in the end I came up with an error called "Index must not exceed 1. I ll atach the error. please help. 

![Screenshot 2024-09-02 112051](https://github.com/user-attachments/assets/b259ca63-b2e6-4eb1-bcc7-87a1f6ffdb18)

Regards.

**Comment by kmruehl** [comment]
@HareendraAmaratunge can you please amend this issue to use the issue template? Thank you.

**Comment by HareendraAmaratunge** [comment]
I Will.

**Comment by HareendraAmaratunge** [comment]
Ok. I will

regards.

**Comment by HareendraAmaratunge** [comment]
Any updates

**Comment by HareendraAmaratunge** [comment]
rgarding I amended this issue to use the issue template as you said.
