### ISSUE TITLE
[Theory or Implementation] OSWEC  desalination Hydraulic Power 

### ISSUE THREAD

**Issue by chakramtalla** [WEC-Sim/WEC-Sim#1338]
Avg Input power 26 kw
hydraulic powr is 390 kw
if input is low, and out put power is high??? is there any bug checked for all cases

![image](https://github.com/user-attachments/assets/e7bc5376-21ff-4ac4-8d04-003bd757bc51)
When I ran the simulation, the hydraulic power going to the RO module was higher than the input power at the hydraulic cylinder. Despite the flow rate being high, this discrepancy occurred in all cases I tested. Can you help clarify why this is happening?"
Simillarly, for flow rate too,
![image](https://github.com/user-attachments/assets/1503b82d-2683-4d3d-b2ff-2e6f9625f1cc)
In this fig you can see blue is inflow to cylinder and remaining is  flow to RO membrane, please clarify

**Comment by MShabara** [comment]
@chakramtalla  can you please amend this issue to use the issue template? Thank you
