### ISSUE TITLE
[BUG] Free Decay with OSWEC

### ISSUE THREAD

**Issue by riasatmorshed** [WEC-Sim/WEC-Sim#1345]
**Describe the bug (REQUIRED)**
First of all, I am kinda confused if this is a bug or something I am missing out.

**Workstation information (REQUIRED):**
_Describe the workstation:_
 - Operating System: Windows 11
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html): R2023a
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html): v5.0
**WEC-Sim file(s):** 
[OSWEC_FreeDecay.zip](https://github.com/user-attachments/files/17480574/OSWEC_FreeDecay.zip)

**How to reproduce:**
` body(1).initial.angle = deg2rad(15)` as my initial angle in the wecSimInputFile. All the .stl, .h5 files (generated from oswec.out using bemio function), and even the rest of the items are kept as it is in the OSWEC tutorial case. I used all the inertia, hydrostatic restoring coefficients (C_55) and added mass at infinity- all from the .out file. And I am using logarithmic decrement to calculate my damping ratio from the "free decay" curve and then tried to replicate the same response using analytic equation. Following is the code I am using after running WECSim.

`%from free decay curve (after running WECSim with 'noCicWave' condition)
w_t1 = 23.4676; %Angular Displacement at time = t1
t1 = 9.5;
w_t2 = 21.4412; %Angular Displacement at time = t2
t2 = 67;
N = 3;
delta = log(w_t1/w_t2);
fd = N/(t2-t1); %Damped Natural Frequency
zeta = delta/(sqrt(delta^2+(N*2*pi)^2)); %Damping Ratio
fn = fd/(sqrt(1-zeta^2)); % Natural Frequency

%% Real OSWEC 
K_55 = 2e6; %Restoring Coefficient (C_55)
I5 = 1.856e6; %(Inertia at I_55)
AddedMassInf = 6e6; %From the .out file
wn_oswec = sqrt(K_55/(I5+AddedMassInf)); %Real natural frequency of the OSWEC in rad/s
fn_oswec = wn_oswec / 2/pi; %Real natural frequency of the OSWEC in Hz
%% Free decay response 

decay_wecsim = rad2deg(output.bodies(1).position(:,5)); %Output from WECSim
time = output.ptos.time(:,1);

nu = 2*zeta*(2*pi*fn); %\nu = 2*\zeta*\omega_n
phase = atan(nu/(2*pi*fd)); 

init_angle = deg2rad(15); %in radian
exponent = -zeta*2*pi*fn_oswec .* time; %just a temporary variable
decay_analytic = rad2deg(init_angle .* exp(exponent) .* cos(2*pi*fd .* time-phase));

plot(time, decay_analytic)
hold on
plot(time, decay_wecsim)`
 
**Expected behavior**
For the free decay test, after being displaced initially at an angle, the flap should be stabilized at 0 degree, which clearly is not the case. I am assuming the equilibrium position is that certain angle it is being stabilized on. However, I was trying to validate my result using an analytic solution upon calculating damping ratio from that free decay test that clearly does not match with the analytic one. Besides, upon being displaced initially for a certain degree, the flap does not instantaneously return to the opposite direction- I am not sure if this is normal thinking before the restoring moment takes over, the inertial moment makes it to go even further. 

**Screenshots:**
![image](https://github.com/user-attachments/assets/51b43a79-64cf-4b99-aae7-3ae7964277d2)

**Additional information:**
Firstly, in terms of stability, CG and CB of the OSWEC lies in the same line, right- even after a rotational displacement?

Secondly, I would like to add that "biased" free decay result was reported in #693 and I guess my issue is not exactly what the OP posted for but something similar I noticed when I tried to plot using `output.ptos.position(:,5)`. Is it intentional because the position is measured relatively and something along that reasoning? However, plotResponse function works fine now! Thanks!

**Comment by jtgrasb** [comment]
Hi @riasatmorshed. Could you share the code you used to apply the initial rotation? Note that the rotation should be applied about the hinge location rather than the cg. See `body.setInitDisp()` for a method which calculates a rotation matrix to apply the correct rotation and linear displacement needed for the [initial rotation](https://wec-sim.github.io/WEC-Sim/main/user/api.html#objects.bodyClass.setInitDisp).

**Comment by riasatmorshed** [comment]
Hello @jtgrasb !

I was using the following:
`% body(1).initial.displacement = [0 0 0];
% body(1).initial.axis = [0 1 0];
% body(1).initial.angle = deg2rad(20);`

However, as per your instruction, I tried `body.setInitDisp()` method with adjustment between CG and rotation-point. The graph turned out perfectly as like a normal free decay curve. Thank you for your help! I really appreciate it. I am planning to close this issue since the problem is resolved unless if you have any last remark or explanation. Thanks again!
