### ISSUE TITLE
STL File Creation 

### ISSUE THREAD

**Issue by MattSharman** [WEC-Sim/WEC-Sim#135]
Hi All, 

Just looking for some advice/best practice for STL and model creation. 

I'm in the process of creating my STL geometry for a more visual representation in Sim Mechanics. 
Am I right to dimension my WEC parts using the part's CoG as its origin. Then use the body(x).cg variable for positioning the parts and running in WEC-Sim.

Hope the above makes sense,  let me know if you require further info!
Matt

**Comment by gui-paredes** [comment]
Hi MattSharmam.
You should use the CoG as the origin, yes.
See my question/comment at https://github.com/WEC-Sim/WEC-Sim/issues/129.

**Comment by MattSharman** [comment]
Many thanks!
