### ISSUE TITLE
WEC-Sim v6.0 is not equivalent to v6.1.1 for OSWEC (due to wave spread bug fix)

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#1367]
**Note: Please complete all required fields. Italicized text describes each field.**

**Describe the bug (REQUIRED)**
When running OSWEC example using v6.1.1 in irregular waves, the results are different from v6.0. The regression tests did not seem to catch this because they only run on the RM3. I am using the same OSWEC case files for the comparison, so I have ruled out any changes to the OSWEC example itself; it must be something in the source code/libraries.

**Workstation information (REQUIRED):**
 - Operating System: Windows 11
 - MATLAB R2023b
 - WEC-Sim v6.0 vs. v6.1.1

**WEC-Sim file(s):**
It seems likely that it is something in either the bodyClass or body library, but I have not diagnosed the issue yet. 

**How to reproduce:**
Run the OSWEC example using v6.0 and compare to results from v6.1.1

**Expected behavior**
v6.0 should yield the same results as v6.1 for the OSWEC example to my knowledge. Note below that the difference occurs in irregular waves with the same phase seed, but not regular waves. 

**Screenshots:**
Irregular Waves:
v6.1.1:
![image](https://github.com/user-attachments/assets/80da76d9-4d58-437a-b0d6-11afa4bc44f5)
![image](https://github.com/user-attachments/assets/fbd0ccc0-9117-4112-9604-180d054e8d09)
![image](https://github.com/user-attachments/assets/215a3cb5-6af5-412b-a8de-22adc47821f9)

v6.0:
![image](https://github.com/user-attachments/assets/dce0adb7-5186-4db2-9fe6-3df488b486fe)
![image](https://github.com/user-attachments/assets/b14c7291-9de9-449b-9fca-50230ae58761)
![image](https://github.com/user-attachments/assets/4496b5f0-6391-4310-94b9-7fa5c6390eb0)

In regular waves: 
v6.1.1:
![image](https://github.com/user-attachments/assets/1761d9dd-217e-4bbf-9eb9-98a7ec6f846f)
v6.0
![image](https://github.com/user-attachments/assets/bc51ad3a-a077-43c3-8301-424fb6c73fe8)

**Additional information:**
@MShabara @akeeste Any idea where these differences would be coming from?

**Comment by akeeste** [comment]
@jtgrasb Nothing immediate stands out, though we made a lot of changes recently. Can you plot the pitch position of the two cases together and the pitch forces of the two cases together so that we can assess the differences more easily?

**Comment by dforbush2** [comment]
contrary to #1346 and #1350, in this case the excitation force IS different. Strongly recommend starting there with this: I suspect the other force differences may follow from this initial difference.

**Comment by dforbush2** [comment]
good find @jtgrasb 
to confirm, the change introduced to #1289 is the correct handling of waveSpread and the reference case should be updated.
