### ISSUE TITLE
Drag Coefficient

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/WEC-Sim#139]
hi 
i have more question about drag coefficient.
i have 6DOF drag coefficient ,i want to put them into wec-sim1.2
how to do it?
![image](https://cloud.githubusercontent.com/assets/23226663/19953969/6b60194c-a1ae-11e6-8386-a0a7f817b004.png)
is there have any  error and  how to do Debugging？
ths u

**Comment by kmruehl** [comment]
Viscous drag must be defined in the body class by a drag coefficient and characteristic area:

- body(1).viscDrag.cd
- body(1).viscDrag.characteristicArea

It cannot be defined as body(1).viscDrag = value, as you have done. For more information on the theory/application of viscous drag in WEC-Sim, please refer to the following:

- [Theory](http://wec-sim.github.io/WEC-Sim/theory.html?highlight=viscous%20drag#morison-elements)
- [Application](http://wec-sim.github.io/WEC-Sim/code_structure.html?highlight=drag#bodyclass)
