### ISSUE TITLE
How to simulate Off-Shore system

### ISSUE THREAD

**Issue by avindrola** [WEC-Sim/WEC-Sim#143]
I am a mechanical engineering student and for my senior mechanical design project I have to simulate Brazilian [ANEEL's project](http://www.bluebird-electric.net/oceanography/ocean_pictures/Wave_Power_Brasil_Coppe_Subsea_Usina-de-Ondas.jpg) (`National Agency of Electric Energy). I would like to know how can I define some part of the system outside the sea, in the shore. It is a 'mixed' system where the 'mooring' is located in the shore and the buoy on the sea.

Thanks for the help and sorry for the bad english, it is not my first lenguage.

**Comment by kmruehl** [comment]
You can model the onshore part of this WEC with a non-hydrodynamic body [click here for more info on non-hydro bodies](http://wec-sim.github.io/WEC-Sim/features.html#non-hydrodynamic-bodies). You can then fix the non-hydrodynamic body to the global reference frame, and add a hinged joint between the non-hydro body and the float.
