### ISSUE TITLE
What angle convention does WEC-Sim use for the position?

### ISSUE THREAD

**Issue by crobarcro** [WEC-Sim/WEC-Sim#167]
I have a question regarding the angles ecpected by WEC-Sim's hydrodynamic force calcualtions. 

What angle convention does WEC-Sim use for the position of bodies? Is it extrinsic Euler  123 (i.e. Tait-Bryon xyz)? There is an 'Angle' function block which converts SimMechanics quarternion representation to Euler, the comments in the code imply it is Euler 321, although I think from looking at what the code does and the output it's actually Euler 123?

Thanks!

**Comment by kmruehl** [comment]
The convention is that the angles are reported as RX, RY, RZ (roll, pitch, yaw).
