### ISSUE TITLE
mooring Stiffness

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/WEC-Sim#168]
hi
i  have  6 x 6 Stiffness matrix
how to set mooring line on floating  position?
![image](https://cloud.githubusercontent.com/assets/23226663/24402096/abe744ce-13e9-11e7-9b8e-32fca484551b.png)
example pic
that is set: 0 0 -13.15?
if the siffness matrix   set at two different positions   the results of displacement(RAO)   are different?
How to set mooring line position well?
what kind of condition  the time period have Phase angle ?
![image](https://cloud.githubusercontent.com/assets/23226663/24405091/2ad61308-13f6-11e7-9db9-dcd8381c075b.png)
ths u

**Comment by yuyihsiang** [comment]
1. if the stiffness matrix set at two different positions the results of displacement(RAO) are different?
Yes, the results will be different
2. How to set mooring line position well? 
Please clarify your question.
3. What kind of condition the time period have Phase angle ?
Please clarify your question.

**Comment by kmruehl** [comment]
@stevenshine does this help?

**Comment by stevenshine** [comment]
ths u , i have solved.
i have another question
Are thre high order forces in WECSIM??
e.g:drift force.....

**Comment by kmruehl** [comment]
No, we do not account for drift or current.
