### ISSUE TITLE
Converting 1DOF NEMOH output to .h5 using MATLAB BEMIO

### ISSUE THREAD

**Issue by fuz95esi** [WEC-Sim/WEC-Sim#169]
When using the matlab bemio functions to convert some nemoh BEM results for only 1DOF in heave motion, the "Radiation_IRF" function fails. I believe this is due to hard-coding of the number of degrees of freedom in the "Read_NEMOH" function, which is set to 6 as seen in Line 81:

`    hydro(F).dof(m) = 6;  % Default degrees of freedom for each body is 6`

The number of DOF is set for NEMOH calculations in the "Nemoh.cal" file and could be read like the number of bodies or water depth.

Is there a particular reason for the DOF being set to 6? Should I only be collecting BEM results for motion in 6DOF?

Thanks for your time and effort in maintaining this wonderful code!

**Comment by j-vanrij** [comment]
Both of your observations are correct - the DOF in Nemoh are currently assumed to be 6, and yes, it would be fairly straight forward to read in and used the actual DOF instead. Nearly all of the BEMIO functions were written assuming the most common run scenario, which, as in your case, is not always true...

So, you have several options. 1) You could run Nemoh with 6 DOF and just not use the extra 5 in WEC-Sim (if that is what you are using). 2) You could modify Read_NEMOH to read in the actual DOF (and submit a pull request so other users can benefit from your changes as well, if you would like!).  3) You could create your own .h5 file as outlined in: http://wec-sim.github.io/WEC-Sim/features.html#writing-your-own-h5-file. 4) Or, you could wait for us to make the changes, which depending on time available, may take awhile…

Thanks for the question!
