### ISSUE TITLE
Verification status for BEMIO function Read_AQWA

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WEC-Sim#171]
WEC-Sim Team, 

Thanks for a good webinar yesterday on BEMIO and MCR. 

During the webinar, it was mentioned that the BEMIO function Read_AQWA.m has not been well verified.  Is that also true of the AQWA reader in the python version, or does only the MATLAB version warrant concern?

Thanks,

Toby.

**Comment by j-vanrij** [comment]
Both the python and MATLAB versions of BEMIO were tested with the same, single, AQWA case (provided in the tutorials\BEMIO\AQWA\Example file). So, both the python and MATLAB versions of BEMIO have the same, minimal, level of verification. 

But to be clear, we have no knowledge that there _are_ bugs in Read_AQWA, and don’t want to cause concern, just thought it would be fair to warn users that Read_AQWA hasn’t been tested as extensively as Read_Nemoh and Read_WAMIT. 

So if you find issues please let us know. And thanks for attending the webinar and the feedback!

**Comment by Toby-D** [comment]
Thanks for clarifying. 

We've used AQWA data in BEMIO, and the only bug that we discovered was fixed in WEC-Sim/bemio#37. We'll definitely let you know if we come across anything else.
