### ISSUE TITLE
Issue while saving cell pressures in responseClass

### ISSUE THREAD

**Issue by yannickdebruyne-ca** [WEC-Sim/WEC-Sim#178]
Hello,

I spotted a problem at line 47-48 of responseClass.m. It seems that the linear presssure and the non-linear pressure are exchanged when saving to the output structure. 

Thank you for addressing this issue,
Regards,

Yannick

**Comment by yuyihsiang** [comment]
Hi Yannick

Thank you for finding that bug. It is fixed now.

-Yi-Hsiang
