### ISSUE TITLE
About add WEC-Sim into the directory

### ISSUE THREAD

**Issue by rz311** [WEC-Sim/WEC-Sim#181]
It works fine, it just can't be added to my own directory. I had to add it each time. When I created the Startup file, it does show the path is "<>" is wrong.

**Comment by kmruehl** [comment]
The wecSimPath variable needs to be defined as a string, and copied into the startup.m file. Here is an example of what mine looks like. Hope this helps.

```
wecSimPath = 'C:\Users\kmruehl\Documents\GitHub\WEC-Sim\WEC-Sim\source';
addpath(genpath(wecSimPath));
```
