### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by AleixWG** [WEC-Sim/WEC-Sim#183]
Hello,

I'm Aleix from Wedge Global, spanish company, we recently started to use and learn wec-sim since we find it as a very powerful tool for our company but we need a little help to fully understand how your code works and how can we improve it. Will you offer some kind of workshops in a near future?

Also, we are researching about negative springs in two-body WEC's and how they affect on the performance of the devices, but we are having troubles trying to add this kind of technology in wecsim.
We think it needs to be added as part of the .m code and not in the simulink part since negative springs generates a force affecting to floater and spar, where your simulink blocks only allows a unique external force applied directly to the PTO.
Being so we are trying to find where wecsim calculates the position, velocity and acelerations for the different bodies so maybe we can add the negative spring effect in that code, can you tell us where to find this part of the code?

Finally a more basic question about the outputs and just to be sure im right in my assumptions, what units does wecsim generate the outputs: (m) (s) (m/s) (N)?

Thank you for creating this tool and for your time reading and answering me. I will keep an eye to this board but you can contact me directly in: aarenas@wedgeglobal.com

**Comment by yuyihsiang** [comment]
Hi Aleix

PTO is actually a joint, which means the force will be added to both bodies no matter what. There is no need for passing the response from each body to calculate the spring force. The purpose of the PTO joint is to have simulink do all the hard work for you.

However, you won't be able to directly implement a negative spring in the input file because sinmulink does not allow the spring stiffness coefficient for the joint to be negative. The way to get around that is to use the block "Translational PTO Actuation Force" instead of "Translational PTO" so that you can add another block to calculate the negative spring force based on the relative motion and negative spring stiffness and pass the force back to the PTO.

Everything is reported in SI units

Thanks,

-Yi-Hsiang

**Comment by AleixWG** [comment]
Thanks for your feedback. We already had a negative spring block for simulink, but it needs position, velocity and acceleration for each body as inputs, generating one force for each body as output, this output is easy to adapt now that we know the joint adds the force to both bodies.

But for the inputs i have one more question, "transitional PTO Actuation Force" generates a response with "position", "velocity" and "acceleration", im assuming this are relative values between bodies, thats fine and we can work with that but is there anyway to get the response for each body (floater, spar)?

I have one last question, will you host any webinar or workshop in a near future? The tutorial you provide is very complete, but any extra advice or know-how we can get to make the best use of your tool is always appreciated.

Thanks,
Aleix

**Comment by kmruehl** [comment]
@AleixWG the [next webinar is June 13](http://energy.sandia.gov/wec-sim-webinar-june-13-2017/). Information about the WEC-Sim webinar series is[ available on our website here](http://wec-sim.github.io/WEC-Sim/webinars.html). If you would like to be added to our mailing list, please provide your email address.

Thank you!

**Comment by yuyihsiang** [comment]
Short answer is yes you can. However, you will have to manually pass the information out of the hydrodynamic block (inside the body block) to the block or the place you want to use. See the figure below, the red blocks are the output "position", "velocity" and "acceleration" for the body.

<img width="1282" alt="screen shot 2017-06-08 at 8 54 45 am" src="https://user-images.githubusercontent.com/4603391/26935062-39526188-4c28-11e7-82fc-1ed49b388620.png">

Let me know if that make sense to you

-Yi-Hsiang

**Comment by yuyihsiang** [comment]
To make things easier, you can also use a "goto" block (at the location you want) to receive the info from the "from" block so that the information passing can be "wireless".

--Yi-Hsiang

**Comment by AleixWG** [comment]
@kmruehl Definitely, add me to the mailing list please, i will assist to your webinars.

@yuyihsiang At first sight it makes perfect sense to me, with your suggestions we can now continue our modelization. I will let you know (here or in a new thread if you close this one, since the doubts have been solved for now) if we succeed in our attempt of effectively adding this negative spring or if we found another dead end, either case thanks for your time and detailed feedback.

Aleix

**Comment by AleixWG** [comment]
@kmruehl i forgot to post my e-mail for the mailing list: aarenas@wedgeglobal.com
