### ISSUE TITLE
AQWA excitation phase

### ISSUE THREAD

**Issue by kmruehl** [WEC-Sim/WEC-Sim#186]
I am trying two identical cylinders separated by 5 diameters in the x direction and I get the attached.  I am most interested in heave motion.  The body 2 results seem a little bonkers, but generally in phase.  Should I really consider switching to WAMIT, or is there some way I can get around it with what I have from AQWA?
-Bret

**Comment by kmruehl** [comment]
Does that excitation force include both Froude-Krylov and diffraction? If it does, can you plot only the Froude-Krylov? The Froude Krylov force should be identical for both bodies except for a phase shift. Also it would help if you can plot wave length in the x-axis instead of frequency. Also, what is the diameter of the cylinders?
-Carlos

**Comment by kmruehl** [comment]
Thanks for the questions.  It turns out that the Froude-Krylov values are all NaNs.  I checked the h5 file and they are nans there too.  I peeked at the .lis file and things look OK there.  The diameter of the cylinders is 0.62m.  I am modeling at tank test scale.  Any suggestions?
-Bret

**Comment by kmruehl** [comment]
Sounds like WEC-Sim has a bug when loading the lis file 
-Carlos

**Comment by kmruehl** [comment]
In Read_AQWA.m for BEMIO the following is near the end of the script.
```
% Eventually update this to read in excitation force components from .LIS file here
hydro(F).sc_ma = NaN(size(hydro(F).ex_ma));
hydro(F).sc_ph = NaN(size(hydro(F).ex_ph));
hydro(F).sc_re = NaN(size(hydro(F).ex_re));
hydro(F).sc_im = NaN(size(hydro(F).ex_im));
hydro(F).fk_ma = NaN(size(hydro(F).ex_ma)); 
hydro(F).fk_ph = NaN(size(hydro(F).ex_ph));
hydro(F).fk_re = NaN(size(hydro(F).ex_re));
hydro(F).fk_im = NaN(size(hydro(F).ex_im));
```

-Bret

**Comment by dforbush2** [comment]
The Read_AQWA script has been updated and now reads in Froude-Krylov+diffraction (.fk) and diffraction (.sc) from the .lis output file.

**Comment by kmruehl** [comment]
@dforbush2 thank you!

**Comment by kmruehl** [comment]
issue from @bretbosma

I have two heaving cylinders spaced with a one diameter gap between them offshore (x direction).  I have run wecSim and am plotting the resultant heave positions of both bodies as shown below.  The amplitude response is different as I might expect, but the phase seems to be the same.  If the wave is propagating through it seems to me that there should be a phase difference.

 ![excphase](https://user-images.githubusercontent.com/4603379/31788500-224d5c92-b4cc-11e7-8e77-66ec03a6feba.png)

If I understood our conversation from before you indicated that the phase shift should be included in the excitation force.  I have plotted that below and don't see a phase shift.
![respphase](https://user-images.githubusercontent.com/4603379/31788501-227d51d6-b4cc-11e7-85a4-238c73599023.png) 

Please let me know if  I am thinking about this wrong and if you have any suggestions of things to try.  Does this work differently for the other BEM inputs?

**Comment by kmruehl** [comment]
@bretbosma, thank you for your patience. 

@dpatterson-nmt @dforbush2 and I have looked into this issue with the AQWA excitation phase rather extensively. While we agree that the excitation phase produced by the WEC-Sim response above appears incorrect (in phase when it should be out of phase), we've compared the direct AQWA output (from the *.lis file) with the output from BEMIO parser (in the *.h5 file) for several multi-body cases, and the excitation phases from all the cases we checked match. This leads us to believe is that issue is with how AQWA reports excitation phase, not with how BEMIO or WEC-Sim parse the excitation phase. 

There may be a flag in AQWA that reports the excitation phase in global coordinates instead of body coordinates (or similar), but without access to AQWA, we cannot further debug the issue. In short, we recommend using another BEM solver (WAMIT or NEMOH) when modeling arrays of WECs to ensure the excitation phase is properly reported. 

Attached is an excel sheet which plots the AQWA output directly from the *.lis file, and below are plots comparing the excitation phase from the direct AQWA output with the BEMIO excitation phase . 
  
**Plot of AQWA (*.lis) output**
<img width="200" alt="x1_phase" src="https://user-images.githubusercontent.com/4603379/32806291-413fa8a8-c949-11e7-951a-c1ee22a65b28.PNG"> <img width="200" alt="x3_phase" src="https://user-images.githubusercontent.com/4603379/32806293-415fbbc0-c949-11e7-8a40-337672e2b081.PNG"> <img width="200" alt="x5_phase" src="https://user-images.githubusercontent.com/4603379/32806294-417a8716-c949-11e7-9e41-3a592197e4d5.PNG">

**Plot of AQWA BEMIO parser (*.h5) output**
![bemioexcforcephase](https://user-images.githubusercontent.com/4603379/32805916-1b81ec8a-c948-11e7-98c3-dfb1e88939a0.png)

**Excel sheet plotting the AQWA (*.lis) output**
[X_compare.xlsx](https://github.com/WEC-Sim/WEC-Sim/files/1472583/X_compare.xlsx)
