### ISSUE TITLE
Generating H5 hydrodata file

### ISSUE THREAD

**Issue by asubram8** [WEC-Sim/WEC-Sim#190]
While trying to follow WEC-Sim steps as given it says that I have to generate a .STL format file of my design. After that it says running BEM code, one generates .HDF5 hydrodynamic coefficients using BEMIO, but to run BEMIO and generate HDF5 file one needs a ".OUT" format file. Kindly guide me on how to generate this .HDF5 file.
Thanks In Advance
Akshith

**Comment by kmruehl** [comment]
BEMIO can be run to parse several different BEM code data into the *H5 format. The *out format is for WAMIT. For more info about BEMIO, refer to the [bemio documentation](http://wec-sim.github.io/WEC-Sim/features.html#bemio ) and the [bemio webinar](http://wec-sim.github.io/WEC-Sim/webinars.html#wec-sim-webinar-1-bemio-mcr).
