### ISSUE TITLE
OrcaFlex Input Files

### ISSUE THREAD

**Issue by aonghusoc** [WEC-Sim/WEC-Sim#196]
Hi,
I'm interested in reproducing the OrcaFlex results detailed in this paper:
OMAE2014-24312-Preliminary Verification and Validation of WEC-Sim
[https://wec-sim.github.io/WEC-Sim/publications.html#](url)

Are the OrcaFlex input files publicly available?

Best wishes,
Aonghus

**Comment by yuyihsiang** [comment]
Hi Aonhgus

I believe those sim and dat files are in the folder from the link below. I am not 100% sure if it was the exact same run, but at least should be a very similar one.
https://www.dropbox.com/sh/jd4bsyno62xn2hu/AACxPNWE9gwbcYMYhTt5SxWRa?dl=0

-Yi-Hsiang

**Comment by aonghusoc** [comment]
Thank you very much!
