### ISSUE TITLE
Hydraulic jump/shoaling effect

### ISSUE THREAD

**Issue by waveenergyharnessingdevice** [WEC-Sim/WEC-Sim#200]
The Wavergy team is interested in simulating a "crystalline lattice" point absorber tethered to a variable-depth, buoyant, pressurized barge with 8 "active-heave" winches which control barge depth and mooring line tension between the barge top deck and the crystalline lattice point absorber. PTO will include crystalline lattice free body motion and regenerative braking system within the barge. bluff-body tests were run in the wave tank at Stevens Institute of Technology and hydraulic jump/shoaling Particle Image Velocimeter data was recorded and should still be available from the Davidson Lab towing/wave tank records. What is the best approach to simulate this multi-body system in WEC-Sim? I believe the MCR feature must be used, but I will need help using that feature.

**Comment by kmruehl** [comment]
To model new devices we typically start with working WEC-Sim model (such as one of the tutorials), and modify it to represent your WEC. The WEC-Sim website provides [tutorials for the RM3 and the OSWEC](http://wec-sim.github.io/WEC-Sim/tutorials.html), both of which are multi-body WEC cases, and included in the WEC-Sim [source code tutorials](https://github.com/WEC-Sim/WEC-Sim/tree/master/tutorials). 

The best way to get familiar with how to run WEC-Sim using MCR is to look at our [online documentation for Multiple Case Runs](http://wec-sim.github.io/WEC-Sim/advanced_features.html#multiple-condition-runs-mcr).  There is a [MCR example case](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/RM3_MCR) on the WEC-Sim Applications, and a [webinar ](http://wec-sim.github.io/WEC-Sim/webinars.html#webinar-1-bemio-and-mcr)on the topic.
