### ISSUE TITLE
problem while installing

### ISSUE THREAD

**Issue by mathyturing** [WEC-Sim/WEC-Sim#212]
i'm new in wec-sim, i do not suceed in installin wec-sim
how to find matlab startup folder?
when I type pwd on the matlab command, I get a directory but there is no startup .m file there
should I create one?
I have created one and copied the code contained in the wecSimStartup.m
I have also change the value of the variable wecSimPath as follows
![screenshot1](https://user-images.githubusercontent.com/33290729/32446684-f4637a04-c309-11e7-9a69-40e163782c48.png)

but i get the error 
startup.m not found
when I write open startup.m
on matlab command window

**Comment by kmruehl** [comment]
@mathyturing your `startup.m` should be located in your MATLAB path. Typically, this is `C:\Users\yourUserName\Documents\MATLAB`. If there is not a `startup.m` file in that directory, add the one you created. 

FYI `startup.m` should be located in the MATLAB path (not the WEC-Sim directory).

**Comment by mathyturing** [comment]
thanks for your quick reaction.

**Comment by mathyturing** [comment]
and what should be the value of the wecSimPath variable?
I have set it to the path to the folder into wich the WecSimStartup is contained.
I have done the following
![screehoot2](https://user-images.githubusercontent.com/33290729/32488848-551a8668-c3ae-11e7-9e90-b98d463a7a86.png)


are  they the right values??/

**Comment by kmruehl** [comment]
That is the correct path. The WEC-Sim path refers to the location of the `WEC-Sim/source` directory. 

[see online doc here](http://wec-sim.github.io/WEC-Sim/getting_started.html#step-1-add-wec-sim-source-code-to-matlab-path)

**Comment by mathyturing** [comment]
thank U very much

2017-11-07 16:55 GMT+01:00 Kelley Ruehl <notifications@github.com>:
