### ISSUE TITLE
unclear class: ptoSim motion mechanics

### ISSUE THREAD

**Issue by serag-abdulmotaleb** [WEC-Sim/WEC-Sim#213]
are there any documentation or tutorials regarding the ptosim.motionmechanics class? 
I know there is one for the OSWEC crank with hydraulic motor. I'm asking, however, is there a more detailed example or any info on how to use this class for articulations between multiple structures

**Comment by kmruehl** [comment]
@serag-abdulmotaleb unfortunately  [OSWEC_Hydraulic_Crank_PTO](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim/OSWEC_Hydraulic_Crank_PTO) is the only example application we provide. If you have a specific question, @ratanakso may be able to help you. He developed PTO-Sim, but he is no longer working on WEC-Sim code development.
