### ISSUE TITLE
Error Running RM3 MoorDyn

### ISSUE THREAD

**Issue by blazingdog2** [WEC-Sim/WEC-Sim#219]
Hi,

I have downloaded C/C++ and the moordyn files as mentioned in the webinar. However every time the simulation is being ran the following error is shown.

Error using wecSim (line 241)
Error in 'RM3MoorDyn/MoorDyn': Initialization commands cannot be evaluated.
Caused by:
    Error using textread (line 159)
    File not found.

![moordyn error](https://user-images.githubusercontent.com/33406048/32947358-70f0d13c-cbd6-11e7-977a-660c531d2769.PNG)

Please assist, 
Thank you

**Comment by yuyihsiang** [comment]
You are missing the mooring folder and the moorDyn setup file (lines.txt) inside the folder.

Please pull the latest WEC-Sim (or directly from WEC-Sim_Applications repo), which should have a mooring folder in this example folder.

Yi-Hsiang

**Comment by blazingdog2** [comment]
Hi sorry, after placing the moordyn and mooring folder i am still getting the same error.

![error](https://user-images.githubusercontent.com/33406048/33472555-d2c96dec-d6ad-11e7-9a77-b38220acc810.PNG)

Wei Jie

**Comment by kmruehl** [comment]
@blazingdog2 did you run `wecSim` from the local path of your`wecSimInputFile.m`? In the screenshot you've included, your MATLAB path is not `\RM3_MoorDyn`.

If you still have this error, please ZIP your model and @yuyihsiang will help debug. Thank you.

**Comment by blazingdog2** [comment]
Its working now thank you very much for your help!

Wei Jie

**Comment by Legaze** [comment]
Hello,
I am running the same tutorial but I am getting a different problem with the software, could you help me, I asked the same question in the wrong issue; sorry about it.

![image](https://user-images.githubusercontent.com/13293786/49498550-b237f180-f86b-11e8-8c11-09fade85b63c.png)

Thanks a lot,
Leo
