### ISSUE TITLE
Control-Sim application example

### ISSUE THREAD

**Issue by GuillaumeSab** [WEC-Sim/WEC-Sim#222]
Dear WEC-Sim team,

I am still working on the RM3 tutorial provided with WEC-Sim to implement MPC and adaptive control strategies.

I recently saw your commits of the Control-Sim project that embed a MPC strategy on the RM3 model.
I am wondering if this project is related in any way to the WECCCOMP competition for control of wave energy and if you are about to release a new version of WEC-Sim that support this example.
Apparently, the parameter phaseRand from waveClass.m is still missing to run this example and I am not sure what to do to make it run.

Thanks in advance,
Guillaume

**Comment by kmruehl** [comment]
@GuillaumeSab the Control-Sim repo is not related to the WECCCOMP competition, and unfortunately we do not currently have the bandwidth to support it. If you would like to read more about the Control-Sim work, please refer to @ratanakso's [PhD dissertation](https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/z316q655j). 

As for how to specify irregular waves with seeded phase, refer to the [updated WEC-Sim documentation](http://wec-sim.github.io/WEC-Sim/advanced_features.html#irregular-waves-with-seeded-phase). The only thing you'll need to change is the variable previously called `waves.randPreDefined` is now called `waves.phaseSeed`. Refer to the [WEC-Sim tutorials ](https://github.com/WEC-Sim/WEC-Sim/tree/master/tutorials), their variable names have been updated accordingly.  See [release notes](https://github.com/WEC-Sim/WEC-Sim/releases) for other variable name changes.
