### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by wyg110sjtu** [WEC-Sim/WEC-Sim#223]
Dear Sirs:

When I ran WEC-Sim-3.0 \tutorials\RM3 in MatLab R2014b, I met the following warnings:

WEC-Sim Read Input File ...   
No public field rampTime exists for class simulationClass.

Error in wecSimInputFile (line 7)
simu.rampTime = 100;                   	% Wave Ramp Time [s]

Error in wecSim (line 29)
evalc('wecSimInputFile');
 
Why????

Please kindly responde me. Thanks.

John

**Comment by yuyihsiang** [comment]
Hi John

The error comes from the changes WEC-Sim parameters

- waves.randPreDefined -> waves.phaseSeed
- waves.phaseRand -> waves.phase
- simu.dtFeNonlin -> simu.dtNL
- simu.rampT -> simu.rampTime

Please modify your wecSimInputFile.m accordingly.

In addition, WEC-Sim only supports MATLAB R2015b or after and, in fact, we recommend running WEC-Sim in MATLAB 2016b or newer.

Thanks,

Yi-Hsiang
