### ISSUE TITLE
Question about selector block

### ISSUE THREAD

**Issue by balboaf** [WEC-Sim/WEC-Sim#226]
Hi, thanks for the WEC-Sim tool.

I have very little time interacting with the code in Matlab (Matlab2015b), recently started to make the diagram in Simulink and I have a question regarding the selector block. 

I am studying an OWSC device, therefore, a rotational motion which should represent the selector block as shown in figure will have.

![image](https://user-images.githubusercontent.com/34801789/34323590-28645cca-e82f-11e7-9b47-4d428233dfb4.png)

But, I do not understand how to configure the parameters of the selector block to that configuration.

![image](https://user-images.githubusercontent.com/34801789/34323571-80b5a7b8-e82e-11e7-88a5-21825700bca4.png)

I would appreciate if I could help with the step by step to understand the operation of the block; It also would make progress in my study.

Thank and happy celebration!

**Comment by yuyihsiang** [comment]
Hi Balboaf 

The index you showed in the second figure means that you will output the first and third value of the input vector. In other words,

output vector has a size of 2 and will equal to [v(1) V(3)], where v is the input vector.

More details can be found in
https://www.mathworks.com/help/simulink/slref/selector.html?requestedDomain=www.mathworks.com

Hopefully, this is helpful for you.

Yi-Hsiang

**Comment by balboaf** [comment]
Then, for the configuration shown in the first figure must exit the fifth value of the input vector. The vector of output will be of size 1 and would be equal to the vector of input v (5). Would the size of the value of "Input Port Size" is 6?

![image](https://user-images.githubusercontent.com/34801789/34499702-fd6a0e34-efe5-11e7-96f6-b7e5a1c52dac.png)

**Comment by kmruehl** [comment]
Correct, `input port size` refers to the number of input ports, in this case 6 for the number of DOF input. And `index` refers to the index number of the input signal, in this case 5 for pitch (RY) motion.
