### ISSUE TITLE
Untethered WEC

### ISSUE THREAD

**Issue by sanjainarain** [WEC-Sim/WEC-Sim#233]
I was wondering if WEC can be used in untethered mode to power a UUV or ship. There is an interesting concept here https://www.youtube.com/watch?v=3bF-p1BEXLA. 

Can we simulate this crawler in WEC. For example, can a WEC system be moored to the ship? 

I am new to the WEC concept but am starting a project on synthesis and verification of CPS. WEC may be a very good focus for our work. 

Thanks. -- Sanjai (snarain@vencorelabs.com)

**Comment by kmruehl** [comment]
@sanjainarain yes, WEC-Sim can be used to simulate a device like the crawler video you posted.

**Comment by sanjainarain** [comment]
OK. Thanks. -- Sanjai
