### ISSUE TITLE
oswec/base 

### ISSUE THREAD

**Issue by alam92** [WEC-Sim/WEC-Sim#236]
![oswec base](https://user-images.githubusercontent.com/37398935/37502908-6e15d06a-2910-11e8-8c39-4dd83d37af98.jpg)

 what the problem mean?
i stuck,please help me @kmruehl #235

**Comment by kmruehl** [comment]
Please refer to documentation on how to [execute WEC-Sim](http://wec-sim.github.io/WEC-Sim/overview.html#step-4-execute-wec-sim)

> Execute the WEC-Sim code by typing `wecSim` into the MATLAB Command Window. WEC-Sim simulations should always be executed from the MATLAB Command Window, not from the Simulink/SimMechanics model.
