### ISSUE TITLE
RM3 problem

### ISSUE THREAD

**Issue by alam92** [WEC-Sim/WEC-Sim#237]
![rm3](https://user-images.githubusercontent.com/37398935/37503229-212bf7aa-2912-11e8-8361-b9698dba1347.jpg)

so far this problem also same as my problem at oswec/base..can anybody tell me why? i just a beginer in this matlab software.. #235 @kmruehl

**Comment by kmruehl** [comment]
Please refer to documentation on how to [execute WEC-Sim](http://wec-sim.github.io/WEC-Sim/overview.html#step-4-execute-wec-sim)

> Execute the WEC-Sim code by typing `wecSim` into the MATLAB Command Window. WEC-Sim simulations should always be executed from the MATLAB Command Window, not from the Simulink/SimMechanics model.
