### ISSUE TITLE
simulation

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/WEC-Sim#238]
when i want to  run wecSim
the message box show 
![image](https://user-images.githubusercontent.com/23226663/37604132-3c9b3904-2bcb-11e8-99a0-b71b5edb0f63.png)
what does it mean ?
how to modify?
thank u

**Comment by kmruehl** [comment]
This error means that the Impulse Response Function (IRF) calculated is shorter than the convolution integral time specified in the input file. To resolve this issue you can either:
- Reduce the convolution integral time of your simulation by changing the `simu.CITime` in your `wecSimInputFile.m` 
- Rerun BEMIO and specify a longer end time (`t_end`) for the calculation of the impulse response functions. Refer to the [documentation on bemio functions](http://wec-sim.github.io/WEC-Sim/advanced_features.html#bemio-functions ) for the Radiation_IRF and Excitation_IRF.

**Comment by stevenshine** [comment]
Hi @kmruehl 
thank u help me but i still have some quesions
the message show when i run menoh
![image](https://user-images.githubusercontent.com/23226663/37641127-8a00a2f0-2c53-11e8-8610-7e7589d1d7a0.png)
