### ISSUE TITLE
calculate moring force chart

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/WEC-Sim#239]
i input mooring force in matrix way, but the dont show in result chart .
why are there the condition?
thank u
![image](https://user-images.githubusercontent.com/23226663/37749501-25549f48-2dc3-11e8-9dd8-90301096931b.png)

**Comment by yuyihsiang** [comment]
The figure is showing the force from the body block. The mooring force is implemented using a separate mooring block. Therefore, to plot the mooring force, you will need to plot the values from output. mooring.mooringForce.

Yi-Hsiang

**Comment by kmruehl** [comment]
@stevenshine does this answer your question?
