### ISSUE TITLE
Nonlinear excitation force calculation

### ISSUE THREAD

**Issue by ahmedmetin** [WEC-Sim/WEC-Sim#242]
Hello

While I was simulating a cylindrical buoy in heave with nonlinear excitation force (nlHydro=2), I found that the final excitation force does not equate to 0 when the buoy goes completely out of the water. As far as I have figured it out the way you have implemented the total excitation force is the sum of the linear excitation force pre-computed with excitation force coefficients, nonlinear excitation force computed using the instantaneous draft of the buoy minus the linear excitation force computed with the mean draft of the buoy. I have modified the Diffraction and Excitation Function Matlab Function block to output the heave f_nonlinear and f_linear signals. You can see in the plot below that f_nonlinear gets equal to 0 when the buoy gets out of the water. (The bottom plot shows wave elevation from mean water level minus the elevation of the center of the buoy, which coincide with the CG). The total height of the buoy is 5.78m and CG = 0, i.e. when z_wave - z_buoy < -5.78/2, the buoy goes out of the water. 
Is there some inaccuracy in WEC-Sim's excitaiton force model when the buoy pops out the water or is it compensated somehow somewhere else in the model?

![excitation_forces](https://user-images.githubusercontent.com/32479811/38172777-9130afc6-35b2-11e8-8357-f7dbbdcffde3.png)

Thanks in advance.

**Comment by yuyihsiang** [comment]
In WEC-Sim. the "total" excitation force includes  both the diffraction and the wave Froude–Krylov force. For nonlinear simulations, the basic assumption is that the diffraction part is still based on linear theory and the Froude–Krylov force is calculated based on instantaneous wave elevation and body position. Therefore, even if the body is out of the water, the diffraction part WON'T be zero. The method is a "weakly nonlinear" model, and this is just the way typically how this simple model is applied.

Yi-Hsiang

**Comment by kmruehl** [comment]
@ahmedmetin does this answer your question?
