### ISSUE TITLE
OSWEC moment of inertia

### ISSUE THREAD

**Issue by NicolasQu** [WEC-Sim/WEC-Sim#243]
Hi,
In the tutorial of the OSWEC, the moment of inertia is given as 1850000 kg m².
Is this the moment of inertia about the centre of gravity?
And the added moment of inertia, given after the bemio calculation, is this also about the centre of gravity? 
I'm talking about hydro.A(5,5,:), the added moment of inertia for pitch.

Thanks in advance!
Regards
Nicolas

**Comment by yuyihsiang** [comment]
Hi Nicolas

Everything in WEC-Sim is defined at CG, from the mass matrix to added mass matrix from WAMIT/Nemoh/AQWA.

Yi-Hsiang
