### ISSUE TITLE
non-linear hydrostatic calculation

### ISSUE THREAD

**Issue by oliviergius** [WEC-Sim/WEC-Sim#254]
Hi,

I have a comment regarding how WEC-sim calculates the restoring forces with the .STL file.
I had a look at the function [f,p] = fHydrostatic(center,elv,instcg,av,rho,g) in the Nonlinear Hydrostatic Restoring force block of the Rigid Body block.
Considering a simple case, e.g. a cube that only moves in heave. This fHydrostatic function will compute the vertical restoring force based on the horizontal bottom panels of the cube - on their areas and z positions. and this z position is not impacted by the wave elevation in the function. so the vertical restoring force will be the same whatever the instantaneous wave elevation; it will depend only on the absolute vertical motion of the body.
I made a test by changing the "wave elevation" input of the block by a constant = 0 and indeed vertical restoring forces are the same in both cases.
I guess a simple way to correct this would be to write z = z-elv before calculating pressureVect.
Thanks for your answer!

**Comment by yuyihsiang** [comment]
Yes, in the hydrostatic block, the hydrostatic force is not directly affect by the wave elevation, it will depend only on the absolute vertical motion (position) of the body and also if the panel is underwater or above water. Note that hydrostatic pressure is zero above the water surface. On the other hand, the influence of the wave was included in the wave excitation block based on instantaneous wave elevation and body position.
