### ISSUE TITLE
Directional waves

### ISSUE THREAD

**Issue by emiliofa** [WEC-Sim/WEC-Sim#257]
Hi all,

I am investigating the possibility to include directional waves in WEC-Sim for irregular waves. Has this topic already been considered? I was considering to update just the formula of the excitation force considering the random phase generation for all the directions, a spreading function for the directional spectrum and the hydrodynamic excitation coefficients for all the directions that the directional spectrum is approximated. Then the excitation force is calculated from the sum of the directions and frequencies considered.

Thanks,
Emilio Faraggiana
PhD student at Swansea University

**Comment by yuyihsiang** [comment]
Hi Emilio

That will be great. Directional wave has been on our wish list. It will be great if you are welling to share with all the user. Please do a pull request once you add the capability. The BEMIO should already have the capability to read in all the hydrodynamic coefficients for directional waves. This should be sufficient for you to do what you are proposing. Let us know if you have any question. regarding the blocks and sub-blocks.

Thanks,

Yi-Hsiang

**Comment by emiliofa** [comment]
Hi,

yes I will gladly share when I will finish to add it. Especially I would like to have some comments about it for any errors.

Thanks,
Emilio
