### ISSUE TITLE
Has anyone used WEC-Sim for an array of WECs?

### ISSUE THREAD

**Issue by elcf** [WEC-Sim/WEC-Sim#271]

**Comment by kmruehl** [comment]
@elcf Thanks for your question. To the best of my knowledge people have dabbled in using WEC-Sim to model arrays, but it has never been fully explored and validated.

**Comment by elcf** [comment]
Thanks @kmruehl, what would be a straightforward way of doing this? I assume that if using the hydrodynamic data, one would have to somehow do a linear superposition of the results. And for the weakly non-linear... I assume that would that be a bigger overhaul the code?

**Comment by kmruehl** [comment]
@elcf Did this answer your question?

**Comment by elcf** [comment]
@kmruehl, thank you so much for your help. I've been on travel so I've not had a chance to sit down and work things out. But I think I follow the logic: simulate the multi-array in WEC-Sim as it was one system with multiple bodies.

As for the non-linear, yes I was referring to WEC-Sim's non-linear hydrodynamics sim option. Would using that option follow the same logic as above? Using multi-body and body-to-body interactions on?

**Comment by elcf** [comment]
@kmruehl, okay got it, thank you for your help!
