### ISSUE TITLE
Mooring stiffness matrix - units

### ISSUE THREAD

**Issue by Ale4c** [WEC-Sim/WEC-Sim#275]
Please, can you tell me the units of measurement for the stiffness, damping and pretension coefficients? I could not find them anywhere.

I need to scale my model between different scales and I need to be sure I am scaling it correctly. 

Thank you

**Comment by kmruehl** [comment]
@Ale4c [WEC-Sim uses SI units](http://wec-sim.github.io/WEC-Sim/theory.html#units), so stiffness is {N/m}, damping is [Ns/m], and pretension forces is [N]. Hope this helps.
