### ISSUE TITLE
Using Wec-Sim in a matlab function

### ISSUE THREAD

**Issue by RomainLLB** [WEC-Sim/WEC-Sim#280]
Hello,

I made a main script in matlab that set values and then call wecSim without any problems.
But when I want to make a function (the aim is to call it with python), Matlab returns me the folowing error:

Error using wecSim (line 257)
    The variant control 'sv_b3_hydroBody' of the variant block 'trans_comp_spring_rig2/flap' must be a condition expression or name
    of a Simulink.Variant object in the global scope workspace of the model.    Error using wecSim (line 257)
    The variant control 'sv_b3_nonHydroBody' of the variant block 'trans_comp_spring_rig2/flap' must be a condition expression or
    name of a Simulink.Variant object in the global scope workspace of the model. 

Where "flap" is a body of the simulink model.

Can you help me please ?

Regards,

RLLB

**Comment by yuyihsiang** [comment]
Hi RLLB,

First, we have never tried to run WEC-Sim from python before. 

Looking at your error messages, it could be some environment setting issues. Can you be more specific on how WEC-Sim was called in the python script or upload the files?

Thanks,

Yi-Hsiang
