### ISSUE TITLE
How to include viscous damping

### ISSUE THREAD

**Issue by vishnuvijayasankar** [WEC-Sim/WEC-Sim#282]
Is viscous damping automatically calculated in WEC-Sim? I know that BEM code is based on the assumption of inviscid flow. So, how can I take account of the viscous damping in WEC-Sim?

P.S: My body is not slender D/λw > 0.2 and I've calculated total damping from experimental decay tests.

**Comment by kmruehl** [comment]
@vishnuvijayasankar viscous damping is not automatically calculated in WEC-Sim, it is only applied is the user specifies a damping value.  Refer to the online documentation here: http://wec-sim.github.io/WEC-Sim/advanced_features.html#viscous-damping-and-morison-elements/
