### ISSUE TITLE
Bug in irregular waves with zero ramp time

### ISSUE THREAD

**Issue by crobarcro** [WEC-Sim/WEC-Sim#285]
When you set the ramp time to zero for irregular waves only the first value of the phases is used, instead of all the values because of an indexing error in `waveElevIrreg`. In the ` if rampTime==0` case, there is the following:

`tmp1    = tmp.*real(exp(sqrt(-1).*(obj.w.*t + obj.phase(idir,:))));`

but `obj.phase` is a column vector and so `obj.phase(idir,:)` is just a single value, the first value in the vector of phases, and the result is crazy values. The case for when there is a ramptime gets it right with

`tmp1  = tmp.*real(exp(sqrt(-1).*(obj.w.*t + obj.phase(:,idir))));`

where the `idir,:` is flipped to `:,idir`

**Comment by kmruehl** [comment]
@crobarcro Thanks for catching this bug. Can you submit a pull request with this waveClass fix?
