### ISSUE TITLE
How to reopen the Mechanics Explorer animation 

### ISSUE THREAD

**Issue by Liam-Guerrero** [WEC-Sim/WEC-Sim#290]
Hi WEC-Sim Community,

Is there any way to view the animation that we see in the mechanics explorer from saved data (after wecSim run is over)

Thanks

Juan Guerrero-Fernández

**Comment by kmruehl** [comment]
@Liam-Guerrero yes, you can export the Mechanics Explorer animation as a video. There are also options to split the screen and have multiple views. Mathworks has some good documentation/forums on how to do this: https://www.mathworks.com/help/physmod/sm/ug/create-a-model-animation-video.html
