### ISSUE TITLE
How to Access the original WAMIT (Not demo version)

### ISSUE THREAD

**Issue by AmirH7076** [WEC-Sim/WEC-Sim#303]
Hello.
Would you please advise me how to get & access the original version of WAMIT? (Not demo version).
Best Regards.

**Comment by crobarcro** [comment]
I'm not one of the developers, just another user, but I can't help but wonder, have you tried doing an internet search for "WAMIT"? I mean, there's actually a website www.wamit.com?

**Comment by kmruehl** [comment]
@AmirH7076 as @crobarcro responded, you'll have to purchase a WAMIT license from http://www.wamit.com/ to get the full (no demo) version of the software.
