### ISSUE TITLE
Currents in WEC-Sim

### ISSUE THREAD

**Issue by jackhughes1** [WEC-Sim/WEC-Sim#305]
Hi, I am inquiring about the possibility of implementing hydrodynamic loading on a body from tidal currents and have a few questions:

1. Is there any work at present which may include an implementation of this kind? 
2. Is this even possible? 
3. If so, where may be a good place to start?

Apologies for the vague questions, but any help would be greatly appreciated!

Best regards, 
Jack H

**Comment by kmruehl** [comment]
Current was added in WEC-Sim in the following commit: https://github.com/WEC-Sim/WEC-Sim/commit/71c68920c16c4ce7b36f4bd9e21096aa202fe24a
