### ISSUE TITLE
Body 1 and 2 labeling

### ISSUE THREAD

**Issue by tedbrekken** [WEC-Sim/WEC-Sim#309]
A minor issue, perhaps, but in the text generated at the MATLAB command line after entering "wecSim" to run WEC-Sim for a two body system (e.g. RM3), there is a subheader "List of Body: Number of Bodies = 2".  Under that header, some hydrodynamic parameters of Body Number 0 and Body Number 1 are identified.  This numbering is at odds with the numbering used elsewhere, which is Body 1 and Body 2.

**Comment by yuyihsiang** [comment]
Changed
