### ISSUE TITLE
Recommend additional commenting on wave height parameter for PM and JS

### ISSUE THREAD

**Issue by tedbrekken** [WEC-Sim/WEC-Sim#310]
Following up on a previous issue I submitted, I recommend adding a comment to the the "waves.H" setting for the PM and JS spectrums, noting that changes to this parameter have no effect.

**Comment by kmruehl** [comment]
Thanks for the recommendation, I updated the documentation and added a note to the log. FYI, significant wave height, `Hs`, is used for the `'JS'` formulation, but the `'PM'` formulation is only based on peak period, `Tp`.
