### ISSUE TITLE
where can I find the result about power?

### ISSUE THREAD

**Issue by accient** [WEC-Sim/WEC-Sim#313]
After running the example , I didn't see any result of power generation efficiency or power generation. Where can I find it?
![image](https://user-images.githubusercontent.com/37647393/61857147-22c47900-aef6-11e9-97e4-700fe9abae73.png)
![image](https://user-images.githubusercontent.com/37647393/61857192-37087600-aef6-11e9-9cda-dec1df789498.png)

**Comment by yuyihsiang** [comment]
output.ptos.powerInternalMechanics. Please note that this comes with a negative sign.

**Comment by accient** [comment]
Thank you
