### ISSUE TITLE
I can't see the arrow to go to the sub-blocks in the RM3 file.

### ISSUE THREAD

**Issue by GyeongKim** [WEC-Sim/WEC-Sim#315]
Hi.
I am a very beginner for the WEC-Sim and a user of MATLAB 2019a.
Now I am studying how to use the WEC-Sim, but I can't see the arrow to go to the sub-blocks in the RM3 file.
Could somebody let me know how to do it?
Many thanks for your help.
![그림1](https://user-images.githubusercontent.com/53353128/62017521-ff632d80-b184-11e9-8818-5e582e5a82ee.png)

**Comment by kmruehl** [comment]
It looks like the arrow button has been removed. You can either hit `Ctrl+U`, or you can right click on the block and select Mask->Look Under Mask. 

![image](https://user-images.githubusercontent.com/4603379/62172005-2c7f1f80-b2ee-11e9-8718-e26a1b2bd8f0.png)

**Comment by GyeongKim** [comment]
Thank you.

**Comment by kmruehl** [comment]
No problem, glad to help.
