### ISSUE TITLE
Jenkins Test Issue

### ISSUE THREAD

**Issue by zmorrell-sand** [WEC-Sim/WEC-Sim#316]
I am opening this issue to test Jenkins CI using GitHub WebHooks.  If this successfully makes Jenkins build, I will close this issue.  Otherwise, I will type single character responses to illicit another test.  The issue will be closed when Jenkins is functional.

**Comment by zmorrell-sand** [comment]
a

**Comment by zmorrell-sand** [comment]
a

**Comment by zmorrell-sand** [comment]
Jenkins is now set up to poll the repository every hour to rebuild.  At the time of writing for this comment, the test cases are deprecated and do not run, but Jenkins is operable.  When the tests are fixed, I will have Jenkins begin sending failure notifications to @kmruehl

**Comment by kmruehl** [comment]
@zmorrell-sand I'll work on updating the test cases.

**Comment by kmruehl** [comment]
I updated the verification file
