### ISSUE TITLE
Read_NEMOH.m doesn't work in linux

### ISSUE THREAD

**Issue by crobarcro** [WEC-Sim/WEC-Sim#323]
Read_NEMOH.m has recently added a line like this:

`if exist(fullfile(filedir,'Results','Kochin.    1.dat'),'file')==2`

In linux this is always false as the directory is lower case `results`, as is actually known by someone who wrote this as it is (sort-of) correctly handled further down.

A better way to code this would be to do something like:

```
    if exist ( fullfile (filedir, 'mesh'), 'dir') == 7
        
        meshdir = fullfile (filedir, 'mesh');
        
    elseif exist ( fullfile (filedir, 'Mesh'), 'dir') == 7
        
        meshdir = fullfile (filedir, 'Mesh');
        
    else
        error ('mesh (or Mesh) directory not found in working folder');
    end
    
    if exist ( fullfile (filedir, 'results'), 'dir') == 7
        
        resultsdir = fullfile (filedir, 'results');
        
    elseif exist ( fullfile (filedir, 'Results'), 'dir') == 7
        
        resultsdir = fullfile (filedir, 'Results');
        
    else
        error ('results (or Results) directory not found in working folder');
    end
```
then use `resultsdir` and `meshdir` throughout (for goodness sake!).

**Comment by kmruehl** [comment]
@crobarcro Thank you very much for catching this bug and for the suggested revision. Your suggestion for handling the `meshdir `and `resultsdir` is _much_ cleaner, so I went ahead and implemented it in `READ_NEMOH.m`. Please let me know if this resolves this issue. We are aware of your other open issue and are in the process of resolving it as well. Thank you!
