### ISSUE TITLE
Nemoh - Hyrdostatics Gen with workflow

### ISSUE THREAD

**Issue by uzayr123** [WEC-Sim/WEC-Sim#325]
Currently unable to generate Hydrostatics.dat and KH.dat files required by WEC-Sim, because I'm not using NEMOH to generate the mesh in the first instance. My workflow is as follows :
Generate mesh in SALOME > Export with quads as .dat > convert to format readable by nemoh via converter script from NEMOH toolbox > run NEMOH on that file

Kwadl provided a toolset in #286, but I'm trying to avoid converting to .stl to retain quads and as such simulation accuracy.

Is there anyway to do this? Help appreciated

**Comment by yuyihsiang** [comment]
You can run Mesh.exe to generate the Hydrostatics.dat and KH.dat files. What you need to do is to 

- Change the Mesh.cal "Target for the number of panels in refined mesh" to the number of the panel you have in your mesh file.

- Rename and modify your mesh file "mesh_file_name.dat" to a mesh file as described in  the "Mesh generation using the Mesh code" section in https://lheea.ec-nantes.fr/logiciels-et-brevets/nemoh-mesh-192932.kjsp?RH=1489593406974

Yi-Hsiang
