### ISSUE TITLE
Tutorial using Nemoh in Matlab

### ISSUE THREAD

**Issue by ammar-alfaili** [WEC-Sim/WEC-Sim#326]
Hello

I want to simulate wave forces on a cylinder in Nemoh. I wanted to see if anyone can guide me since it is the first time i am doing this, implementing/using  Nemoh in Matlab. 

thank you in advance

**Comment by yuyihsiang** [comment]
See the example from Nemoh Website
https://lheea.ec-nantes.fr/logiciels-et-brevets/nemoh-examples-192931.kjsp?RH=1489593406974

You should be able to modify the example and may answer your questions.

Yi-Hsiang

**Comment by ammar-alfaili** [comment]
yes, I have seen that example but I still don't know how to use Nemoh in matlab. That's the main problem. 

\Ammar

**Comment by yuyihsiang** [comment]
Unfortunately, we only provide an interface with Nemoh, and this is a question for Nemoh.

**Comment by cadu55br** [comment]
I created a MATLAB script for a Vertical Cylinder with Flat bottom (VCF_Tutorial_Arnal_axiMesh_Nemoh_Bemio.m), based on the presentation "NEMOH: a tutorial using the Matlab wrapper", by Vincent Arnal, 11-2014 (arnal.vinc@gmail.com). See attached. 
I hope it can help you. Good luck!
Carlos

[Example of MATLAB script for running NEMOH.txt](https://github.com/WEC-Sim/WEC-Sim/files/4017019/Example.of.MATLAB.script.for.running.NEMOH.txt)

[NEMOH Tutorial, by V.Arnal.pdf](https://github.com/WEC-Sim/WEC-Sim/files/4017020/NEMOH.Tutorial.by.V.Arnal.pdf)

**Comment by kmruehl** [comment]
@cadu55br thank you for providing this example.

**Comment by ammar-alfaili** [comment]
Hello Carlos

Thanx a lot. This was very helpful. I appreciate it.


Best regards

Ammar

________________________________
Fra: Carlos Silva <notifications@github.com>
Sendt: 2. januar 2020 20:05:03
Til: WEC-Sim/WEC-Sim
Cc: Ammar Galib Al-Faili; Author
Emne: Re: [WEC-Sim/WEC-Sim] Tutorial using Nemoh in Matlab (#326)


I created a MATLAB script for a Vertical Cylinder with Flat bottom (VCF_Tutorial_Arnal_axiMesh_Nemoh_Bemio.m), based on the presentation "NEMOH: a tutorial using the Matlab wrapper", by Vincent Arnal, 11-2014 (arnal.vinc@gmail.com<mailto:arnal.vinc@gmail.com>). See attached.
I hope it can help you. Good luck!
Carlos

Example of MATLAB script for running NEMOH.txt<https://github.com/WEC-Sim/WEC-Sim/files/4017019/Example.of.MATLAB.script.for.running.NEMOH.txt>

NEMOH Tutorial, by V.Arnal.pdf<https://github.com/WEC-Sim/WEC-Sim/files/4017020/NEMOH.Tutorial.by.V.Arnal.pdf>

**Comment by dith96** [comment]
Hello..
I just found this page while looking for a tutorial on installing and using Nemoh.. 
I want to simulate waves for OWC in Nemoh for my final project, but until now I'm still confused about how to use it..
Is there anyone can guide me using Nemoh? Please.. help me anyone.. This is my first time trying  Nemoh.

Thank you..

**Comment by Javeria503** [comment]
hello i am a beginner to NEMOH i did not have any idea about that how to used it if someone can help me with this it will be much helpful for me.

**Comment by kmruehl** [comment]
@Javeria503 unfortunately we do not provide NEMOH support. However, we do have some BEMIO examples that using NEMOH here: https://github.com/WEC-Sim/WEC-Sim/tree/main/examples/BEMIO/NEMOH

**Comment by cadu55br** [comment]
@Javeria503, in order to try to help you, I am sending below the link to a PDF copy of my master's dissertation, presented to COPPE/UFRJ on 21/December/2020, as a partial fulfillment of the requirements for the degree of Master of Science (M.Sc.):
"STUDY ON THE MAXIMIZATION OF THE ABSORBED POWER OF POINT ABSORBER WAVE ENERGY CONVERTERS IN RIO DE JANEIRO, BRAZIL"
"ESTUDO SOBRE A MAXIMIZAÇÃO DA POTÊNCIA ABSORVIDA DE CONVERSORES DE ENERGIA DAS ONDAS DO TIPO ABSORVEDOR PONTUAL NO RIO DE JANEIRO, BRASIL"

Link: 
https://lnkd.in/dX2g_e3H

Unfortunately, the text is in Portuguese, but with an online translator it is possible to understand most of the text.

I suggest you pay attention to APÊNDICE D (Appendix D, page 169/246), which contains "Examples of Inputs and Outputs of the Programs Used", as well as the respective MATLAB scripts.

I hope this information is useful to you.
Good luck and best regards.
Carlos

**Comment by kmruehl** [comment]
@cadu55br thank you!

**Comment by Javeria503** [comment]
@cadu55br Hello can you guide me how to use BEM for only diffraction problem. I look your examples but in my case the structure is fixed not floating. Thanks _

**Comment by bibble18** [comment]
@cadu55br Hi carlos your files have been very helpful to the project I am currently working on. However I am facing issue with running Nemoh and BEMIO for the sphere for now(it worked well on cylinder), is there any way I can have your contact(email or anything) that would be very helpful.
