### ISSUE TITLE
Error in Read_AQWA (line 178) ind = tmp1(1:2); tmp1(1:2)=[];

### ISSUE THREAD

**Issue by sricharanvvs** [WEC-Sim/WEC-Sim#329]
Hi,
When I am reading AQWA files in BEMIO the error shown below pops up. 
Can anyone help me to understand why this error is popping up?
I dont think either of .AH1 and .LIS files are not corrupted as they show the data when I open it unlike a garbage data, what could be the reason for this? Please help in sorting out this ASAP.

 Is this due to more number of bodies? Is there any limit?
Thank YOU.
Charan.
![Screenshot (82)](https://user-images.githubusercontent.com/51389362/71143837-f5c88800-2241-11ea-8bc1-354d1c877720.png)

**Comment by sugarl14** [comment]
Do anyone have any tips for figuring this out? I am having the same issue.

![image](https://user-images.githubusercontent.com/57150958/74551081-8ceb4c80-4f20-11ea-81ae-9449b68248a4.png)
