### ISSUE TITLE
Nemoh results from tutorial\bemio\rm3

### ISSUE THREAD

**Issue by frrfrz** [WEC-Sim/WEC-Sim#330]
Hello, i am trying to replicate the the same test using nemoh, but i am not able to get the same results, running mesh.exe i obtain the same hydrostatics and kh results but when i run preprocessor.exe, solver.exe and postprocessor.exe i obtain some completely different results. I suppose that the problem could be my mesh, are there any ''rules'' for creating the nemoh mesh?
I create the mesh with rhino using the command mesh from surface.
In the attachment you will find my mesh and the nemoh folder where i run the code and the results as well.
Thanks in advance for your help.
[nemoh.zip](https://github.com/WEC-Sim/WEC-Sim/files/4046789/nemoh.zip)

**Comment by yuyihsiang** [comment]
I was trying to run you BEMIO to check it, but it can not find the hydorstatic.dat file.

Yi-Hsiang

**Comment by frrfrz** [comment]
I am sorry i forgot to attach that file, now in the attachments you will find the folder ready to run with bemio. Thank you very much.
[nemoh.zip](https://github.com/WEC-Sim/WEC-Sim/files/4066894/nemoh.zip)

**Comment by DavidTran2008** [comment]
Hi frrfrz,

As the official NEMOH release has not been implemented irregular frequency removal functionality, your issue is likely caused by this function rather than mesh resolution. However, higher mesh resolution could somewhat avoid irregular frequency issue as well. You can take a look at the attached file for details.

Regarding irregular frequency removal functionality, you may want to try it using OpenWARP code.
[NEMOH Issue330.pdf](https://github.com/WEC-Sim/WEC-Sim/files/4073845/NEMOH.Issue330.pdf)

Best,
Toan

**Comment by frrfrz** [comment]
Hello, Toan, Thank you so much for the fast response and you time, i am going to make one last attempt using an higher mesh resolution, and if this way doesn't work i ll try with openWARP. I ll keep you updated.

Thank you
Fabrizio

**Comment by frrfrz** [comment]
Just one last question, i can't understand why using the same nemoh.cal input file (so same frequency range and step) and the float.dat and spar.dat from the tutorial  the result that i obtain are good. Thank you

**Comment by TTToan2008** [comment]
If I understand correctly, you meant that you obtained a good agreement (no spike) between WAMIT and NEMOH using inputs from WEC-Sim repository. If so, which NEMOH version are you using? Did you include IRR function or other?

By the way, I just ran NEMOH simulation using exact **inputs from NEMOH folder** of WEC-Sim repo plus **your NEMOH mesh**. The result looks pretty good (attached figures) and it is similar to that of NEMOH result of WEC-Sim repo.
![Added-Damping](https://user-images.githubusercontent.com/21998751/72572319-671a4b80-387f-11ea-97a7-90c8201a6c64.jpg)

![Added-Mass](https://user-images.githubusercontent.com/21998751/72572327-6bdeff80-387f-11ea-9062-b5e3fca0c4aa.jpg)

**Comment by frrfrz** [comment]
Yes my problem is that if i run nemoh with the mesh from wecsim\tutorial\bemio\rm3 i obtain the results that you posted above, but if in the same folder i run nemoh with my mesh and then i run bemio i obtain different results.
![image](https://user-images.githubusercontent.com/57464560/72619971-6bd91100-390c-11ea-80bf-216c052b3fce.png)
![image](https://user-images.githubusercontent.com/57464560/72620032-83b09500-390c-11ea-918e-11f0d2edb986.png)
(i've obtained these results running bemio from the folder that i sent you)
That's why i thought that the mesh was the problem. Same nemoh.cal, mesh.exe, preprocessor.exe, solver.exe, postprocessor.exe.
My nemoh version is the v2_03.

**Comment by frrfrz** [comment]
P.S. I am running nemoh through the command window, i run mesh.exe separately fot the two bodies and then i just run prprocessor.exe, solver.exe and postprocessor.exe through a .bat file. You can find everything i use inside the folder i sent you.

**Comment by TTToan2008** [comment]
Hi,

Sorry for my late response.
I think your mesh has an issue. As you look at meshes displayed in Meshmagick tool, your mesh resolution is really small at heave plate of spar part.  I think this is the reason why there are so many spikes in the results either NEHOH or WAMIT (WAMIT result showed in the previous file looks cleaner). Therefore, I would recommend that you should avoid different mesh resolution among discontinuous surfaces (e.g., heave plate side).  Additionally, you might want to consider a bigger mesh cell of spar closed to the water surface as well. 

Let me know if that helps.
Thanks,
Toan

![NEMOH_Issue330](https://user-images.githubusercontent.com/21998751/72947911-db9e3000-3d40-11ea-8b0f-1b4eb3126e69.png)
![NEMOH_WEC-Sim Repo](https://user-images.githubusercontent.com/21998751/72947912-db9e3000-3d40-11ea-842c-2849bc44ad23.png)

**Comment by frrfrz** [comment]
Hello Toan, with your suggestion everything works. I am not sure if the problem was caused just by the heave plate side, anyway i ve changed that mesh and also aligned the vertical lines of the spar mesh and float mesh.
![thickplatebad](https://user-images.githubusercontent.com/57464560/73206751-7ddb6080-4111-11ea-9c9f-aa71abc4ad29.JPG)
![thickplategood](https://user-images.githubusercontent.com/57464560/73206752-7ddb6080-4111-11ea-83de-bb0c8243359a.JPG)
![mesh gross](https://user-images.githubusercontent.com/57464560/73206753-7e73f700-4111-11ea-95f2-a73cf63d9f45.JPG)
![sparmesh0](https://user-images.githubusercontent.com/57464560/73206754-7e73f700-4111-11ea-96a7-02b5605240a9.JPG)
Thank you so much for your time and help. You saved my master thesis.

Fabrizio
