### ISSUE TITLE
Need help in modeling of the original WEC concept

### ISSUE THREAD

**Issue by Getmoreter** [WEC-Sim/WEC-Sim#331]
Hello everybody!
I am developing an original concept of a wave energy converter and would like to find a person who can help with drawing up a quality model. I am new to programming and run into problems in almost everything. An additional difficulty is that I have not seen mechanics similar to my concept in any other converter and I can not even imagine how to describe it in the simulator. If you are ready to discuss the details and conditions, please write to me at dbogdanovich@yandex.ru. I really hope for your help!
All the best!

**Comment by kmruehl** [comment]
@Getmoreter this is an issue board for the WEC-Sim code, so we cannot provide support unless it's directly related to the use and application of WEC-Sim.
