### ISSUE TITLE
most recent failed build results clogging commit history, and my feed.

### ISSUE THREAD

**Issue by crobarcro** [WEC-Sim/WEC-Sim#333]
It seems someone has set up Jenkins to commit the most recent failed build to the WEC-Sim repo. This will spell doom for the WEC-Sim commit history, and also pollutes the feed of anyone following the project. 

In any case this is not the type of thing one should be committing to the repository, the repository should be for code not transitory data or info.

**Comment by kmruehl** [comment]
@crobarcro we are aware of this issue, and are in the process of streamlining the Jenkins build failure reports so that it doesn't clog the commit history. These commits should be squashed now. Our apologies for the inconvenience.
