### ISSUE TITLE
Can WEC-Sim be used for Control Systems?

### ISSUE THREAD

**Issue by sugarl14** [WEC-Sim/WEC-Sim#335]
Using WEC-Sim, can I figure out the plant variable that represents the system of the WEC? I want to simulate an MPC controller in MATLAB/Simulink that controls a WEC, and was curious if WEC-Sim can provide the information needed for the plant variable.

![question](https://user-images.githubusercontent.com/57150958/73849203-8578c480-47f7-11ea-9107-2deb71367721.JPG)

**Comment by nathanmtom** [comment]
@sugarl14 Thank you for your question. If I may first ask a clarifying question, is it your desire to obtain a linear state space representation of the device plant model? or are you asking if WEC-Sim can model the dynamics of the device plant model? 

If your question is in reference to a linear state space representation, the answer would be not directly. WEC-Sim does contain all the information to build a linear state space representation if needed but not automatically; however, you will need to run the state space approximation of the radiation convolution integral or use constant hydrodynamic coefficients. 

If your question is in reference to a model of the device plant model, yes WEC-Sim can be used to model the dynamic behavior of a device given a control input. 

Please let me know if this has answered your question, if not feel free to ask a follow on question or ask for clarification on my comments above.
