### ISSUE TITLE
coordinate system

### ISSUE THREAD

**Issue by Tudore** [WEC-Sim/WEC-Sim#338]
Hi, may I check with you if I have several bodies, what are the coordinate systems for motion descriptions? In other words, are the output motions with reference to the global system or local systems? 

Thanks！

**Comment by kmruehl** [comment]
The WEC-Sim coordinate system is defined here: http://wec-sim.github.io/WEC-Sim/theory.html#coordinate-system. The global coordinate system has its origin at the still water line. Output for each body are defined relative to a body-fixed coordinate system with its origin at the body's cg.
