### ISSUE TITLE
where are RM3/OSWEC wamit files ?

### ISSUE THREAD

**Issue by avidortelem** [WEC-Sim/WEC-Sim#346]
Hello,

The first time I installed WECSIM I remember that the wamit files of the tutorials were available.

Since I cloned wecSim from GitHub there are not here anymore.

Where can I found them ?

I am trying to find them to see how multiple bodies should be run in wamit, is the generalised modes option available in wecsim ?

Best,

**Comment by kmruehl** [comment]
@avidortelem they are available here: https://github.com/WEC-Sim/WEC-Sim/tree/master/examples/BEMIO

They've been moved from tutuorials to examples.
