### ISSUE TITLE
error loading AH1 and LIS files from  AQWA output files

### ISSUE THREAD

**Issue by ignacio-byte** [WEC-Sim/WEC-Sim#350]
i can´t convet the AH1 and LIS files to h5.files

clc; clear all; close all;
hydro = struct();

hydro = Read_AQWA(hydro,'aqwa_example_data.AH1','aqwa_example_data.LIS');
hydro = Radiation_IRF(hydro,15,[],[],[],[]);
%hydro = Radiation_IRF_SS(hydro,[],[]);
hydro = Excitation_IRF(hydro,15,[],[],[],[]);
Write_H5(hydro)
Plot_BEMIO(hydro)

i did not change the name in scrip instead i rename the "ANALYSIS" file to "aqwa_example_data"
i use matlab R2019a
ANSYS aqwa 2019R3
wecsim 4.0
i dont know if there is a problem whith the version of programs
but the thing is when i run the scrip i get this error

Unable to perform assignment because the indices on the left side are not compatible with the size of the right
side.

Error in Read_AQWA (line 201)
                hydro(F).sc_ma((kdiff-1)*6+1:kdiff*6,j,i) = tmp1;  % mag of scattering force

Error in bemio (line 4)
hydro = Read_AQWA(hydro,'aqwa_example_data.AH1','aqwa_example_data.LIS');

function hydro = Read_AQWA(hydro,ah1_filename,lis_filename)

% Reads data from AQWA output files.
%
% hydro = Read_AQWA(hydro, ah1_filename, lis_filename)
%     hydro ?         data structure
%     ah1_filename ?  .AH1 AQWA output file
%     lis_filename ?  .LIS AQWA output file
%
% See ??\WEC-Sim\tutorials\BEMIO\AQWA\...? for examples of usage.

[a,b] = size(hydro);  % Check on what is already there
if b==1
    if isfield(hydro(b),'Nb')==0  F = 1;
    else  F = 2;
    end
elseif b>1  F = b+1;
end

p = waitbar(0,'Reading AQWA output file...'); %Progress bar
e = 0;

hydro(F).code   = 'AQWA';
V182            = 0; % Set AqwaVersion flag "Version 18.2 or larger" to 0
tmp             = strsplit(ah1_filename,{' ','\','.'});
hydro(F).file   = tmp{length(tmp)-1};  % Base filename

fileID          = fopen(ah1_filename);
raw1            = textscan(fileID,'%[^\n\r]'); %Read/copy raw output, ah1
raw1            = raw1{:};
fclose(fileID);
fileID          = fopen(lis_filename);
raw2            = textscan(fileID,'%[^\n\r]'); %Read/copy raw output, lis
raw2            = raw2{:};
fclose(fileID);
N               = length([raw1(:);raw2(:)]);

% n=2;
n = 1;
TF = 1;
while TF == 1
    if isempty(strfind(raw1{n},'LHFR'))==0; V182 = 1; end % Change Aqwa Version flag to 1 if specific string is found in header
    n   = n+1;
    TF  = startsWith(raw1(n),'*');
end

tmp = str2num(raw1{n});
COGidx=find(contains(raw1,'COG'),1); % finds line of COG heading
DRAFTidx=find(contains(raw1,'DRAFT'),1); % finds line of DRAFT heading
hydro(F).Nb = (DRAFTidx-COGidx)-1; % Number of bodies is the distance between (in all tested versions)
    
for i=1:hydro(F).Nb
    hydro(F).body{i}    = ['body' num2str(i)]; %Body name
    hydro(F).dof(i)     = 6;  % Default degrees of freedom for each body is 6
end
hydro(F).Nh     = tmp(2);  % Number of wave headings
hydro(F).Nf     = tmp(3);  % Number of wave frequencies
hydro(F).beta   = [];
for i = 1:ceil(hydro(F).Nh/6)
    hydro(F).beta   = [hydro(F).beta str2num(raw1{n})]; % Wave headings
    n               = n+1;
end
hydro(F).beta(1:3) = [];
hydro(F).w = [];
for i=1:ceil(hydro(F).Nf/6)
    hydro(F).w = [hydro(F).w str2num(raw1{n})]; % Wave frequencies
    n = n+1;
end
hydro(F).T = 2*pi./hydro(F).w;

for ln = n:length(raw1);
    if isempty(strfind(raw1{ln},'GENERAL'))==0
        if V182 == 1  % General information columns in Versions>18.2
            tmp = str2num(raw1{ln+1});
            hydro(F).h      = tmp(2);   % Water depth
            hydro(F).rho    = tmp(3); % Water density
            hydro(F).g      = tmp(4);   % Gravity
        else          % General information columns in Versions<18.2
            tmp = str2num(raw1{ln+1});
            hydro(F).h      = tmp(1);   % Water depth
            hydro(F).rho    = tmp(2); % Water density
            hydro(F).g      = tmp(3);   % Gravity
        end
        clear V182
    end
    if isempty(strfind(raw1{ln},'COG'))==0
        for i=1:hydro(F).Nb
            tmp = str2num(raw1{ln+i});
            hydro(F).cg(:,i) = tmp(2:4); % Center of gravity
        end
    end
    if isempty(strfind(raw1{ln},'DRAFT'))==0
        for i=1:hydro(F).Nb
            tmp = str2num(raw1{ln+i});
            draft(i) = tmp(2); % Draft
        end
    end
    if (isempty(strfind(raw1{ln},'HYDSTIFFNESS'))==0 |...
            (isempty(strfind(raw1{ln},'MASS'))==0 & isempty(strfind(raw1{ln},'ADDEDMASS'))==1))
        if isempty(strfind(raw1{ln},'HYDSTIFFNESS'))==0 f = 0; else f = 1; end
        for j=1:hydro(F).Nb
            for i=1:6
                tmp = str2num(raw1{ln+(j-1)*6+i});
                if length(tmp)>6 tmp(1)=[]; end
                if f==0
                    hydro(F).C(i,:,j) = tmp; % Linear restoring stiffness
                elseif f==1
                    M(i,:,j) = tmp; % Mass
                end
            end
        end
    end
    if ((isempty(strfind(raw1{ln},'ADDEDMASS'))==0) && isempty(strfind(raw1{ln},'LF'))==1 && isempty(strfind(raw1{ln},'HF'))==1) || ...
            (isempty(strfind(raw1{ln},'DAMPING'))==0 && isempty(strfind(raw1{ln},'LF'))==1)
        if isempty(strfind(raw1{ln},'ADDEDMASS'))==0 f = 0; else f = 1; end
        for m=1:hydro(F).Nb
            for k=1:hydro(F).Nb
                for j=1:hydro(F).Nf
                    for i=1:6
                        tmp = str2num(raw1{ln+(m-1)*hydro(F).Nb*hydro(F).Nf*6+(k-1)*hydro(F).Nf*6+(j-1)*6+i});
                        if length(tmp)>6 ind = tmp(1:3); tmp(1:3)=[]; end
                        if f==0 % Added Mass
                            hydro(F).A((ind(2)-1)*6+i,((ind(1)-1)*6+1):(ind(1)*6),ind(3)) = tmp;
                        elseif f==1 % Radiation Damping
                            hydro(F).B((ind(2)-1)*6+i,((ind(1)-1)*6+1):(ind(1)*6),ind(3)) = tmp;
                        end
                    end
                end
            end
        end
    end
    if isempty(strfind(raw1{ln},'FORCERAO'))==0
        for k=1:hydro(F).Nb
            for j=1:hydro(F).Nh
                for i=1:hydro(F).Nf
                    tmp1 = str2num(raw1{ln+(k-1)*hydro(F).Nh*hydro(F).Nf*2+(j-1)*hydro(F).Nf*2+(i-1)*2+1});
                    tmp2 = str2num(raw1{ln+(k-1)*hydro(F).Nh*hydro(F).Nf*2+(j-1)*hydro(F).Nf*2+(i-1)*2+2});
                    ind = tmp1(1:3); tmp1(1:3)=[];
                    hydro(F).ex_ma(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) = tmp1; % Magnitude of exciting force
                    hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) = -tmp2*pi/180; % Phase of exciting force
                end
            end
        end
        hydro(F).ex_re = hydro(F).ex_ma.*cos(hydro(F).ex_ph); % Real part of exciting force
        hydro(F).ex_im = hydro(F).ex_ma.*sin(hydro(F).ex_ph); % Imaginary part of exciting force
    end
    d = floor(10*ln/N);  %Update waitbar every 10%, or slows computation time
    if (d>e) waitbar(ln/N); e = d; end
end

hydro(F).Vo = [];
hydro(F).cb = [];
lnlog=zeros(length(raw2),1); % initialize line find log
for ln=1:length(raw2);
    if isempty(strfind(raw2{ln},'MESH BASED DISPLACEMENT'))==0
        tmp = textscan(raw2{ln}(find(raw2{ln}=='=')+1:end),'%f');
        hydro(F).Vo = [hydro(F).Vo tmp{1}];   % Volume
    
    elseif isempty(strfind(raw2{ln},'POSITION OF THE CENTRE OF BUOYANCY'))==0
        cb = [];
        for i=1:3
            tmp = textscan(raw2{(ln-1)+i}(find(raw2{(ln-1)+i}=='=')+1:end),'%f');
            cb = [cb; tmp{1}];
        end
        hydro(F).cb = [hydro(F).cb cb]; % Center of buoyancy
        
    elseif isempty(strfind(raw2{ln},'FROUDE KRYLOV + DIFFRACTION FORCES-VARIATION WITH WAVE PERIOD'))==0
        k=str2num(raw2{ln-2}(end-9:end-8));                       % Body number flag
        for j=1:hydro(F).Nh
            for i=1:hydro(F).Nf
                tmp1 = str2num(raw2{ln+6+(j-1)*(hydro(F).Nf+9)+(i-1)});
                if i==1;
                    ind = tmp1(1:3); tmp1(1:3)=[];
                else
                    ind = tmp1(1:2); tmp1(1:2)=[];
                end
                tmp2 = tmp1(2:2:end);
                tmp1(2:2:end)=[];
                hydro(F).fk_ma((k-1)*6+1:k*6,j,i) = tmp1;  % mag of froude Krylov force
                hydro(F).fk_ph((k-1)*6+1:k*6,j,i) = tmp2;  % phase of froude Krylov force
            end
        end        
        hydro(F).fk_re = hydro(F).fk_ma.*cos(hydro(F).fk_ph*pi/180); % real part of Froude Krylov force
        hydro(F).fk_im = hydro(F).fk_ma.*sin(hydro(F).fk_ph*pi/180); % imaginary part of Froude Krylov force
        lnlog(ln:ln+6+(j-1)*(hydro(F).Nf+9)+(i-1))=[ln:ln+6+(j-1)*(hydro(F).Nf+9)+(i-1)]; % avoids repeating line operations for repeated matches
        
    elseif isempty(strfind(raw2{ln},'DIFFRACTION FORCES-VARIATION WITH WAVE PERIOD/FREQUENCY'))==0 ...
            && isempty(strfind(raw2{ln},'FROUDE KRYLOV +'))==1
        kdiff=str2num(raw2{ln-2}(end-9:end-8));                       % Body number flag
        for j=1:hydro(F).Nh
            for i=1:hydro(F).Nf
                tmp1 = str2num(raw2{ln+6+(j-1)*(hydro(F).Nf+9)+(i-1)});
                if i==1;
                    ind = tmp1(1:3); tmp1(1:3)=[];
                else
                    ind = tmp1(1:2); tmp1(1:2)=[];
                end
                tmp2 = tmp1(2:2:end);
                tmp1(2:2:end)=[];
                hydro(F).sc_ma((kdiff-1)*6+1:kdiff*6,j,i) = tmp1;  % mag of scattering force
                hydro(F).sc_ph((kdiff-1)*6+1:kdiff*6,j,i) = tmp2;  % phase of scattering force
            end
        end        
        hydro(F).sc_re = hydro(F).sc_ma.*cos(hydro(F).sc_ph*pi/180); % real part of scattering force
        hydro(F).sc_im = hydro(F).sc_ma.*sin(hydro(F).sc_ph*pi/180); % imaginary part of scattering force
        lnlog(ln:ln+6+(j-1)*(hydro(F).Nf+9)+(i-1))=[ln:ln+6+(j-1)*(hydro(F).Nf+9)+(i-1)];        
    end
    
    d = floor(10*(ln+length(raw2))/N);  %Update waitbar every 10%, or slows computation time
    if (d>e) waitbar((ln+length(raw1))/N); e = d; end
    
end
hydro = Normalize(hydro);  % Normalize the data according the WAMIT convention
close(p);
end

**Comment by kmruehl** [comment]
@ignacio-byte Can you please upload the `*.AH1` and `*.LIS` AQWA files, and the `bemio.m` file you're using? That will allow us to reproduce and debug this error. Thank you.

**Comment by kmruehl** [comment]
@ignacio-byte can you upload the AQWA files for this case?
