### ISSUE TITLE
viscous drag relative velocity

### ISSUE THREAD

**Issue by avidortelem** [WEC-Sim/WEC-Sim#353]
Hello,

I have an issue to model the viscous force in WECSIM.

I already (before trying to go to WECSIM) have a time-domain to modelise a plate of 8*4.5m.

The theorical viscous force is:

<img width="273" alt="time" src="https://user-images.githubusercontent.com/43061767/80072610-c656be80-8546-11ea-8666-d3bce4fcf824.PNG">

Xi dot is the plate velocity and Uf the wave particle velocity, Sp the plate surface

In my time domain model the viscous force is modelized as:

relative_velocity= plate_velocity - particle_velocity_at_free_surface

Fv = 1/2 * rho * Cd * sp *  | relative_velocity | * relative_velocity

In WEC-SIM, it looks like  if I put 

body(1).viscDrag.cd=[Cd Cd Cd Cd Cd Cd]; % drag coefficient 
body(1).viscDrag.characteristicsArea=[sp sp sp sp sp sp]; % drag coefficient 

Then the drag force calculated by WECSIM will not used the relative velocity according to the wecsim theory chapter in the website.

How can I solve the drag force with relative velocity ?

I saw that there is the relative velocity in the drag part of the 'morison element', but I don't really understand why the relative velocity is not in the drag force above also.

If I am not wrong, I don't normally need to used the morison element with Ca, etc because the radiation force are already calculated with the hydro data.

Thanks for your help,

**Comment by yuyihsiang** [comment]
You are right that we did not include the flow velocity in the drag force but did include the flow velocity in Morison element. Typically, if we need to have the flow velocity to calculate the relative velocity, we use Morison element with ONE element and set Ca to zero (, which should be the default I think).
