### ISSUE TITLE
hydraulic PTO

### ISSUE THREAD

**Issue by kjbennichan** [WEC-Sim/WEC-Sim#374]
hi,
 Do hydraulic PTO option works in matlab 2016a. Is it available.

**Comment by dforbush2** [comment]
Hi @kjbennichan 

As mentioned in #368, WEC-Sim should support all versions back to 2016a.

Is there a specific error you are encountering?

Best,
Dom

**Comment by kjbennichan** [comment]
Hi,
 I don't know how to provide a hydraulic PTO. These are the options
obtained, it's in the attachment. How can I give hydraulic PTO.

**Comment by dforbush2** [comment]
Please see applications case: WEC-Sim_Applications\PTO-Sim\RM3_Hydraulic_PTO

The hydraulic PTO parameters are specified in the ``ptoSimInputFile.m``, and define the parameters in the "PTO-Sim" block of the accompanying ``RM3_Hydraulic_PTO.slx`` model.

**Comment by kmruehl** [comment]
@kjbennichan did this resolve your issue?
