### ISSUE TITLE
paraview error/pull request #382 

### ISSUE THREAD

**Issue by Aquaharmonics** [WEC-Sim/WEC-Sim#383]
Hello,

Just as an FYI, here is the original error that pull request #382 fixes when running WECSim with paraview visualization :

![image](https://user-images.githubusercontent.com/20505639/86500271-c3e1c380-bd44-11ea-80e8-9a6b1e34f261.png)

**Comment by kmruehl** [comment]
@Aquaharmonics thank you. We will get this issue resolved and merge your PR today.
