### ISSUE TITLE
How to use MoorDyn?

### ISSUE THREAD

**Issue by ZhiGN** [WEC-Sim/WEC-Sim#388]
I am a novice programmer. I can run the MoorDyn program, but the FAIRTEN in the result file Lines.out is deviated from the FairTens result generated by the matlab calculation example in the workspace.
![Snipaste_2020-07-20_17-39-51](https://user-images.githubusercontent.com/68538942/87923422-0b3fb200-cab0-11ea-8c65-229f2431fe8c.png)

**Comment by kmruehl** [comment]
@ZhiGN can you upload this WEC-Sim/MoorDyn model so that we can debug this issue?

**Comment by yuyihsiang** [comment]
Can you upload the files for us to check?

--Yi-Hsiang

**Comment by ZhiGN** [comment]
@kmruehl @yuyihsiang First of all thank you for your kind reply. This file is an example of moordyn published by Professor Hall. I haven't combined moordyn and wec-sim. When running separately, I found that the FAIRTEN in the result file Lines.out is different from the value output by the scope module in simulink, but I feel that the two values should be the same. I have seen the source program, but because I don't understand C++ programs, I didn't find the reason. Thank you again for your kind reply.
[Simulink.zip](https://github.com/WEC-Sim/WEC-Sim/files/4974853/Simulink.zip)
[MoorDyn v1.00.03C Source.zip](https://github.com/WEC-Sim/WEC-Sim/files/4974854/MoorDyn.v1.00.03C.Source.zip)

**Comment by yuyihsiang** [comment]
Thanks for uploading the data. I have asked Matt to take a look at this.

**Comment by mattEhall** [comment]
Hi @ZhiGN, there was an error in earlier versions of MoorDyn (half the weight of the top mooring line segment was neglected in the fairlead force calculation) that might explain the disagreement you're seeing. It was fixed a few years ago in version 1.01.01C. It looks like you're using an earlier version, so my recommendation would be to try v1.01.01C and see if it solves the problem.

**Comment by kmruehl** [comment]
I've added this issue to upgrading WEC-Sim to MoorDyn2 on the project board: https://github.com/WEC-Sim/WEC-Sim/projects/28

**Comment by yuyihsiang** [comment]
WEC-Sim/MoorDyn has been updated to the latest release version.

--Yi-Hsiang

**Comment by HANloading** [comment]
> I am a novice programmer. I can run the MoorDyn program, but the FAIRTEN in the result file Lines.out is deviated from the FairTens result generated by the matlab calculation example in the workspace. ![Snipaste_2020-07-20_17-39-51](https://user-images.githubusercontent.com/68538942/87923422-0b3fb200-cab0-11ea-8c65-229f2431fe8c.png)

你好，请问moordyn的调用解决了吗？？，能否加个联系方式？
