### ISSUE TITLE
2 bodies required for an OWESC?

### ISSUE THREAD

**Issue by sugarl14** [WEC-Sim/WEC-Sim#393]
Hi,

To run WEC-Sim with an OSWEC, are two bodies (the flap and the base) required? Or can I simply model just the hinged flap in the Simulink file?

**Comment by nathanmtom** [comment]
@sugarl14 You can model an OSWEC with either one body (no base) or two bodies (the flap and the base) and will be dependent on your system design.

**Comment by sugarl14** [comment]
Great. Thank you, Nathan!

Landon
