### ISSUE TITLE
Definining CG and CB in write_hdf5

### ISSUE THREAD

**Issue by Rodimus88** [WEC-Sim/WEC-Sim#404]
according to which reference coordinate system do i need to define the CG and CB of my geometry. relative to the sea level or the center of gravity or else. also do i need to provide moment of inertia for each axis to the wecSiminput.m?. i am a beginner just trying to simulate a simple point absorbing sphere using wecSim. can any one giude me how to do this correctly step by step.

**Comment by dforbush2** [comment]
You'll want to use a coordinate system with the origin at the body CG (if you have a homogeneous sphere, this is colocated with your CB) in your BEM calculations. You will be able to specify the initial location of this sphere's CG relative to the still-water line in the wecSimInputFile.m

**Comment by Rodimus88** [comment]
I had figured it out about the initial location relative to the still water line. thanks @dforbush2 for the help. if my sphere is not homogeneous (eg: hollow sphere) then how should i define the CB?. i have used the create_h5file.m to create hydrodynamic data.

**Comment by dforbush2** [comment]
In the case of a hollow sphere the CB should be at the geometric center of the sphere, coincident with your CG. The CB should be defined with the origin at the body CG in your BEM calculations, so in this specific instance [0,0,0].  WEC-Sim will determine the equilibrium position of the sphere relative to the still water line based upon its displacement and mass.

**Comment by Rodimus88** [comment]
According to physics, the CB should located in the cg of the displaced volume. isn't it. i though providing the mass and displacement help wec-sim to calculate the CB. the couple created by buoyancy and weight affects pitch and roll. so CG and CB should be two separate locations in reality. for this example it may not important. but generally you should consider it. @dforbush2 can you please explain this.

**Comment by dforbush2** [comment]
I edited my previous response. You are correct. The CB will not align with the CG (which is located at the center of the sphere) for a partially submerged homogeneous (or hollow) sphere. For a given sphere volume, a lighter sphere will have a lower CB, and a heavier sphere will have a higher CB. 

For hydrodynamic bodies, WEC-Sim reads the CB location from the *h5 file. WEC-Sim uses the CG and CB location defined in the *h5 file to perform hydrostatic restoring force calculations, which will include the pitch/roll moments resulting from non-colocated CB and CG. WEC-Sim uses the mass and volume of the body (and forces from attached additional bodies, moorings, etc.)  to determine the WEC equilibrium position relative to the still water line, but does not itself calculate the CB of any body.

If you are generating your own *h5 file and you need to determine the CG and CB for a complicated geometry where you cannot immediately deduce their location from their mass, there are tools available that can perform these calculations. I would recommend MeshMagick.

https://lheea.github.io/meshmagick/index.html

**Comment by Rodimus88** [comment]
Thank you @dforbush2 for the detailed explanation. so, finally the CG should defined relative to the still water level. and CB would also be expressed relative to the still water level.

**Comment by dforbush2** [comment]
WEC-Sim reads the CG and CB location from the *h5 file for hydrodynamic bodies. In your *h5 file, the location of the CG and CB should be relative to the free-surface. 
Sorry for the confusion I created, early on I had misunderstood your question.

**Comment by Rodimus88** [comment]
it's OK @dforbush2 . i have learned some by this conversation. thank you for sharing your knowledge and valuable time with me.
