### ISSUE TITLE
Defining userDefinedFunctions.m

### ISSUE THREAD

**Issue by Rodimus88** [WEC-Sim/WEC-Sim#406]
how to set up the userDefinedFunctions.m file for a custom problem. i just copy the userDefinedFunctions,m file from OSWEC tutorial and place in my project folder. then i encounter with following error,
![Screenshot (83)](https://user-images.githubusercontent.com/69836354/91309752-9ce8c080-e7ce-11ea-9237-659503ffd813.png)

**Comment by nathanmtom** [comment]
@Rodimus88 You are correct that if a userDefinedFunction is in the same working directory as your WEC-Sim files at the end of the simulation WEC-Sim will call the userDefinedFunction. In your screenshot above it appears that the userDefinedFunction has been called successfully, but it appears that there is no 'output' object in your 'Workspace'. Therefore, the userDefinedFunction stops and does not run to completion. You will need to complete a WEC-Sim run to generate the output object. 

Please let us know if this solves your issue. 

Cheers, 
Nathan 
National Renewable Energy Laboratory

**Comment by Rodimus88** [comment]
your solution has worked Mr @nathanmtom . thank you for your help.!!
