### ISSUE TITLE
Accessing WAMIT, NEMOH or AQWA's codes

### ISSUE THREAD

**Issue by h7ossein** [WEC-Sim/WEC-Sim#410]
Pretty self-explanatory title, 
I wanted to ask if there is a way for me to access WAMIT, NEMOH or AQWA's codes?

**Comment by dforbush2** [comment]
http://wamit.com/
https://github.com/LHEEA/Nemoh
https://www.ansys.com/products/structures/ansys-aqwa

Only NEMOH is open source but there may be trial versions of other software available.
