### ISSUE TITLE
waveClass('spectrumImport'): plotSpectrum

### ISSUE THREAD

**Issue by saltynexus** [WEC-Sim/WEC-Sim#412]
This is a minor bug, but if you try to plot an imported spectrum using `plotSpectrum` in `waveClass` this line

`if obj.spectrumType == 'JS'`

will throw an error because `waves.spectrumType = 'spectrumImport'`. A simple fix would be

`if strcmp(obj.spectrumType,'JS') == 1`

**Comment by kmruehl** [comment]
@saltynexus I'm unable to reproduce this error. I've run the RM3 example (attached) with the following wave settings:
```matlab
% Irregular Waves with imported spectrum
waves = waveClass('spectrumImport');        % Create the Wave Variable and Specify Type
waves.spectrumDataFile = 'spectrumData.mat';  %Name of User-Defined Spectrum File [:,2] = [f, Sf]
```
and was able to generate a plot of the imported wave spectrum using the `plotSpectrum` in the `userDefinedFunctions` post-processing script. 
``` matlab
waves.plotSpectrum();
```

![plotSpectrum](https://user-images.githubusercontent.com/4603379/93498833-7f8bab80-f8cf-11ea-994f-966e39a056ae.png)

**Comment by saltynexus** [comment]
If you put a break point in the function, then evaluate
```
obj.spectrumType == 'JS'
```
you should get the following error.
```
Matrix dimensions must agree.
```

You don't need WEC-Sim to prove this is an error. Type in
```
'apple' == 'banana'
```

The reason why you get a plot is because the plot is generated before occurs and you're using
```
    try 
        wrapper.waves.plotSpectrum();
        saveas(gcf,[Dir.fig_param_set,sep,'Wave_Spectrum'],'png');close(gcf);
    catch
    end
```
Take out the `try` `catch` statements and you should be able to reproduce the error. It's hiding the fact an error exists.

**Comment by kmruehl** [comment]
@saltynexus thanks for bringing this to our attention, the proposed solution has been added, and the warning should be removed.
