### ISSUE TITLE
How can I change the XLables in the BEMIO Plots

### ISSUE THREAD

**Issue by aglassFHKiel** [WEC-Sim/WEC-Sim#417]
![normalized_radiation_irf_surge](https://user-images.githubusercontent.com/71267766/94005120-1956cb00-fd9e-11ea-97a8-1992c49932a1.png)

How can i change the time in normalized radiation and normalized excitation irfs?

**Comment by aglassFHKiel** [comment]
up to 60 secounds

**Comment by dforbush2** [comment]
After BEMIO runs, click the plot you're interested in and type

`xlim([0 60]);`

However, the time over which the IRF is calculated is a user input to `Radiation_IRF` and `Excitation_IRF`, and the X-limit of the plots created should be inherited from this input.

For example, 60 second IRFs are calculated as:
```

hydro = Radiation_IRF(hydro,60,[],[],[],[]);
hydro = Excitation_IRF(hydro,60,[],[],[],[]);
```
Please see https://wec-sim.github.io/WEC-Sim/advanced_features.html#bemio

**Comment by aglassFHKiel** [comment]
perfekt, thanks
