### ISSUE TITLE
PTO: k, c, and linearDamping values

### ISSUE THREAD

**Issue by sugarl14** [WEC-Sim/WEC-Sim#421]
Hi,

I was wondering what you all did to determine the values for k, c, and linearDamping for the OSWEC following tutorials:

1) for the oswec wecSiminputfile:
pto(1).k = ?
pto(1).c = ?

and 
2) for the PTO-Sim example for the OSWEC
body(1).linearDamping(5,5)= ?

I also notices for the PTO-Sim example (OSWEC_Hydraulic_PTO), you all defined pto(1).k and pto(1).c to be zero. Why did you choose this?

My OWSC geometry is a little different in size so I need to calculate my own values for k, c, and linearDamping!

Thank you!

**Comment by dforbush2** [comment]
I'm answering this in #422 due to the duplicate issue.
