### ISSUE TITLE
OWSC Rotation Limit

### ISSUE THREAD

**Issue by sugarl14** [WEC-Sim/WEC-Sim#427]
Hi,

This issue is similar to issue #343  , but it is dealing with an OWSC.  Whenever I run a simulation on my OWSC geometry, the flap seems to rotate beyond the base structure (which, physically, is impossible). I have attached a picture of this below. Is it possible to model end stops in WEC-Sim so the flap will only rotate say + and - 45 degrees?

![image](https://user-images.githubusercontent.com/57150958/95989412-3d835600-0df8-11eb-80d8-be96f39009fa.png)

![image](https://user-images.githubusercontent.com/57150958/95989447-48d68180-0df8-11eb-86ed-a778533f32a5.png)

![image](https://user-images.githubusercontent.com/57150958/95989182-eed5bc00-0df7-11eb-8a8b-6bbfb529d96e.png)

**Comment by dforbush2** [comment]
Hi @sugarl14 

I think you should be able to do something similar to the solution proposed for #343 by specifying a user-prescribed force on your rotational PTO, you could also try the hard-stop Simscape blocks (external to the WEC-Sim distribution) suggested in #185.  

Additionally, later versions of MATLAB/Simulink have additional dialog options on constraint/PTO type blocks that allow the user to specify end stops a manner mathematically identical to that suggested in #343 but directly in the block dialog. For me in 2020a, for a translational PTO, you can access these parameters from the "Limits" drop-down, in the screen shot:

![image](https://user-images.githubusercontent.com/30122876/96053076-10589700-0e3c-11eb-851d-3c81447709e5.png)


However, these options are NOT available in older MATLAB versions (not sure exactly which, but roughly 2018a).

**Comment by sugarl14** [comment]
Great. Thank you for all the help!
