### ISSUE TITLE
Running wecSim in a parfor loop

### ISSUE THREAD

**Issue by eliesh17** [WEC-Sim/WEC-Sim#458]
Hi, I am trying to run wecSim in a parfor loop but keep getting transparency errors (which is expected considering the number of variables) 
I was wondering if there is a workaround for this. 

Thank you.

**Comment by yuyihsiang** [comment]
Please switch to the Dev branch and check the wecSimPCT.m file. We added a wecSimFcn.m file to call wecSim from a function to get around this issue.  If you are planning a series WEC-Sim run using MATALB parallel computing toolbox, you can use the run wecSimPCT.m instead of wecSimMCR.m, see the user manual. 
![Screen Shot 2020-11-18 at 4 29 52 PM](https://user-images.githubusercontent.com/4603391/99600765-55339880-29bb-11eb-94d9-03ab5040685b.png)

**Comment by eliesh17** [comment]
> 
> 
> Please switch to the Dev branch and check the wecSimPCT.m file. We added a wecSimFcn.m file to call wecSim from a function to get around this issue. If you are planning a series WEC-Sim run using MATALB parallel computing toolbox, you can use the run wecSimPCT.m instead of wecSimMCR.m, see the dev branch user manual (bottom left corner).
> 
> ![Screen Shot 2020-11-18 at 4 29 52 PM](https://user-images.githubusercontent.com/4603391/99600765-55339880-29bb-11eb-94d9-03ab5040685b.png)

Thank you for your reply!!

I'm gutting the following error when I run wecSimPCT: 

Error using wecSimPCT (line 100)
The source code (X:\...\wecSimPCT.m) for the parfor-loop
that is trying to execute on the worker could not be found.

Caused by:
    Undefined function 'hydroData' for input arguments of type 'double'.
    Error using remoteParallelFunction (line 84)
    Worker unable to find file.
        Undefined function 'hydroData' for input arguments of type 'double'.

If I set simu.reloadH5Data=1, then I get the following error: 

parfor imcr=1:length(mcr.cases(:,1))

Caused by:
    Error using wecSim (line 257)
    Variant control 'sv_b1_hydroBody' of variant block 'C6M/BA' must be a condition expression or name of a
    Simulink.Variant object in the global scope workspace of the model. Ensure that the condition does not
    match the model name.
    Error using wecSim (line 257)
    Variant control 'sv_b1_nonHydroBody' of variant block 'C6M/BA' must be a condition expression or name of
    a Simulink.Variant object in the global scope workspace of the model. Ensure that the condition does not
    match the model name.

**Comment by yuyihsiang** [comment]
We have tested using the RM3_MCROPT3 in the WEC-SIm Applications repository. If you have same issue when running the RM3_MCROPT3 using wecSImPCT.m, you may want to check two things

1. Which MATLAB version r u using?

2. Can you confirm your parallel setting?
![Screen Shot 2020-11-25 at 3 05 20 PM](https://user-images.githubusercontent.com/4603391/100286273-bdd8c300-2f2f-11eb-8d0a-47d9a86b9d22.png)
![Screen Shot 2020-11-25 at 3 05 32 PM](https://user-images.githubusercontent.com/4603391/100286276-c3360d80-2f2f-11eb-8fb0-d4ddee6800ae.png)

Note: simu.reloadH5Data=1 should not matter. The *.h5 hydrodynamic data is reload, regardless the setting for simu.reloadH5Data in the WEC-Sim input file.

**Comment by yuyihsiang** [comment]
Did it resolve your issue?
