### ISSUE TITLE
Error in reading AQWA generated h5 file

### ISSUE THREAD

**Issue by abhisheks865** [WEC-Sim/WEC-Sim#460]
Hi there,
When I am running the wecSim code after creating h5 file from AQWA, I am getting below error. 

![image](https://user-images.githubusercontent.com/71249618/99426231-774cee00-28c9-11eb-8996-d66860e74d2e.png)

I have checked my H5 file and it is of 8 MB so i think it has all the data required to proceed in wecSim. Can someone help me to resolve this error?

[ANALYSIS.zip](https://github.com/WEC-Sim/WEC-Sim/files/5555622/ANALYSIS.zip)

**Comment by sugarl14** [comment]
can you send a screenshot of the following things:

1) BEMIO script in matlab
2) first few lines of both .LIS and .AH1 files
3) output options in AQWA (Analysis Settings > Output File Options)

**Comment by abhisheks865** [comment]
@sugarl14 Thanks for responding to my query. I think I troubleshot this problem. wecSim command was showing an error because AQWA generated h5 file had only one body. I set up only one body while setting up my model in AQWA. I grouped floating and submerged bodies into two different bodies in AQWA and generated the h5 file again. That's how I was able to read h5 file in wecSim.
