### ISSUE TITLE
Error in postprocessing - ParaviewVisualization

### ISSUE THREAD

**Issue by Rodimus88** [WEC-Sim/WEC-Sim#468]
I got the following error when I try to create paraview file for wecsim example RM3 and OSWEC.

Undefined variable "hspressure" or class "hspressure".

Error in paraViewVisualization (line 53)
            body(ii).write_paraview_vtp(TimeBodyParav, PositionBodyParav, bodyname, simu.simMechanicsFile,
            datestr(simu.simulationDate), hspressure{ii}, wpressurenl{ii}, wpressurel{ii},
            simu.pathParaviewVideo,vtkbodiesii);

Error in wecSim (line 334)
paraViewVisualization

![Capture2](https://user-images.githubusercontent.com/69836354/100194407-a8599e00-2f1b-11eb-8437-40d7cc85197a.JPG)

**Comment by akeeste** [comment]
Hi @Rodimus88 

Thank you for bringing this bug to our attention. In a previous commit, the way that hspressure, wpressurenl, and wpressurel are passed internally in the post-processing functions was changed. These three references were not fully updated when creating Paraview output. 

I have created a pull request (#472) to fix these references to the cell pressures. It will soon be reviewed by another member of the WEC-Sim team and merged with master to fix this issue. Please let me know if the same problems occurs after this update.

Adam

**Comment by Rodimus88** [comment]
Hi @akeeste 

thank you for the attention given, So i just need to update my wec-sim directory to avoid this error. I will inform if any error occurs afterwards.
