### ISSUE TITLE
Error while using WECCCOMP_Fault_Implementation

### ISSUE THREAD

**Issue by BinoBK** [WEC-Sim/WEC-Sim#498]
Hi all,
I am facing an issue while running WECCCOMP_Fault_Implementation case. Following is the error that I am getting:

![image](https://user-images.githubusercontent.com/77161641/104851529-87119e80-591b-11eb-9c5e-25951d39b6f1.png)

I am using Matlab R2002b and latest WEC-Sim. Kindly extend help. 

**Also, Is it possible to share the WEC-Sim model that was shared for the competition "A competition for WEC Control Systems" in 2017.** 

Thanks,
Bino

**Comment by BinoBK** [comment]
Thanks to the solution provided in #497 , after adding body(1).cg=[0 0 0], I was able resolve the above mentioned error. 

**As requested above, Is it possible to share the WEC-Sim model that was shared for the competition "A competition for WEC Control Systems" in 2017.**

**Comment by nathanmtom** [comment]
@BinoBK Thank you for this notification, we will need to update the WECCCOMP files in the WEC-Sim Application Repository. 

Please see the following repository that holds the WEC-Sim Model used during WECCCOMP

https://github.com/WEC-Sim/WECCCOMP

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by BinoBK** [comment]
Thank you @nathanmtom
