### ISSUE TITLE
Degrees of Freedom Question

### ISSUE THREAD

**Issue by ahagmuller** [WEC-Sim/WEC-Sim#50]
It looks like the default blocks that WEC-SIM uses to constrain motions, do so in a 2D plane for degrees of freedom in Heave Surge and Pitch. It looks like the outputs have 6DOF available, is it possible to model a device in all 6DOF in WEC-SIM?  We use NEMOH as the BEM solver with 6DOF as well.
Thanks,
Alex

**Comment by cmichelen** [comment]
See #52
