### ISSUE TITLE
FFT feature in WEC-Sim Free decay test

### ISSUE THREAD

**Issue by BinoBK** [WEC-Sim/WEC-Sim#500]
Hi all,
I want to perform Fast Fourier Transformation of Free decay test results in order to find out the Natural frequency of the system (ie. The Float along with associated mechanism but excluding the PTO). 

**Is FFT feature in-built in WEC-Sim?** 

Thanks,
Bino

**Comment by nathanmtom** [comment]
@BinoBK  Thank you for your question about a WEC-Sim FFT function. WEC-Sim currently doesn't have a built in function to call to perform and FFT on a given time signal of interest; however, MATLAB has the base `fft` function with examples [here](https://www.mathworks.com/help/matlab/ref/fft.html) to help you build your own FFT script.

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by BinoBK** [comment]
Thanks a lot @nathanmtom

**Comment by kmruehl** [comment]
I opened an issue on the MHKiT repo to request this feature.
