### ISSUE TITLE
output/pto/powerInternalMechanics ???

### ISSUE THREAD

**Issue by aglassFHKiel** [WEC-Sim/WEC-Sim#510]
Can anybody explane what kind of Mechanical Power "powerInternalMechanics" is?

Is this the mechanical power input for the PTO-System e.g. for PTO-Sim?

best regards
Andreas

**Comment by yuyihsiang** [comment]
It is just the force multiplied by the velocity. Since it indicates absorbing power by the joint, it is negative given based on the coordinate system.

**Comment by kmruehl** [comment]
@aglassFHKiel did this answer your question?

**Comment by aglassFHKiel** [comment]
Is it the **forceTotal** multiplied by the velocity?

**Comment by kmruehl** [comment]
pto.powerInternalMechanics = pto.forceInternalMechanics*pto.c

**Comment by aglassFHKiel** [comment]
Thank you Kelley,

i suppose that pto.c is the relative velocity between float and spar,
further is pto.forceInternalMechanics the force between float and spar.

But where can I find information about InternalMechanics? 
How is the equation of pto.forceInternalMechanics?

best regards
Andreas

**Comment by kmruehl** [comment]
@aglassFHKiel my apologies, I responded to this post too quickly and I provided you incorrect information. 

`output.ptos.powerInternalMechanics = output.ptos.forceInternalMechanics.*output.ptos.velocity`

- `output.ptos.forceInternalMechanics` is the pto force between float and spar.
- `output.ptos.velocity` is the relative velocity between float and spar
- `pto.c` is the pto damping between the float and the spar

**Comment by kmruehl** [comment]
@aglassFHKiel did this resolve your issue?

**Comment by aglassFHKiel** [comment]
Hi Kelley, thanks for your support. Yes this resolved the issue.

best regards
Andreas
