### ISSUE TITLE
Specifying damping in MCR option 2?

### ISSUE THREAD

**Issue by sugarl14** [WEC-Sim/WEC-Sim#528]
Hi!

I have created an excel file that contains a JPD plot of wave height, period, and freqency of occurrence. (Similar to what is spoken at 11:30 of this video https://www.youtube.com/watch?v=C9R_mGNI5yA).

I was wondering if there was a way that I could also specify my optimum  `pto.c` values for each wave period in this excel file? 
i.e., when `T= 1.5`, I want `pto.c= 6000`. Or  when `T= 8.5` I want `pto.c = 20000`. (Also, I'm just using arbitrary numbers for `pto.c` here)

Here's a screenshot of what I have / what I'm trying to do:

![image](https://user-images.githubusercontent.com/57150958/110020707-dfe49d00-7cf7-11eb-90ef-a2953aa6c794.png)

thanks!!

**Comment by sugarl14** [comment]
On second thought, couldn't I just use MCR option 3 and create a .mat file that looks something like this?

![image](https://user-images.githubusercontent.com/57150958/110023025-a6f9f780-7cfa-11eb-8590-d84a8dd0e528.png)

**Comment by yuyihsiang** [comment]
Yes, that is the best way to do it.

—Yi-Hsiang

**Comment by hossein-mehdipour** [comment]
Hello @sugarl14 , excuse for bothering you, I had a question about this issue & I was wondering if you could help me
I was wondering when you use option 3, you no longer can specify percentage of occurrence of any sea states. Doesn't this influence the results of your simulations? Or its effects negligible? 
Or you just repeat the rows concerning sea states that occur multiple times?

**Comment by sugarl14** [comment]
Hey @hossein-mehdipour, great question. I'll do my best to answer but I'd like to have a WEC-Sim expert verify any answer I give. So take what I say with a grain of salt :)

Option 3, as far as I am aware, only accounts for `waves.H`,  `waves.T`, `pto.c`,  and `pto.k`, so you are correct that option 3 doesn't include the percentage of sea state occurrence. 

Here's what I did for my work (which may or may not be the preferred method) -- 
I used MCR option 3 and to obtain the mechanical power into the PTO for all the seas states being considered. Then I took these values and multiplied them by the percentage of sea state occurrence to obtain my power contribution matrices. 

For example,

Let's say we have `waves.H = 1.5`, `waves.T = 5.5`, `pto.c = 20000`, and 'pto.k= 0`. After running this simulation let's just guess that the average mechanical power into the PTO is something like 5,000 Watts.  But lets say that specific sea state only  occurs 3% of the time , over a 1 year span. We can do 5,000W * 0.03 to get 150W. So this sea state will contribute 150 W of power over a span of 1 year. 

I hope this helps you in some way. Don't hesitate if you have any more questions! I'll be happy to do my best to answer. But again, I recommend having a WEC-Sim guru to double check.

Thanks,

Landon

**Comment by hossein-mehdipour** [comment]
@sugarl14 Thank you so much for taking the time to answer, it was an interesting approach that I think makes sense. I'm going to double-check it just in case.
And I assume "Power Contribution Matrices" and "Power Matrices" are not same thing (according to description you just mentioned). Am I right?
Hello @yuyihsiang, I was kindly wondering if you could check the comment above to see if there's anything we are missing.
