### ISSUE TITLE
AQWA Data

### ISSUE THREAD

**Issue by ratanakso** [WEC-Sim/WEC-Sim#54]
Hello,

I was wondering if I need both LIS and AH1 files or just LIS file to run bemio. Also, if I have an IGS, do you know what tool should I use to get a STL for the geometry.

Regards,
Nak

**Comment by kmruehl** [comment]
Nak, 

It looks like you already resolved this issue, but for future users to reference I'm also going to respond here.  

- To run BEMIO for AQWA, you need both the *.LIS and the *.AH1 files.

- For the *.STL geometry file, I use SolidWorks, but most CAD programs should be able to save an *.IGS file as an *.STL.

-Kelley
