### ISSUE TITLE
How to use Read_NEMOH?

### ISSUE THREAD

**Issue by strvalik** [WEC-Sim/WEC-Sim#540]
Hi all, I am confused with this relatively simple issue.

Read_Nemoh(hydro,filedir)

I have a NEMOH working file directory, but I cannot figure out what to put for the hydro input.

Could anyone help?

**Comment by dav-og** [comment]
Hi @strvalik,
You just need to initialize a MATLAB structure array and then pass that as the 'hydro' argument in Read_NEMOH():

`hydro = struct();`
`hydro = Read_NEMOH(hydro,'..\RM3\');`

For a working example, see: https://github.com/WEC-Sim/WEC-Sim/blob/master/examples/BEMIO/NEMOH/RM3/bemio.m

**Comment by strvalik** [comment]
Great! Thank you for getting back to me so quickly!

The documentation is useful as well.
