### ISSUE TITLE
Modifying OSWEC with floating connection

### ISSUE THREAD

**Issue by krisRaj** [WEC-Sim/WEC-Sim#55]
Hello All,

I just began using WEC Sim last week and have a question on setting up the simulink file for OSWEC like wec. The wec I am working on is similar to OSWEC meaning it has a rotational PTO, but the fixed part (base) is now freely floating.  Thus in the new/modified  wec the Global Reference Frame is connected to the  base with a floating constraint. What should be the constraint.loc values? Should it be [0 0 0] or the bottom most part of the base (which is floating now).

Also when wec-sim outputs the pitch motions, is it in radians or degrees?

Thank you

Kumar

**Comment by cmichelen** [comment]
Hi Kumar,

The location of the floating constraint does not affect the dynamics of the system. In general, the location of constraints only affect your dynamics for rotational constraints. For the  rest of the constraints the only difference is in the constraint moments.

Pitch motion is in radians.

- Carlos
