### ISSUE TITLE
OSWEC Viscous Drag force

### ISSUE THREAD

**Issue by timmaflanagan** [WEC-Sim/WEC-Sim#551]
Hello! I am trying to calculate the power losses on the tutorial OSWEC due to drag. 

The equation I am trying to solve for is the following:
F_v = 1/2 rho C_d A (v_b - V_w) | (v_b - V_w)|
C_d = drag coefficient
A = projected area 
v_b = velocity of the body
V_w = velocity of the wave.

I would like to determine what the relative velocity (v_b-v_w) is between the body and the wave if possible. I understand that this relative velocity can be found from output.ptos.velocity( : , 5). Is this the velocity I am looking for?  

Right now, I am running MCR conditions for regular waves with:
H: 0.75:0.5:9.25
T: 4.5:0.5:12.5
I am using viscDrag.cd and viscDrag.characteristicArea
Further I am calculating a range of PTO values: 1e7:1:7e7

Would I need to calculate the relative velocity for each input condition? will the relative velocity of each input condition be different?

**Comment by jleonqu** [comment]
Hi @timmaflanagan 

output.ptos.velocity( : , 5) is the angular velocity in the OSWEC, not the linear velocity.

Please check the Advance Features section on the WEC-Sim webpage for more information about drag forces and viscous damping: https://wec-sim.github.io/WEC-Sim/man/advanced_features.html#viscous-damping

Best,

Jorge Leon

**Comment by timmaflanagan** [comment]
Thanks Jorge!!

**Comment by jleonqu** [comment]
Hello @timmaflanagan 

Please consider the use of Morison Elements for your simulation, you can find the theory for this topic here: https://wec-sim.github.io/WEC-Sim/man/theory.html#morison-elements

A brief description of the implementation can be found here: https://wec-sim.github.io/WEC-Sim/man/advanced_features.html#viscous-damping-and-morison-elements

In the WEC-Sim Applications repo you can find an example of the use of the Morison Elements: https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/Free_Decay/1m-ME

Let us know if this information helps to solve your issue.

**Comment by nathanmtom** [comment]
@timmaflanagan 

Did @jleonqu additional information answer any remaining questions you had? If so could you please close this issue.

Thank you in advance.

Cheers, 
Nathan
National Renewable Energy Laboratory
