### ISSUE TITLE
Paraview visualization 

### ISSUE THREAD

**Issue by SofiasKonstantinos** [WEC-Sim/WEC-Sim#552]
![image](https://user-images.githubusercontent.com/75040477/113281539-5b813c00-92ee-11eb-8265-f0c74feb72d9.png)
I am using the example from the wecsim application master for paraview , but get these errors when trying to activate the pressure glyphs . Any idea?

**Comment by akeeste** [comment]
Hi @SofiasKonstantinos 

Thanks for bringing this up. It seems this is the same bug currently described in issue #459 . We believe the latest versions of Paraview are incompatible with our older output scripts for the pressure glyphs which need to be updated. We hoping to have a fix for this before the next WEC-Sim version is released.

What Paraview version are you using? It seems this issue started around Paraview v5.8 or v5.9.

Also, issue #459 has a lengthy workaround that you might be able to implement in the meantime.

Adam
