### ISSUE TITLE
how to define initial pitch angle for free decay test?

### ISSUE THREAD

**Issue by siya-jin** [WEC-Sim/WEC-Sim#563]
Dear there,

I am trying to simulate a free decay test, setting the body with initial a pitch angle.
But the command of body(1).initDisp.initLinDisp = [ X Y Z], only offers the set for X Y and Z initial displacement. 
May i ask if i miss any command to control the initial angle setting for Roll, Pitch and Yaw, please?

Thanks!

**Comment by siya-jin** [comment]
Dear there,

Sorry for the disturb. I thought i found the command of:
initDisp          = struct(...                                          % Structure defining the initial displacement
            'initLinDisp',          [0 0 0], ...             % Initial displacement of center fo gravity - used for decay tests (format: [displacment in m], default = [0 0 0])
            'initAngularDispAxis',  [0 1 0], ...             % Initial displacement of cog - axis of rotation - used for decay tests (format: [x y z], default = [1 0 0])
            'initAngularDispAngle', 0)  

to be used. 
Thanks!

**Comment by akeeste** [comment]
Hi @siya-jin,

Yes you can use the initDisp structure to define an initial displacement of the device. You can set these values directly, or use the setInitDisp() method. This [method ](https://wec-sim.github.io/WEC-Sim/man/api.html#objects.ptoClass.setInitDisp) rotates a body about a specific axis and point, resulting in both rotation of the body and the corresponding translational displacement due to the rotation of the center of gravity about some arbitrary point.

**Comment by siya-jin** [comment]
Hi Adam,

Really thanks for your help.

Best wishes
Siya
________________________________
发件人: Adam Keester ***@***.***>
发送时间: 2021年4月23日 15:54
收件人: WEC-Sim/WEC-Sim ***@***.***>
抄送: Siya Jin ***@***.***>; Mention ***@***.***>
主题: Re: [WEC-Sim/WEC-Sim] how to define initial pitch angle for free decay test? (#563)


Hi @siya-jin<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsiya-jin&data=04%7C01%7Csiya.jin%40plymouth.ac.uk%7Cfe441995ab6441d7499f08d90667b225%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637547864702962129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N%2FMuY331HRRxPVZWl%2Bn%2FPIp8HE%2BnVwHEr7%2BXdvvRjsA%3D&reserved=0>,

Yes you can use the initDisp structure to define an initial displacement of the device. You can set these values directly, or use the setInitDisp() method. This method <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwec-sim.github.io%2FWEC-Sim%2Fman%2Fapi.html%23objects.ptoClass.setInitDisp&data=04%7C01%7Csiya.jin%40plymouth.ac.uk%7Cfe441995ab6441d7499f08d90667b225%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637547864702972125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UE3KNkRVASTuNtOdKt4bJXFXMHa0UmfvPZmlK4btcKk%3D&reserved=0> rotates a body about a specific axis and point, resulting in both rotation of the body and the corresponding translational displacement due to the rotation of the center of gravity about some arbitrary point.

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWEC-Sim%2FWEC-Sim%2Fissues%2F563%23issuecomment-825714288&data=04%7C01%7Csiya.jin%40plymouth.ac.uk%7Cfe441995ab6441d7499f08d90667b225%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637547864702972125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oZhc3pOb5ImTTA5r%2Bqxrarp1XjPkWbXtN7ZN1WeIDrA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMMBOOQPCFKVL7JJ4GKHBULTKGC2FANCNFSM43OIWFMA&data=04%7C01%7Csiya.jin%40plymouth.ac.uk%7Cfe441995ab6441d7499f08d90667b225%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637547864702982117%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0mrM2Y1JDUPqH40AznKlbIavsLYH48GKzwk0K5n%2B8CE%3D&reserved=0>.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
