### ISSUE TITLE
The problem of running large Simulation Time-Step about WECCCOMP GitHub repository 

### ISSUE THREAD

**Issue by Doudou-Li** [WEC-Sim/WEC-Sim#582]
Hello,

I'd like to set a large simulation time-step in WEC-SIM. For example trying to choose over 0.1s so as to reduce the sampling points in a sampling period..
The WECCCOMP GitHub repository defaults  simulation solver to be ode4, and simulation time-step equals to 0.001s.

1. There is a problem for running the simulation as following when I try to set simulation time-step 0.12s and simulation solver still ode4.
![QQ图片20210509162742](https://user-images.githubusercontent.com/63373273/117578100-9728d600-b0e4-11eb-8710-6398a4440856.png)

But when I change simulation time-step 0.16s and remain simulation solver ode4. The new problem shows to me, as below:
![QQ图片20210509164655](https://user-images.githubusercontent.com/63373273/117578424-35696b80-b0e6-11eb-830f-bdee19d22039.png)

2. So I decide to choose the variable step-size solver ode45.  The WaveStar modelling could work on simulation time-step over 0.12s. 
However it always shows me a strange error as below:

Unrecognized function or variable 'power_eff'.

Error in userDefinedFunctions (line 40)
plot(time,power,time,power_eff)

Error in wecSim (line 302)
    userDefinedFunctions;

Could you help me to solve the above problems?

DD

**Comment by nathanmtom** [comment]
@Doudou-Li Thank you for your question and will do my best to answer your question. 

The WECCCOMP model was built to satisfy the constraints of the experimental test apparatus system. The variable `xPcTs` in the `controller_init.m` is the time step set that was used during WECCCOMP experimental testing and competitors were restricted to this time step. This time step is defined in the filters found in the `WECCCOMP Controller` Simulink block highlighted below. Therefore if you run the simulation with a different time step than defined by `xPcTs` the output from this block can generate large responses that may crash the simulation. If you change the `xPcTs` to be the same time step as the WEC-Sim simulation you may be able to run with a longer time step. However, these filters were developed by our collaborators at the University of Aalborg and we will not be able to provide on turning the response. 

![image](https://user-images.githubusercontent.com/7635064/117605069-1e417280-b114-11eb-8ed5-2ca14d52f037.png)

Please let me know if this has answered your question or if you need any clarification. 

Cheers, 
Nathan 
National Renewable Energy Laboratory

**Comment by Doudou-Li** [comment]
Thank you.
I think it may not be right to set a very large simulation time-step in it, which the PTO block is not allowed to work.

DD

**Comment by nathanmtom** [comment]
@Doudou-Li Appreciate your response, do you still have questions about the WECCCOMP example? If not, then could you please close this issue.

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by Doudou-Li** [comment]
Yes, I have closed the issue.


Thank you

DD

________________________________
