### ISSUE TITLE
WEC-Sim with power electronics - simulation problem

### ISSUE THREAD

**Issue by rodrijardim** [WEC-Sim/WEC-Sim#583]
Hello everyone,

I started to study the RM3_c hydraulic model provided by the WEC-sim team and I need to analyze the electricity production in different sea conditions. In the first phase, I need to synchronize the WEC generator with the mains without the existence of a DC link and converter.

In order to have the parameters of interest (voltage magnitude, frequency, angle, etc.), I had to add a permanent magnet synchronous machine block to the RM3 and analyze the results according to the mechanical torque generated (genTorque) by the hydraulic motor.

https://imgur.com/r0Vf3D2

The "genTorque" output of the "Rotary Generator Lookup Table" block was connected to the "Tm" input (Mechanical torque) of the "Permanent Magnet Synchronous Machine" block of Simulink. From the data provided by the PMSM, I can detect when the frequency, magnitude and angle of the phases are practically the same as those of the grid to connect the generator (RM3) to the power grid.

The files "ptoSimInputFile" and "wecSim" were not changed and the only changes I made were to the file "wecSimInputFile.m". These changes were as follows: simu.mode = 'accelerator', simu.solver = 'ode45', simu.ssCalc = 1;
As in problem # 419, I need to have a very low time interval (for example 0.001s) and this creates arrays with millions of data for a simulation time of 400s. As you can imagine, the simulation runs for a long time until the computer crashes.

What can I change in the file / block settings to be able to simulate?

**Comment by jleonqu** [comment]
Hello @rodrijardim 

In an effort to better understand the needs and concerns of the user’s community, the WEC-Sim team have developed some templates for submitting issues. To find the templates please go first to the Issues tab, and then go to New Issue.

![image](https://user-images.githubusercontent.com/72461917/118880705-64829880-b8af-11eb-9ce4-972459b7e26f.png)

There are four options to choose from: Bug report, Feature request, Theory or implementation clarification, and WEC-Sim applications specific issue or question.

![image](https://user-images.githubusercontent.com/72461917/118880789-82e89400-b8af-11eb-8b81-ea31d0bd2125.png)

We kindly suggest to re submit your issue using one of these templates. As a development team it is extremely useful for us to classify the issues in these categories. We hope that in the short and long term this will be beneficial not just for us as developers but also for the users and the WEC-Sim community in general.
