### ISSUE TITLE
Hydrostatic stiffness bug

### ISSUE THREAD

**Issue by cmichelen** [WEC-Sim/WEC-Sim#59]
WEC-Sim currently assumes that the hydrostatic stiffness matrix has values only on one side of the diagonal. This is true for WAMIT but not for AQWA (not sure about NEMOH). We should change it so that BEMIO outputs the entire matrices for all cases. 

in bodyClass/hydroForcePre:
```matlab
k = obj.hydroData.hydro_coeffs.linear_restoring_stiffness;
obj.hydroForce.linearHydroRestCoef =  (k + k' - diag(diag(k))).*rho .*g;
```

should be: 
```matlab
k = obj.hydroData.hydro_coeffs.linear_restoring_stiffness;
obj.hydroForce.linearHydroRestCoef =  k.*rho .*g;
```
I will make this change after BEMIO has been modified.

**Comment by ratanakso** [comment]
Carlos,

I was able to use pip for matplotlib, progressbar2 and astropy, but I can't
use pip with numpy scipy and h5py. Any suggestions?

Thanks,
Nak

**Comment by cmichelen** [comment]
Checked: WAMIT is the only one that outputs half the matrix. For NEMOH and AQWA BEMIO outputs the whole matrix.

Changed BEMIO wamit.py as follows (added lines 165-166,172-173):
![screen shot 2015-11-05 at 9 48 41 am](https://cloud.githubusercontent.com/assets/5296181/10975407/00a60ce8-83a4-11e5-8261-1041567df963.png)

Will push BEMIO and bodyClass changes soon. Need to create new h5 files for all the tutorials/verification cases.
