### ISSUE TITLE
[Theory or Implementation]: FYI Advice for Capytaine axisymmetric mesh creation

### ISSUE THREAD

**Issue by dforbush2** [WEC-Sim/WEC-Sim#592]
I’ve been wrestling with a Capytaine issue the last couple of days and just now found a solution.

If one wants to create an axisymmetric mesh, Capytaine has a great tool you can use: body.AxialSymmetricMesh.from_profile([N x 3 list of points], [number of angular discretizations]).
But what doesn’t seem to be documented is that those points need to be piece-wise continuous for it to produce a mesh that give useful results (in retrospect this is obvious, but isn’t immediately apparent looking at visualized meshes.) For my example, I wanted to create a hollow cylinder like so:

![image](https://user-images.githubusercontent.com/30122876/119560365-16630e80-bd61-11eb-8ca8-567ec801895c.png)
  
where the plane is the free-surface.

Initially, I had defined the profile points to be rotated like so:
Cylinder Top
Outer Cylinder Wall (top down)
Cylinder Bottom
Inner Cylinder Wall (top down)

Which is convenient from a point definition perspective, but the problem is that if you plot the Y-coordinates of this order

![image](https://user-images.githubusercontent.com/30122876/119567257-57f7b780-bd69-11eb-8f29-6428b0ec1c8c.png)

It is not continuous. However, the axisymmetric mesh routine will mesh across this discontinuity. The problematic panels are the long diagonals only clearly visible in a wireframe view.

![image](https://user-images.githubusercontent.com/30122876/119567424-8aa1b000-bd69-11eb-9e06-51f4579616ce.png)

Capytaine may still run with these panels, but it is unlikely to generate accurate BEM estimates. 

The problem is solved by flipping the order of the inner cylinder wall
Cylinder Top
Outer Cylinder Wall (top down)
Cylinder Bottom
Inner Cylinder Wall (bottom up)

![image](https://user-images.githubusercontent.com/30122876/119567931-27644d80-bd6a-11eb-83af-00f0a4920a70.png)

Posted here so that we may reference in response to future related issues.

**Comment by kmruehl** [comment]
@dforbush2 should we close this?
