### ISSUE TITLE
[WEC-Sim Applications] parameters in the ptoSimInputFile.m

### ISSUE THREAD

**Issue by hossein-mehdipour** [WEC-Sim/WEC-Sim#602]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
PTO-Sim

**Describe the bug or issue**
I have afew questions about the parameters in the `ptoSimInputFile.m` in the` $WEC-Sim_Applications-master\PTO-Sim\OSWEC\OSWEC_Hydraulic_PTO`, I wanted to ask what are they? I've listed them below, If you could help understand what they are.

%% High Pressure Accumulator
```
ptosim.accumulator(1).del_p_r
ptosim.accumulator(1).VIeq
ptosim.accumulator(1).VImax
```

%% Lookup Table Generator
```
ptosim.rotaryGenerator.TgenBase
ptosim.rotaryGenerator.omegaBase
```

%% Rotary to Linear Crank
```
ptosim.motionMechanism.crank
ptosim.motionMechanism.offset
ptosim.motionMechanism.rodLength
```
(and if you don't mind explaining what is the difference between Crank & Rod?)

Also, I can't seem to find the "Hydraulic Motor Displacement" Value anywhere in the `ptoSimInputFile.m`.

**To Reproduce**
N/A

**Expected behavior**
N/A
**Screenshots**
N/A

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 7]
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2021a]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v4.2]

**Additional context**
N/A

**Comment by jleonqu** [comment]
Hello @hossein-mehdipour 

The variables that you mentioned are:

%% High Pressure Accumulator
ptosim.accumulator(1).del_p_r : it's the maximum pressure difference between the high pressure accumulator and the low pressure accumulator
ptosim.accumulator(1).VIeq : it's the initial volume of the high pressure accumulator when it is connected to the hydraulic system. It is different to ptosim.accumulator(1).VI0 which is the initial volume with no charge.
ptosim.accumulator(1).VImax : it's the volume of the accumulator when the pressure reach the maximum volume.

%% Lookup Table Generator
ptosim.rotaryGenerator.TgenBase : it's the rated torque of the electric generator. It is used in the lookup table as part of the input. The torque in the motorEff.mat file goes from -1.56 x ptosim.rotaryGenerator.TgenBase to 1.56 x ptosim.rotaryGenerator.TgenBase
ptosim.rotaryGenerator.omegaBase : it's the rated angular velocity of the electric generator. It is used in the lookup table as part of the input. The angular velocity in the motorEff.mat file goes from 0.004 x ptosim.rotaryGenerator.omegaBase to 4 x ptosim.rotaryGenerator.omegaBase.

%% Rotary to Linear Crank
Please look at this [link](http://wec-sim.github.io/WEC-Sim/man/advanced_features.html#tutorial-oswec-with-pto-sim) to solve your questions about the OSWEC example with the rotary to linear crank mechanism.

%%Hydraulic Motor Displacement
You need to use the file variableMotorVolume.m to change the value of the motor displacement. This file calculates the displacement as a function of delta pressure.

**Comment by jleonqu** [comment]
Hello @hossein-mehdipour 

Does this answer your question?

**Comment by hossein-mehdipour** [comment]
Sorry for my delayed response @jleonqu,
I read multiple papers about HPTO and its parameters, and I noticed that in almost every paper there is a value for hydraulic motor displacement as an independent value, except in this paper ([this](https://lib.ugent.be/catalog/rug01:002494968)) which uses a WEC-Sim (I know this research is not under the Official WEC-Sim development team) and instead of getting "motor displacement" as an input, it represent the value in combination with "the swashplate angle ratio" (α) based on delta-pressure (just as in WEC-Sim), as in other papers, the motor displacement is presented like other parameters like Piston Area and HPA & LPA Volumes and ... . Can you elaborate on this topic please?

And I have a question which i hope is not too off-topic here:
I was to trying to figure out the range of HPTO parameters (especially Piston Area and HPA & LPA Volume and pre-charge pressure), and I found really wide range of used parameters in different study,
for example the value for HPA Volume goes as low as 0.01 L (which I assume is for a test of some sort), and goes as high 9000 L in another study (which is almost about the same as WEC-Sim's default value), and in an study [that used the actual data from a manufacturers for HPTO components](https://www.mdpi.com/1996-1073/14/1/79), this value was ranged 0.2 to 57 L. To be honest I am kind of confused about this ranges, I wondered if you could help me with this problem as well.

**Comment by hossein-mehdipour** [comment]
I had another question I wanted to ask,
I was checking the equations in the `ptoSimInputFile.m` and I was trying to change the HPA's pre-charge pressure, but according to the equations, this value is not independent, and is dependent on LPA's Volume and pre-charge pressure. Am I right?
I'm asking because I saw in [an study](https://www.mdpi.com/1996-1073/14/1/79) (this is the same study as in my previous comment) that they optimized the value of these 3 parameters simultaneously. Does PTO-Sim operates differently from other HPTO simulators or I'm missing something here?

**Comment by jleonqu** [comment]
Hello @hossein-mehdipour 

The definition of the hydraulic displacement depends on the specific needs of the simulation that the user wants to perform, that is why you can see so many different ways to define the displacement. This also depends on the kind of device that the user wants to simulate, it could be any kind of hydraulic motor such as a gear motor, a vane motor, a piston motor, etc. Every motor would have a different way to define its displacement. You can also find some studies where the displacement is assumed as constant. For the OSWEC example in the WEC-Sim applications repo, you can use the file variableMotorVolume.m to define your own way to calculate the motor displacement.

For the range of the HPTO parameters, that depends again on the specific characteristics of the case. I would suggest to define the mechanical power from the input, and then you can estimate the sizes of the hydraulic devices to handle that mechanical power.

For your last three questions:
1.	No, it doesn’t operate different. The definition of the pre charge pressure depends on the kind of accumulator. For the OSWEC example in the WEC-Sim applications repo, the accumulator is a gas accumulator. You could have a spring loaded accumulator and then the definition of the variables would be different.
2.	That depends on the definition that the author gives to the variables of the system.
3.	No, that is not possible. I would suggest to review the way you are calculating the mean generated power.

**Comment by hossein-mehdipour** [comment]
Thank you for your helpful answers @jleonqu,
1. So in the OSWEC example in the WEC-Sim applications repo, the HPA's pre-charge pressure is not an independent parameter?

3.I'm using `mean(output.ptosim.pistonNCF.absPower)` and `mean(output.ptosim.rotaryGenerator.genPower)`, I also tried `sum(output.ptosim.pistonNCF.absPower)` and `sum(output.ptosim.rotaryGenerator.genPower)`. Am I doing something wrong?

**Comment by jleonqu** [comment]
Hi @hossein-mehdipour 

1. In the OSWEC example, the precharge of the low pressure accumulator is a function of the rated working pressure. For the high pressure accumulator, the precharge is defined as a function of the parameters of the accumulators such as the initial volume and the precharge of the high pressure accumulator,

3. I double check the examples in the WEC-Sim applications repo and the value of mean(output.ptosim.rotaryGenerator.genPower) is less than the value of mean(output.ptosim.pistonNCF.absPower). If you change the original parameters, I would suggest to double check the other variables of the system such as the force in the piston, the velocity of the piston, the torque in the generator and the shaft speed of the generator, these are the variables used to calculate the power in the piston and the power in the generator.

**Comment by hossein-mehdipour** [comment]
Hi @jleonqu 
1. Thank you for your response.
3. I found out what my mistake was, I had changed the solver from "ode4" (WEC-Sim's default solver) to "ode45" (I can't recall why exactly, but It must have been because ode4 runs resulted in some errors and I had to change that). My initial assumption was that changing the solver will probably change the accuracy and speed of the run (and not drastically change the result), now that I compare two sets of runs using "ode4" & "ode45" with the same inputs, I can see that the results are almost the same, except for the mean absorbed power value in the cases that absorbed power was less than generated power (which is almost 2/3 of the value using "ode4"). I was curious if you know why is this problem happening.

But now that I have changed the solver, In some cases I have "Negative Piston Pressure Values". Is this possible?

You also mentioned afew parameters that I was unable to find in the WEC-Sim Outputs. I was wondering if you could help me find these parameters (in the workspace I assume):
Velocity of the Piston (is this equal to the Velocity of the Spar?)
the Torque in the Generator?
the Shaft Speed of the Generator (is this equal to Motor Speed?)

4. What is the unit for Motor Displacement in WEC-Sim? "m3/rad" or "m3/rev"?

**Comment by jleonqu** [comment]
Hi @hossein-mehdipour 

I run the simulation with both solvers and I had the same results. Are you changing the maximum time step? Please check this link for more information about solvers in wecSim: [Time Step Features](https://wec-sim.github.io/WEC-Sim/man/advanced_features.html#time-step-features)

You can find the variables here:

- Piston Velocity: the piston Velocity is not saved in the outputs, but you can save this variable in your own model. The piston Velocity is the output "linearVel" of the block "Rotary to Linear Adjustable Rod". Even though this variable is not saved in the output, it is used to calculate the absPower in the piston.
- Torque in the Generator: the torque in the generator is not saved in the outputs, but you can save this variable in your own model. You can find this variable in the output of the block Rotary Generator Lookup Table
- Shaft speed of the generator: it is equal to the motor speed.

4. The units for the Motor Displacement in the OSWEC example are "m3/rad"
The swashplate angle ratio is a characteristic of variable displacement hydraulic piston/motors. In the OSWEC example, the angle ratio is not used because the displacement is a function of the pressure.

**Comment by hossein-mehdipour** [comment]
Hello @jleonqu ,
First I wanted to thank you for the further information you provided regarding determination of the said outputs, and for the question about the hydraulic motor.

About the other problem, I'm currently working on the RM3 example, so I will give 1 example concerning RM3.
In the `$WEC-Sim_Applications-master\PTO-Sim\RM3\RM3_Hydraulic_PTO` example, just change the values of the following parameters:
 in the `ptoSimInputFile.m`
 `ptosim.pistonNCF.topA` & `ptosim.pistonNCF.botA` to 0.18, 
`ptosim.accumulator(1).VI0` & `ptosim.accumulator(2).VI0` to 2,
and in the `wecSimInputFile.m` change the `simu.solver` to 'ode45'.

After the run, compare the values of `mean(output.ptosim.pistonNCF.absPower)` & `mean(output.ptosim.rotaryGenerator.genPower)`. 

You should be able to see what I'm referring to.

**Comment by jleonqu** [comment]
Hello @hossein-mehdipour 

I used the same values that you used and I am having the same problem: the value of mean(output.ptosim.pistonNCF.absPower) is less than the value of mean(output.ptosim.rotaryGenerator.genPower). I compared the energy in the piston and the energy in the generator by taking the integral of the power in the piston and the power in the generator. The results are consistent: the energy in the piston is greater than the energy in the generator.
The values of mean(output.ptosim.pistonNCF.absPower) and mean(output.ptosim.rotaryGenerator.genPower) are affected by the high frequency behavior that you can see in the piston pressure and piston force, which depends on the parameters that you are using for the hydraulic PTO in your simulation. The values that you are using for the accumulator volume are too low compared with the original values of the example, you should adjust your hydraulic system to compensate for the low accumulator volumes and therefore avoid the high frequency behavior.

**Comment by hossein-mehdipour** [comment]
Hello @jleonqu 
Thank you for taking the time to check this problem and give me more insight about it.
Yes looks like with these values of piston area & the HPA volume, even using the default solver will result in some pretty impractical output values of the model (for example Float & Spar displacement or Piston Pressure) and it seems like the HPA volume should be larger than this (in my example 3 seems to be the minimum acceptable value).
