### ISSUE TITLE
How to plot the free surface?

### ISSUE THREAD

**Issue by mojimarinecode** [WEC-Sim/WEC-Sim#606]
Hi 
I am running NEMOH for multi-floater WEC on Matlab
I am confuzed with the freesurface.dat files
How can I plot the free surface perturbations related to my floaters?
Thanks

**Comment by kmruehl** [comment]
Hi @mojimarinecode thanks for your question. Unfortunately this is a NEMOH question, and this is the WEC-Sim forum, so I encourage you to [open an issue on the NEMOM forum](https://github.com/LHEEA/Nemoh), and I'm going to close this issue.
