### ISSUE TITLE
Frame of reference

### ISSUE THREAD

**Issue by timmaflanagan** [WEC-Sim/WEC-Sim#612]
Hello, I am trying to determine what frame of reference the forces that WECSim outputs are in. 
Specifically: what frame of refence is the PTO force in?
What frame of refence is the Pto velocity? 
Finally are the viscous forces calculated in the body frame or the water frame or the global frame?

Best,

Timma

**Comment by akeeste** [comment]
Hello @timmaflanagan 

Thank you for your question. We have begun requiring users to open GitHub issues using an appropriate template. This is very useful to the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue with the "Theory or implementation clarification" I am happy to help.

Thanks!
Adam
