### ISSUE TITLE
[Theory or Implementation] stl origin

### ISSUE THREAD

**Issue by adetosoafonja** [WEC-Sim/WEC-Sim#618]
Can you include the origin of the stl file to be used for non-linear hydro in the documentation. I think I saw it somewhere a while ago that it's at the COG but I now I am struggling to find where it is stated whether it is in the documentation or in the webinar. I would suggest that it be stated again in the part that describes how to implement non-linear hydro since it is required for this functionality.

**Comment by akeeste** [comment]
Hello @adetosoafonja 

Thank you for your question. We have begun requiring users to open GitHub issues using an appropriate template. This is very useful to the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue with more detail and using the "Theory or implementation clarification" I am happy to help.

Thanks!
Adam
