### ISSUE TITLE
non-linear excitation force for RM3 point absorber

### ISSUE THREAD

**Issue by abaddonwang** [WEC-Sim/WEC-Sim#623]
Hi, 

I'm doing research on the average power output of a WEC model in different 2D waves. Previously I was using the example model-the RM3 point absorber for the analysis. However, I found the model is a linear model, I want to analyze with a model of high non-linearity. 

I found the examples provided (RM3 point abosorber) is not suitable for the non-linear analysis due to the lack of the mesh file. Can you provide me the mesh file so I can do the non-linear analysis with it (with non-linear excitation force turned on)?

My research topic is mainly on the wave classification, so I'm really weak on model building that's why I come here for help.

**Comment by akeeste** [comment]
Hello @abaddonwang 

Thank you for your question. We have begun requiring users to open GitHub issues using an appropriate template. This is very useful to the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue with more detail and using the "Theory or implementation clarification" I am happy to help.

Thanks!
Adam

**Comment by abaddonwang** [comment]
Hi Adam,

I re-submitted the question in  "Theory or implementation clarification", please check.  I hope can get your reply soon.

Best regards,

Abaddon Wang
________________________________
发件人: Adam Keester ***@***.***>
发送时间: 2021年6月23日 23:18
收件人: WEC-Sim/WEC-Sim ***@***.***>
抄送: Daming Wang ***@***.***>; Mention ***@***.***>
主题: Re: [WEC-Sim/WEC-Sim] non-linear excitation force for RM3 point absorber (#623)


Hello @abaddonwang<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabaddonwang&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7C670206e013004d13c50308d93694caff%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637600834994407726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h5WtFLBo%2FXCzVaEBzLiEC%2BL9F%2FUam2ygOUcvDWNkWbw%3D&reserved=0>

Thank you for your question. We have begun requiring users to open GitHub issues using an appropriate template. This is very useful to the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue with more detail and using the "Theory or implementation clarification" I am happy to help.

Thanks!
Adam

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWEC-Sim%2FWEC-Sim%2Fissues%2F623%23issuecomment-867197178&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7C670206e013004d13c50308d93694caff%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637600834994417677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nyxk6M%2Fc%2BJWYydg7cS0GXCl951VrWK6e2EcLGMJuS7M%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQBRX6EFL3II77WAELHTWVLTUJMSJANCNFSM47D3ZSOA&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7C670206e013004d13c50308d93694caff%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637600834994417677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Iu9TgLAjhRDZE3wEDQ5GAPZEodhDhWa7rlW%2BkDS1LF4%3D&reserved=0>.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
