### ISSUE TITLE
[Theory or Implementation] non_linear excitation force turned on using RM3 point absorber model

### ISSUE THREAD

**Issue by abaddonwang** [WEC-Sim/WEC-Sim#624]
Hi,

I'm doing research on the average power output of a WEC model in different 2D waves. Previously I was using the example model-the RM3 point absorber for the analysis. I tried to estimate the influence of non-linear excitation force, I used the example model RM3 point absorber, I turned on the non-linear excitation force by setting 'simu.nlHydro = 2;' in wecSiminputfile. m. However, this will cause the model float away along x-axis during the analysis. 

After consulting with other students, I found I probably need the mesh file for the RM3 model to carry on the non-linear analysis rather than simply turning on the non-linear excitation force by setting 'simu.nlHydro = 2;' 

 Can you provide me the missing file so I can do the non-linear analysis with it ? My purpose is to estimate the difference with and without the non-linear excitation force by using the same wave condition and to see if there is big difference on the power output from the WEC model. (Do you know if this non-linear excitation force will have significant influence on the power output?)

Since my research topic is about the wave field classification, I'm not experienced with model building, so I ask you if you can provide me this model so I can carry one the non-linear analysis. 

Best regards,

Abaddon

**Comment by akeeste** [comment]
Hi @abaddonwang 

As stated in issue #623, please use the template when opening a new issue. We ask that you please retain the given headers in bold, and supply information in the given format. This helps the WEC-Sim team to quickly identify the root causes of issues, categorize and analyze issues to find areas where we can improve WEC-Sim. 

For example, please include the following additional information corresponding to the "Theory and Information" headers on the template:
**Is your question request related to a problem? Please describe.**
Does your drift issue happen both with and without nonlinear hydro? What mesh are you currently using? What wave cases are you testing?

**Describe the theory or implementation approach that you have a question**
What requirements for using nonlinear hydro are you looking for clarity on? Is this only about mesh resolution or additional requirements as well?

**Describe the type of conclusion or resolution you are looking for**
I assume you are looking to get the non-linear hydro option working. This may require more insight than handing off a high resolution mesh.


If this template does not fit your needs, we welcome suggestions on new templates or how to improve our current ones.

Thanks!

**Comment by abaddonwang** [comment]
Hi Adam,

Sorry, I thought the text is only for guidance. i will re-submit it.

Best regards,

Abaddon
________________________________
发件人: Adam Keester ***@***.***>
发送时间: 2021年6月24日 16:52
收件人: WEC-Sim/WEC-Sim ***@***.***>
抄送: Daming Wang ***@***.***>; Mention ***@***.***>
主题: Re: [WEC-Sim/WEC-Sim] [Theory or Implementation] non_linear excitation force turned on using RM3 point absorber model (#624)


Hi @abaddonwang<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabaddonwang&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cd098cfa549c64e2dddc708d937281e8e%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601467711535382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VX2VJCsK3%2F4gF7eaudavbatfh4rlOXnuXnMjAuU1W3w%3D&reserved=0>

As stated in issue #623<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWEC-Sim%2FWEC-Sim%2Fissues%2F623&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cd098cfa549c64e2dddc708d937281e8e%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601467711545336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=liqd87ckM%2BUUEP2DuRRh%2F7Qdo22aWkAqdaAD3k%2FHnXk%3D&reserved=0>, please use the template when opening a new issue. We ask that you please retain the given headers in bold, and supply information in the given format. This helps the WEC-Sim team to quickly identify the root causes of issues, categorize and analyze issues to find areas where we can improve WEC-Sim.

For example, please include the following additional information corresponding to the "Theory and Information" headers on the template:
Is your question request related to a problem? Please describe.
Does your drift issue happen both with and without nonlinear hydro? What mesh are you currently using? What wave cases are you testing?

Describe the theory or implementation approach that you have a question
What requirements for using nonlinear hydro are you looking for clarity on? Is this only about mesh resolution or additional requirements as well?

Describe the type of conclusion or resolution you are looking for
I assume you are looking to get the non-linear hydro option working. This may require more insight than handing off a high resolution mesh.

If this template does not fit your needs, we welcome suggestions on new templates or how to improve our current ones.

Thanks!

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWEC-Sim%2FWEC-Sim%2Fissues%2F624%23issuecomment-867753052&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cd098cfa549c64e2dddc708d937281e8e%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601467711555291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b7mszxKQIkAXZcsApSq%2BjUem0le3OPGtXXHVkwqXGaw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQBRX6AL3RPI24EBIMFQH4TTUNIFBANCNFSM47GXY2SQ&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cd098cfa549c64e2dddc708d937281e8e%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601467711555291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1q9UOJF0Ov%2BYJD8Nia%2FE1qmyQaLOZ1XKm5YihBukJ40%3D&reserved=0>.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by akeeste** [comment]
Thank you! This does help us go through issues more quickly and effectively so that we can help users as soon as possible. I will look to update the template and make this more clear.

**Comment by abaddonwang** [comment]
Good evening,

I re-submitted the [Theory or Implementation]non_linear excitation force on RM3 point absorber model #625

Please check.

Best regards,

Abaddon
________________________________
发件人: Adam Keester ***@***.***>
发送时间: 2021年6月24日 17:17
收件人: WEC-Sim/WEC-Sim ***@***.***>
抄送: Daming Wang ***@***.***>; Mention ***@***.***>
主题: Re: [WEC-Sim/WEC-Sim] [Theory or Implementation] non_linear excitation force turned on using RM3 point absorber model (#624)


Thank you! This does help us go through issues more quickly and effectively so that we can help users as soon as possible. I will look to update the template and make this more clear.

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWEC-Sim%2FWEC-Sim%2Fissues%2F624%23issuecomment-867772328&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cb32eb4e8077e4387f14508d9372b8761%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601482352341100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L7yZYfuKHQh7%2BW5SscfYP%2B1tfIQe1cg4apnpTDrbRjU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQBRX6CWKA6B3IDFZRQYDUDTUNLARANCNFSM47GXY2SQ&data=04%7C01%7Cdaming.wang%40plymouth.ac.uk%7Cb32eb4e8077e4387f14508d9372b8761%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637601482352341100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hSH0PaKRZgJX%2BGiBEvJAsDZBzdGR6B4Zkr7jNfL06gU%3D&reserved=0>.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
