### ISSUE TITLE
[Development] Bump minimum MATLAB version to 2019b or 2020a (Proposal)

### ISSUE THREAD

**Issue by H0R5E** [WEC-Sim/WEC-Sim#631]
I'd like to propose that the minimum MATLAB version for WEC-Sim is increased. I think there are two good reasons (with two different versions) for this, as follows:

1. [Function Argument Validation](https://uk.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html) is an awesome feature that was introduced in R2019b. It makes handling function inputs so much easier than before, that it is really hard to write new code that doesn't use it, once you've started.

2. The minimum version for Mathworks supported CI platforms (like [Github Actions](https://github.com/matlab-actions/setup-matlab/)) is R2020a. Thus, we can't automatically test older versions.

EDIT: Do you like my "[Development]" tag? I kind of feel left out of the Issue Templates. ;)

**Comment by yuyihsiang** [comment]
The dev documentation will be updated (typo: 2019a -> 2020b) and the issue is resolved.
