### ISSUE TITLE
Use of rot. PTO act. torque/rot. PTO act motion for pos/speed control

### ISSUE THREAD

**Issue by t-osu** [WEC-Sim/WEC-Sim#652]
Hey all,

I am trying to drive a pendulum based PTO WEC at a constant speed for later control purposes. Right now, I have tried various ways to try and achieve this and all ways do not produce a consistent constant speed, they are jumpy around the actual value it should be at. Perhaps this is just the way it is because of mooring and interaction with waves, but I figured to post it here, maybe I overlooked something! Just an FYI I am using moordyn with a catenary setup. I'm not sure if specifics of that are helpful, if so let me know. Anyway, here is what I've tried for cases of 0.1 m and 5 s. The speed for one revolution is then 2*pi/5 = 1.256 rad/s. So far, item 3 has gotten me the best results.

1) First I tried the rotational PTO actuation motion block. I simply put the speed I want at the velocity input. This is the model what is outputted as speed. The output confuses me because if it is going at that speed, why is the position not at a constant slope? (I have the position unwrapped.) When watching the model in the model explorer, the pendulum is moving very slowly, definitely not the speed it should be.

![rot actuation speed](https://user-images.githubusercontent.com/68524876/127063899-f135d0b1-ccd2-4361-8b16-40d6561a8624.PNG)

![rot act speed output](https://user-images.githubusercontent.com/68524876/127063970-303d8cfa-bbd5-4e9a-8061-b0062a410ccf.png)

2) Second, I tried putting a position for the pendulum to follow using a repeating sequence (I didn't want to use a sine wave because then the pendulum wouldn't be moving in one direction). The pendulum is moving in one direction, but the speed continually increases, though. Also, I later tried a sequence for the entire length of the simulation instead of a repeating sequence and I got the same result.

![rot actuation position](https://user-images.githubusercontent.com/68524876/127064390-6f782484-22f8-498f-847a-6146cd8330bf.PNG)

![rot actuation pos output](https://user-images.githubusercontent.com/68524876/127064486-478d1a7f-23ee-4eef-a130-bce6ef40462b.png)

3) Third, I tried using the rotational PTO actuation torque. I demuxed the response output from this block to get the velocity of the pendulum which I then put into a really simple PI controller where the reference is the speed I want. To get to torque I just multiply it by a coefficient. I'm unsure how to determine that currently for different speeds because it obviously has an effect on the overall speed I am actually getting. Right now I just have it set to a value that got me on average the closest to my desired speed. I didn't use the direct drive rotary generator from PTO-Sim because of all the parameters needed to be set and I'm unsure what my actual generator parameters would be.

![pto torque](https://user-images.githubusercontent.com/68524876/127064841-5c786adb-3965-4f4f-a047-304ef4006769.PNG)

![pto torque output](https://user-images.githubusercontent.com/68524876/127066447-e02f1bcf-979e-4ba5-875e-6a5b0272a4ee.png)

Does anyone have any advice on what I should try, a mistake, or if I have tried everything maybe this is the best I can get?
Thanks :],

- Chris

**Comment by akeeste** [comment]
Hello @t-osu 

Thank you for your question. We have begun requiring users to open GitHub issues using [an issue template](https://github.com/WEC-Sim/WEC-Sim/issues/new/choose), as described in our [Troubleshooting documentation](http://wec-sim.github.io/WEC-Sim/master/user/troubleshooting.html#open-an-issue). This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue using the appropriate template (keep bold headers but remove italic descriptive text) and with more detail on your set-up and goals, we are happy to help.

Thanks!
Adam
