### ISSUE TITLE
[Developer Issue] Output time step with variable step solvers

### ISSUE THREAD

**Issue by akeeste** [WEC-Sim/WEC-Sim#656]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Project**
WEC-Sim development

**Describe the issue**
The output time step ``simu.dtOut`` is not robust in variable step WEC-Sim simulations. Library ``To Workspace`` blocks currently use a [decimation ](https://www.mathworks.com/help/simulink/slref/toworkspace.html) of ``round(simu.dtOut/simu.dt,0)``. For fixed step solvers this is fine, but with variable step solvers this becomes inaccurate. For example, if simu.dt = 1, simu.dtOut=5, WEC-Sim outputs every 5th data point. However when using a variable step solver, the actual time step can become 0.01. Then the output time step is effectively 0.05, not 5 seconds.

This can be fixed by changing all ``To Workspace`` blocks in the library to use the ``SampleTime = simu.dtOut``

**Comment by dforbush2** [comment]
see also global model settings: 
![image](https://user-images.githubusercontent.com/30122876/128199774-0cba0bf7-0d03-43fb-8c14-fd8ee847d049.png)

not sure which is the easier/better way

**Comment by akeeste** [comment]
@dforbush2 Thank for pointing this out. I'll look at loading the simulink file with the global output time step instead of changing each individual ``To Workspace`` block.
