### ISSUE TITLE
Required information on WAMIT's .out file

### ISSUE THREAD

**Issue by rbeicht** [WEC-Sim/WEC-Sim#662]
Hello everyone,

**Is your question request related to a problem? Please describe.**
No, it's related to a doubt regarding the WAMIT input files for BEMIO.

**Describe the theory or implementation approach that you have a question**
From what I read, when using WAMIT files in BEMIO, the .out needs to consider all 6 DoFs, and also have the infinite added mass. Then, I would like to know if it has any other requiriment, or just those 2.

**Personal project context**
I'm using WEC-Sim for a new project with some collegues.

**Describe the type of conclusion or resolution you are looking for**
I would like to know if there is more information required in WAMIT's .out, other than the 6 DoFs and infinite mass.

**Additional context**
N/A

Thanks for the help!

**Comment by akeeste** [comment]
Hello @rbeicht 

Thank you for your question. The WEC-Sim development team has begun requiring users to open GitHub issues using a template, as described in our [Troubleshooting documentation](http://wec-sim.github.io/WEC-Sim/master/user/troubleshooting.html#troubleshooting). This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen this issue using the appropriate template (keep bold headers but remove italic descriptive text) and linking to the relevant documentation that you have questions on, we are happy to help.

Thanks!
Adam

**Comment by rbeicht** [comment]
Thanks for the advice mate, done it!

**Comment by kmruehl** [comment]
@rbeicht yes, those are both requirements for WAMIT output in order to run WEC-Sim. WEC-Sim does require data for all 6 DOF from WAMIT for each body, and the infinite added mass. Here's a list of information BEMIO needs to parse WAMIT data for a WEC-Sim run:

- frequency-dependent excitation force 
- frequency-dependent radiation damping 
- frequency-dependent added mass and infinite added mass
- hydrostatic restoring force 
- displaced volume

We have [examples of WAMIT runs for WEC_Sim here](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples/BEMIO/WAMIT) if you'd like to refer to prior WAMIT runs when configuring your new run. Personally, I always start with a prior run and modify the input files for a new case.

**Comment by rbeicht** [comment]
> @rbeicht yes, those are both requirements for WAMIT output in order to run WEC-Sim. WEC-Sim does require data for all 6 DOF from WAMIT for each body, and the infinite added mass. Here's a list of information BEMIO needs to parse WAMIT data for a WEC-Sim run:
> 
> * frequency-dependent excitation force
> * frequency-dependent radiation damping
> * frequency-dependent added mass and infinite added mass
> * hydrostatic restoring force
> * displaced volume
> 
> We have [examples of WAMIT runs for WEC_Sim here](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples/BEMIO/WAMIT) if you'd like to refer to prior WAMIT runs when configuring your new run. Personally, I always start with a prior run and modify the input files for a new case.

Thanks for the info mate, it will help a lot!

Only thing I didn't understand was modifying input files in new case, you mean to use everything like the example but change only WAMIT file?

**Comment by akeeste** [comment]
@rbeicht This comment was only to suggest that if you base the WAMIT configuration files (.cfg, .frc, .pot) off of the BEMIO examples, then all information necessary for WEC-Sim should be included. Then when creating a new WAMIT case, you only have to edit a few parameters (cg, frequency, headings, etc). The rest of the input files stay the same and ensure all outputs for WEC-Sim are included.

Does this help resolve your issue?
Adam

**Comment by rbeicht** [comment]
Oh I see, now I understood! 

It certainly helps and also is a good strategy to avoid mistakes or missing outputs. Thanks a lot!
