### ISSUE TITLE
Memory usage with nlHydro = 2

### ISSUE THREAD

**Issue by mmartini1987** [WEC-Sim/WEC-Sim#669]
Dear WEC-Sim developers,
I am running a non-linear hydrodynamic simulation (nlHydro=2) of a flap-type device.

I am unable to run simulations longer than approx. 3600s, as my computer runs out of memory. I noticed that in the workspace there are very large variables related to non-linear hydrodynamics that likely collapse my memory, namely: "body1_hspressure_out", "body1_wavelinearpressure_out", "body1_wavenonlinearpressure_out" and so on.

I understand these are not required for the simulation to run, but only to store pressure values on each panel.

Is there a way to avoid these variables to be saved into the workspace? I could not find anything on the WEC-Sim guide.

Many thanks in advance!

Kind regards
Michele

**Comment by akeeste** [comment]
Hello @mmartini1987 

Thank you for your question. The WEC-Sim development team has begun requiring users to open GitHub issues using a template, as described in our [Troubleshooting documentation](http://wec-sim.github.io/WEC-Sim/master/user/troubleshooting.html). This is helpful for the development team to classify issues, and address questions more thoroughly and efficiently. We hope that this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the appropriate template we are happy to help. I think the feature request is most appropriate here.

Thanks!
Adam
