### ISSUE TITLE
[Developer Issue] BEMIO - Error using hdf5lib2

### ISSUE THREAD

**Issue by watchara3512** [WEC-Sim/WEC-Sim#679]
**Project**
WEC-Sim/ BEMIO

**Describe the issue**
For the Boundary Element Method Input/Output (BEMIO), I am trying to run it (refer to the Two-Body Point Absorber (RM3) tutorial & example-BEMIO-WAMIT-Cylinder) but I get the following errors as shown in Fig. 1 & 2. Do you have any suggestions to solve these errors?

"Error using hdf5lib2"
![Error 1](https://user-images.githubusercontent.com/88237095/129269134-d7131f74-5a4c-4893-9bec-ce20d9c5ecb6.png)
Fig. 1
![Error 2](https://user-images.githubusercontent.com/88237095/129269166-726e8f7f-f5e4-4bfc-ab8a-6e789be37097.png)
Fig. 2

and all WEC-Sim files were installed in the Mathlab path.
![Mathlab-Set Path](https://user-images.githubusercontent.com/88237095/129269497-f156baff-6aeb-4783-a077-56bbd070d68e.png)

Thank you in advance for your help 
Watchara  Tongphong

**Comment by akeeste** [comment]
Hi @watchara3512 

Thanks for opening your issue with a template. However, we reserve the ``Developer Template`` for our internal team only. The bug template will be more useful to us in this case. Can you please edit or reopen your issue to include the information/layout in the ``Bug Template``? This will help me assist you more quickly.

I have successfully tested the BEMIO scripts currently in our RM3 example, RM3 tutorial, and BEMIO-WAMIT-Cylinder example. I have no issues with them. When you edit, please give information on any changes you have made, WEC-Sim version and operating system.

Thanks,
Adam
