### ISSUE TITLE
[Developer Issue] Pinned sphinx_rtd_theme to less than version 1 for docs build 

### ISSUE THREAD

**Issue by H0R5E** [WEC-Sim/WEC-Sim#710]
**Project**
WEC-Sim

**Describe the issue**

The latest version of [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme) does not seem to be working properly, so I had to pin the version we use to less than version 1 in the travis docs build. There is an upstream bug report [here](https://github.com/readthedocs/sphinx_rtd_theme/issues/1236) with people reporting similar issues, so we can keep an eye on this for a resolution.

**Comment by kmruehl** [comment]
Closing this issue, will revisit at a later date with documentation updates.
