### ISSUE TITLE
[Theory or Implementation] Bottom-Refferenced Point Absorber in 3DOF

### ISSUE THREAD

**Issue by vibishana** [WEC-Sim/WEC-Sim#739]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
Hello! I'm trying to model a bottom fixed point absorber. In the model I'm considering PTO and other machineries are sitting on the seafloor and a partially submerged buoy is connected to the PTO with a  cable. 

**Describe the theory or implementation approach that you have a question**
I'm considering a translational PTO oriented in z-direction and if we restrict to 3DOF we know that all surge, heave and pitch displacements of the buoy are responsible for the translational displacement of the PTO.  However, I wasn't able to figure out a way to incorporate surge, heave and pitch displacements of the buoy into the translational PTO block.  All the examples I found are only considering heave responses. 

**Personal project context**
This is related to my final year research project. 

**Describe the type of conclusion or resolution you are looking for**
Any idea, document, or example you can provide is appreciated. Thank You!

**Additional context*
![ppppp](https://user-images.githubusercontent.com/92297649/136775195-83ba087b-22f7-4dd5-8724-52c80bf71b52.png)

**Comment by nathanmtom** [comment]
@vibishana Thank you for your inquiry and I will do my best to try and answer your question. 

If I have understood you question correctly, you would like to use the translational PTO to represent the tensioned line between the seafloor and the buoy while allow the connection at the top of the seabed foundation and at the bottom of the float to act like rotational joints that allow for surge, heave, and pitch motion. 

If so, the easiest will be to add a rotational joint on either side of the translational PTO block, linking constraints and ptos in series. We have examples in the [WEC-Sim Applications Repository](https://github.com/WEC-Sim/WEC-Sim_Applications), specifically the `Desalination` and `WECCCOMP_Fault_Implementation` folders, which I'd suggest looking through to see how we have implemented this type of system. 

I will mention that sometimes Simscape Multibody does not like rotational joints connected to another constraint or PTO without any mass, so often we place a small mass in-between the joints to resolve this issue. 

I hope my comments and response above have answered your question or at least pointed you in the right direction to find your answers. 

Cheers, 
Nathan
National Renewable Energy Laboratory
