### ISSUE TITLE
Function 'quaternion2EulXYZ' not supported for code generation.

### ISSUE THREAD

**Issue by Naveenudara** [WEC-Sim/WEC-Sim#749]
Function 'quaternion2EulXYZ' not supported for code generation.

Function 'Body Elements/Rigid Body/Hydrodynamic Body/Structure/Motion Sensor/quaternion2EulXYZ' (#1074.241.261), line 6, column 5:
"quaternion2EulXYZ(Q)"
Launch diagnostic report.
Component:MATLAB Function | Category:Coder error
Errors occurred during parsing of MATLAB function 'RM3/Rigid Body/Hydrodynamic Body/Structure/Motion Sensor/quaternion2EulXYZ'
Component:MATLAB Function | Category:Coder error
Simulink cannot determine sizes and/or types of the outputs for block 'RM3/Rigid Body/Hydrodynamic Body/Structure/Motion Sensor/quaternion2EulXYZ' due to errors in the block body, or limitations of the underlying analysis. The errors might be inaccurate. Fix the indicated errors, or explicitly specify sizes and/or types for all block outputs.
Component:MATLAB Function | Category:Coder error

**Comment by woosalute** [comment]
ds
