### ISSUE TITLE
How to obtain a specified degree of freedom hydrodynamics from [6x6] matrix in WEC-SIM

### ISSUE THREAD

**Issue by Doudou-Li** [WEC-Sim/WEC-Sim#764]
Hello,

I'd like to consider resonance theory for power maximization design by using WECCCOMP GitHub repository, which provided a WEC-Sim model of the 1:20 scale Wavestar device.

I think I want to build an optimal velocity reference for impedance matching idea. Therefore, I guess for this Wavestar numerical model, it is necessary to get its lumped damping term. But I am confused with how to obtain damping coefficients.
Maybe the pitch motion radiation damping coefficient is the mainly term for my requirement to know.

Is there possible to build a function between WEC damping coefficient and frequency?
![image](https://user-images.githubusercontent.com/63373273/141142120-2fd4d3d6-b7cc-4b82-a2fb-410350491603.png)

BR
Doudou

**Comment by nathanmtom** [comment]
@Doudou-Li Thank you for your inquiry; however, we are now requiring that our user base complete on the templates shown for new issues. 

![image](https://user-images.githubusercontent.com/7635064/141198266-8670c7cb-a104-42b3-a85c-775aea24b88e.png)

Then please complete all sections listed, which keeping the bolded section headings so we know which questions or description you are providing.

![image](https://user-images.githubusercontent.com/7635064/141198407-3a3d7700-be3c-412b-a741-fa51622846ff.png)

Once you have followed this template the WEC-Sim team will do our best to answer your question. 

Cheers, 
Nathan
National Renewable Energy Laboratory
