### ISSUE TITLE
How to show water surfaces and waters in mechanics Explorer

### ISSUE THREAD

**Issue by YU-XiaoYou** [WEC-Sim/WEC-Sim#767]
I used my own model in wec-Sim, it is only one body. After inputing the command " wecSim", it seems good, but i can not see the water surfaces and water in mechanics Explorer. I want to see them. What do I need to do?

**Comment by akeeste** [comment]
Hello @YU-XiaoYou 

Thank you for your question. We require users to open GitHub issues using an appropriate template. This is very useful to the development team to classify issues, and address questions more thoroughly and efficiently. We hope this will be beneficial for developers, users and the WEC-Sim community in general.

If you can please reopen or edit this issue to use the "Bug Report" template and include more details on what your errors, I am happy to help. Please maintain the template structure while completing the various sections.

Thanks!
Adam

**Comment by akeeste** [comment]
Hi @YU-XiaoYou 

There has been no updates in two weeks so I will close this issue. Please open a new issue using a template if you have additional issues and I am happy to assist.

Thanks,
Adam
