### ISSUE TITLE
Two Body Point Absorber (RM3)

### ISSUE THREAD

**Issue by Devsh93** [WEC-Sim/WEC-Sim#773]
I keep getting this error, and I don't know how to fix it, any help!?

Error using wecSim (line 46)
['RM3/Global Reference Frame/Solver Configuration']: Error evaluating equations at time 0.012. Stopping
simulation.  There may be a singularity in the solution.  If not, try reducing the step size (either by
reducing the fixed step size or by tightening the error tolerances)
Caused by:
    Error using wecSim (line 46)
    ['RM3/Floating (3DOF)/CONSTRAINT (Planar Joint)']: 'RM3/Floating (3DOF)/CONSTRAINT (Planar Joint)' has a degenerate mass distribution on its follower side.
 
I have tried to change the time step but still get the error.

Thanking you.

**Comment by akeeste** [comment]
Hi @Devsh93 

Have any past issues or the troubleshooting page helped resolve this problem? If not please edit this issue to use the Bug Report template and provide additional information.  I will close this issue in one week if there are no further questions.

Thanks,
Adam

**Comment by Devsh93** [comment]
Thank you sir.

There is a problem when consider PTO damping coefficient., and also buoy is oscillating not only in heave but also in surge and pitch.

**Comment by akeeste** [comment]
Hi @Devsh93 

If you wish to continue discussing this problem or a different aspect of WEC-Sim, please open a new issue using our Bug Report or Theory templates:
![image](https://user-images.githubusercontent.com/72414466/144865501-1b7c539b-10eb-445d-91b8-9dbbe4688886.png)

![image](https://user-images.githubusercontent.com/72414466/144865352-184b6df8-a036-4860-aaf1-a4aded87f515.png)
 
Please fill out all relevant information to clarify the problem and your set-up, and we can assist with your issue.

Thanks,
Adam

**Comment by kmruehl** [comment]
@Devsh93 I'm going to close this issue. Please open a new issue using the issue template.
