### ISSUE TITLE
Capytaine Results Files Show Zeroes

### ISSUE THREAD

**Issue by ccz359** [WEC-Sim/WEC-Sim#789]
Hello!

I have a project where I am using the Sandia Labs RM3 Wec-Sim model to kickstart an analysis on my own design. My project is also a two body point absorber system, similar to RM3. For the BEM analysis I have used the code for Capytaine, but made some modifications including the mesh input files. One other modification I made was to the call_capytaine.py file following the GitHub meshmagick Issue 19 solution. I am able to run my modified WP.py (based on rm3.py) without errors and it generates results in a .nc file, however the results are full of zeroes.

I've checked both meshes with healmesh -hm in meshmagick for both the spar and float meshes, and all appears fine. I did run the RM3 code first in Capytaine before applying changes, and it successfully produced results.

I am using Windows, Python 3.9, conda 4.11.0. I've attached my working folder.

Do you know why my results may be producing only zeroes? Any insight would be appreciated.

I have also posted this in the Capytaine Issues page on GitHub, but was hoping @akeeste may have some further insights as well.

Thanks!
[WP.zip](https://github.com/WEC-Sim/WEC-Sim/files/7944252/WP.zip)

**Comment by akeeste** [comment]
Hello @ccz359 ,

Unfortunately the WEC-Sim development team cannot provide in-depth assistance on BEM codes, as described in our [Troubleshooting documentation](http://wec-sim.github.io/WEC-Sim/master/user/troubleshooting.html#wec-sim-issues). If Capytaine runs without error but does not give the results expected, please contact the developers of Capytaine for further assistance. I can only suggest that you doublecheck the case set-up (bodies, DOFs, CGs, etc) and recommend viewing the meshes using ``FloatingBody.show()`` before running Capytaine. 

The ``call_capytaine`` file in the WEC-Sim master branch contains a check that will catch and prevent the meshmagick issue referenced. If there is an issue with any WEC-Sim scripts related to Capytaine or BEMIO I am happy to assist you. If so, please reopen this issue using one of the provided templates and give further information on the errors you receive.

Thanks,
Adam

**Comment by ccz359** [comment]
Hi @akeeste 

Thanks for the response, I understand. I think I've figured some of my issues out. I am getting one error now that I was getting before. Any idea how to solve this?

![image](https://user-images.githubusercontent.com/95105880/151248632-d0e1e6ce-b18b-4458-989d-0ca4e74a8811.png)

**Comment by akeeste** [comment]
Hi @ccz359 

I am glad that you were able to resolve some issues! This error comes up depending on the version of Capytaine being used. The hydrostatics module has changed since this script was developed. See the try-catch statement in lines 18-24 [here](https://github.com/WEC-Sim/WEC-Sim/blob/master/examples/BEMIO/CAPYTAINE/call_capytaine.py). This may need to be updated to catch the ``AttributeError``
