### ISSUE TITLE
ptoSimInputFile for Linear Generator

### ISSUE THREAD

**Issue by aglassFHKiel** [WEC-Sim/WEC-Sim#795]
Hey,
By modifying the ptoSimInputFile, some coefficient inputs are unclear to me.
Rs-Winding resistance: is it the resistance per coil oder per winding?
Bfric-Friction coefficient: what friction is this ment to be an how is it calculated in this example?
lambda_fd- Flux linkage: how is it calculated? 
Is there an Documantation where i can look it up?
Thanks in advance for your help!

![PTO_Linear Generator_Coefficients](https://user-images.githubusercontent.com/71267766/152144823-d5bd3726-25af-445a-b341-f55413d29aa7.PNG)

**Comment by jleonqu** [comment]
Hello @aglassFHKiel 

Rs is the resistence per winding.
Bfric is the friction coefficient that account for the friction losses in the electric generator.
lambda_fd: this is the flux linkage of the stator d winding. 

Bfric and lambda_fd are not calculated, these values are properties of the electric generator used as a case study for this example.

Regarding documentation, please look at references 7 and 10 in this link: [WEC-Sim Publications](http://wec-sim.github.io/WEC-Sim/master/introduction/publications.html)

**Comment by jleonqu** [comment]
I'll close this issue, but feel free to ask more questions or open a new issue if needed.
