### ISSUE TITLE
PTO-Sim - Able to Use for Piston Seawater Pump?

### ISSUE THREAD

**Issue by ccz359** [WEC-Sim/WEC-Sim#804]
Hi Wec-Sim Team!

**Is your question request related to a problem? Please describe.**
N/A

**Personal project context**
I am developing a wave powered seawater pump model in Wec-Sim. This is a two-body point absorber WEC, similar to the RM3 example. The pump is a single piston pump with two check valves: one at the inlet and one at the outlet. The piston is driven by the relative motion of float and spar.

**Describe the theory or implementation approach that you have a question**
I’m currently working on the Simulink model for the PTO and am wondering whether I can use PTO-Sim to model the pump by making some modifications to the existing blocks. Is there a way to model this pump in PTO-Sim? 

**Describe the type of conclusion or resolution you are looking for**
Is there more documentation available on PTO-Sim beyond what is posted on the GitHub pages?

**Additional context**
I’ve included a simple diagram of the wave pump/PTO that I’m trying to model as well. The piston rod is tied to the motion of the float, and the chamber is embedded within the spar. 

![image](https://user-images.githubusercontent.com/95105880/154711666-8fccf89c-e9b6-43d7-a447-833876ee6131.png)

Thank you!

**Comment by jleonqu** [comment]
Hello @ccz359 

You can use some of the blocks of PTO-Sim to simulate your system with some changes. You can use the "Compressible Fluid Piston" block for your piston, the input volFlowTop should be zero for your specific case. The input volFlowBottom would depend on the flow in the check valves of the system. To simulate the check valves, you can use the subsystems inside the block "Rectifying Check Valve". Each subsystem in this block is simulating one of the four check valves of the rectifying valve, so you can use this to simulate your valves.

For documentation, please look at references 7 and 10 here in this [link](http://wec-sim.github.io/WEC-Sim/master/introduction/publications.html). In these references you can find the equations used to model the hydraulic cylinder and the check valves in the rectifying valve.

**Comment by jleonqu** [comment]
Hello @ccz359 

You can't use the subsystem blocks directly, but you can copy and paste them and use different names for the variables, and then you won't have this error message. Also, I was reviewing the equations for the hydraulic cylinder and the input for volFlowTop shouldn't be zero but it should be Area*Piston Velocity. The initial value for the top pressure in the cylinder should be atmospheric pressure, and this pressure shouldn't change during the simulation. I have made some changes in your simulink model based on the diagram shown below:

![image](https://user-images.githubusercontent.com/72461917/156032987-5996c35a-55df-42ea-a00b-55ce51a605ea.png)

This is how the variables of the diagram are represented in the simulink model:

![image](https://user-images.githubusercontent.com/72461917/156033523-7b590d94-9b14-43a4-8d5f-b29b4d462fe4.png)


[WP_sharedUpdated.zip](https://github.com/WEC-Sim/WEC-Sim/files/8155551/WP_sharedUpdated.zip)

**Comment by ccz359** [comment]
Hi @jleonqu 

Your responses and feedback have been immensely helpful in building the PTO simulation for the water pump. I've included the working folder for the project so far. There are still a few quirks I'm trying to work out, if you have any insight I'd be very grateful. 

- At the start of the simulation (0-1 seconds), there is an initialization where the forces and position 'blow up', where the orders of magnitude are much greater than for the rest of the simulation. Do you know what might be causing this and how to mitigate it?
- At the start (0-2 seconds), the spar drops in position by about 50 meters from the surface, and then gradually sinks further over the course of the simulation. I've changed many of the inputs to see whether this can also be fixed, but I've had no luck so far. Any ideas? Ideally, according to the design, the spar and float are working together at the surface and are constrained with hard stops from moving more than 2m apart.

For my own understanding of the check valve blocks, what are the k1 k2 values written into the ptosim code representing?

Thank you very much!
[WP_shared2.zip](https://github.com/WEC-Sim/WEC-Sim/files/8208766/WP_shared2.zip)

**Comment by jleonqu** [comment]
Hi @ccz359 

Does this answer your question?

**Comment by ccz359** [comment]
Hi @jleonqu 

The smaller time step solved both the initialization and spar dropping issues that I was seeing, thank you! I've also set the k1 and k2 values equal to each other. 

Now, the only issue that I can see with the simulation is the lack of relative motion. The spar and float are moving synchronously in their heave motion, where I would expect the spar to remain more stationary. When I simulate with the spring/damper PTO I see the relative motion I would expect, but no longer see it when using PTO Sim. 

Here are my most up to date files if you have a chance to take a look. FYI with the reduced time step, the simulation does take several minutes to run now.

Again, I really appreciate the help and feedback.
[WP_shared3.zip](https://github.com/WEC-Sim/WEC-Sim/files/8333818/WP_shared3.zip)

**Comment by jleonqu** [comment]
Hi @ccz359 

You can try to change some of the parameters of your PTO model such as the area and volume of the piston, the characteristics of the valve, and the pressure settings. The damping and stiffness of the system is a function of all these variables. I would suggest to play a little bit with these variables to understand exactly how they affect the dynamics of your system.

**Comment by ccz359** [comment]
Hi @jleonqu 

After working on this some more, I found that I had set the Pmax value for the valve too high. The pressures at the inlet and to start in the piston were also too high. After reducing them to reflect the design better, I found that the solution was producing results that are expected. 

I really appreciate your help with this. Thanks so much!
