### ISSUE TITLE
The new variable/structure scheme doesn't work for non-linear hydrostatic forces

### ISSUE THREAD

**Issue by salhus** [WEC-Sim/WEC-Sim#819]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Project**
#803 defines a new variable name .nonlinearHyrdo (replaces .nlHyrdo) does not work because the old block had a non-linear sampling time variable that needs updating.

**Describe the issue**

Setting the .nonlinearHydro (even 0 and not just 1, 2) causes an error because the sampling time variable needs to be updated.

**Comment by kmruehl** [comment]
@salhus can you please add this to #822 so the issues are tracked in one thread? Thank you I'm going to close this here.
