### ISSUE TITLE
[BUG] API Section in Documentation not working

### ISSUE THREAD

**Issue by jtgrasb** [WEC-Sim/WEC-Sim#830]
**Describe the bug**
The API section within WEC-Sim's documentation is not functioning correctly and only displays the class names (both dev and master).

**WEC-Sim file(s)**
The objects are failing to import for some reason.

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to the WEC-Sim documentation and click on user manual -> API

**Expected behavior**
API should show the parameters associated with each class and their description

**Screenshots**
![image](https://user-images.githubusercontent.com/87095491/158606216-5870d780-e395-4b65-96fc-96768136de2f.png)
When built on my current branch:
![image](https://user-images.githubusercontent.com/87095491/158606518-8d9050e8-6f31-4d3c-9685-270e4f995fc3.png)

**Comment by kmruehl** [comment]
@H0R5E any ideas on why the API docs aren't properly generating?

**Comment by H0R5E** [comment]
Not sure. My thought is to expedite #817 as I wasn't getting an issues other than the ones I find on dev. That was 12 days ago tho....

**Comment by kmruehl** [comment]
Thank you @H0R5E
