### ISSUE TITLE
A problem of running the example :$WEC-Sim\tutorials\RM3----(matlab use)

### ISSUE THREAD

**Issue by woosalute** [WEC-Sim/WEC-Sim#843]
i am a new to WEC-Sim, i am trying to run the bemio.m in the tutorial document (E:\WEC-Sim\tutorials\RM3), but the matlab has always shown the error below:
                            The function or variable 'Read_WAMIT' is not recognized.
what can i do to solve it? i would  appreciate if  you can answer my question.

**Comment by woosalute** [comment]
![image](https://user-images.githubusercontent.com/101490252/162551095-6baf00a2-bc11-4cad-aab9-a95737aa3f6d.png)
this is my matlab interface

**Comment by nathanmtom** [comment]
@woosalute Thank you for submitting your issue; however, we require users to submit their issues following one our templates based on your inquiry. Please submit a new issue following the template or update this existing issue following said template. I've included some screen shots below to help walk you though this process.

![image](https://user-images.githubusercontent.com/7635064/162795747-859e5f85-58d1-4f0b-b15a-8fa216a4011f.png)

![image](https://user-images.githubusercontent.com/7635064/162795847-08c667ab-71a9-44fe-8ed3-dd894b5bc312.png)

**Comment by woosalute** [comment]
thank you for your reply! after two days working ,i have solved the problem that i have had,but i still thank you very much



At 2022-04-12 01:27:55, "nathanmtom" ***@***.***> wrote:

@woosalute Thank you for submitting your issue; however, we require users to submit their issues following one our templates based on your inquiry. Please submit a new issue following the template or update this existing issue following said template. I've included some screen shots below to help walk you though this process.
