### ISSUE TITLE
[WEC-Sim Applications] Rotational PTO Actuation Torque

### ISSUE THREAD

**Issue by Hi-gone** [WEC-Sim/WEC-Sim#848]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
WEC-Sim_Applications-master\PTO-Sim\OSWEC\OSWEC_Hydraulic_PTO

**Describe the bug or issue**
In this case, the PTO system only outputs torque relative to the Flap, because Base is fixed. Can I use Rotational PTO Actuation Torque if the Base is floating?

**To Reproduce**
_Steps to reproduce the behavior:_
N/A

**Expected behavior**
I want to simulate a dual floating WEC, but I wasn't sure of the correctness of the 'Rotational PTO Actuation Torque', only one floating body seems to be considered in the Simulink model.

**Screenshots**
![1650104289(1)](https://user-images.githubusercontent.com/87789625/163671206-5701f401-4cb9-411f-aa21-576b1b8babd8.png)

**Workstation Information (this section MUST BE completed):**
OS: [Windows 10]
[MATLAB/Simulink] [ 2020b]
[WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v4.4]

**Additional context**
_Add any other context about the problem here._

**Comment by akeeste** [comment]
Hi @Hi-gone

Thank you for opening an issue and using our template.

You can definitely use the ``Rotational PTO Actuation Torque`` block with a floating base. In this case the PTO block's torque and response are both of the Follower port (`F`) relative to the Base port (`B`). Typically the follower is the flap and the Simscape base is the OSWEC base. See the ports labeled on the block here:
![image](https://user-images.githubusercontent.com/72414466/164013946-b9da2d9c-ca38-47b4-88ff-171da130b722.png)


You can likely use the same hydraulic PTO-Sim model that is in this Application case. However it might need some adjustments to account for a different physical set-up and the fact that the base can also move.

Please let me know if this addresses your issue and if you have any more questions.
Adam

**Comment by Hi-gone** [comment]
@akeeste 
Thank you for your explanation,I guess the input in Rotational PTO Actuation Torque is relative speed.For two bodies in relative motion,they should be subjected to opposite torques.So is this output reassigned in the next segment?

**Comment by akeeste** [comment]
@Hi-gone 

The ``Rotational PTO Actuation Torque`` block has a relative torque input, and the ``Rotational PTO Actuation Motion`` block has a relative motion input. Even though these blocks take relative speed and torque, Simscape will automatically apply the correct convention to each body so that each has an opposite and opposing force on it.

Adam

**Comment by akeeste** [comment]
Hi @Hi-gone 

Do you have any more questions on this issue? If not I will close out this issue next week. Feel free to open another for any more questions you have.

Thanks,
Adam
