### ISSUE TITLE
How to convert a mooring system parameter into a 6x6 matrix  for use in WEC-SIM?

### ISSUE THREAD

**Issue by Owen0708** [WEC-Sim/WEC-Sim#85]
Hi,
I have seen that mooring system setting in the code FAST, it's called the quasi-static
mooring, is the WEC-SIM mooring system also called the quasi-static mooring?
Because the mooring setting in the WEC-SIM is need to set another matrix "c"(WEC-SIM's c relate to 
velocity), here is the difference between the WEC-SIM and FAST, I am shown in the below.
FAST:
![image](https://cloud.githubusercontent.com/assets/13230160/12115042/cb0e72e8-b3e9-11e5-9c9e-81f665d76883.png)
WEC-SIM:
![image](https://cloud.githubusercontent.com/assets/13230160/12115109/44094c68-b3ea-11e5-877f-0f28737c7665.png)
So if I had a matrix "c"(FAST's c matrix relate to displacement) which I found in this paper:http://www.nrel.gov/wind/pdfs/47535.pdf, is the same as the matrix "k"(WEC-SIM's k relate to displacement)?
And is there an example showing the convert a mooring system parameter into a 6x6 matrix 
for use in WEC-SIM? the mooring system parameters look like this:
![image](https://cloud.githubusercontent.com/assets/13230160/12115274/c3deddbc-b3eb-11e5-918d-db82ccaaa12b.png) which I found it from the same paper.  

many thanks.
Owen

**Comment by cmichelen** [comment]
Hi Owen,

Some comments:
* In the WEC-Sim equation you are missing the Pre-Tension (a constant force)
* Yes, I think the Fast 'c' matrix corresponds to the WEC-Sim 'k' matrix, @yuyihsiang is that so?
* No, unfortunately we do not have an example showing this.
* You should also take a look at MoorDyn which allows for better mooring modeling. You seem to have your mooring system well defined, so you could use MoorDyn. The is an example that uses MoorDyn under ``tutorials/RM3_CoupledWithMoorDyn`` 

Hope this helps.
