### ISSUE TITLE
[Theory or Implementation] Differences in AQWA and WEC-Sim conventions

### ISSUE THREAD

**Issue by salhus** [WEC-Sim/WEC-Sim#865]
**The development team requests that before submitting a question on the theory and implementation behind WEC-Sim to first please:**
1. Read through our [WEC-Sim Documentation](http://wec-sim.github.io/WEC-Sim/man/theory.html) with additional description found in our [Advanced Features Section](http://wec-sim.github.io/WEC-Sim/man/advanced_features.html)
1. Review MATLAB source code ([functions](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions), [objects](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/objects)) and the Simulink blocks ([libraries](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/lib))
1. Review the curated [WEC-Sim Examples](https://github.com/WEC-Sim/WEC-Sim/tree/master/examples) and the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications)
1. Review the [WEC-Sim issues page](https://github.com/WEC-Sim/WEC-Sim/issues) which allows you to search past resolved issues or questions that might help answer your own question.

**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I do not understand why I get 'X' result when running 'Y' simulation [...]_

This issue is a continuation of questions raised by @tuisong1106 in the context of #855.
I would request @tuisong1106 to use the format here to describe their question here so that it can be resolved.

**Describe the theory or implementation approach that you have a question**
_Please clearly describe the assumptions, equations, or code script that you would like clarification. Also, please provide references to other research papers, open-source material, or other information that may be relevant in the WEC-Sim developers understanding your question._

**Personal project context**
_If this request is related to your project, please describe what you are attempting to do in your project so the WEC-Sim development team knows your end goal._

**Describe the type of conclusion or resolution you are looking for**
_[Ex.] I am still unclear on how an irregular wave train is generated within WEC-Sim and would appreciate being pointed to where in the documentation and code where I can find additional information._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by hachikoi1** [comment]
Hi [salhus](https://github.com/salhus)
Long time no see, here I am again. This time the issue is related to the phase angle of the wave excitation force calculated by AQWA. 
Regarding PR #855, I found some modifications in readAQWA.m, and the modifications are updated in WEC-Sim v5.0.1 (my present version)
```
-    hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) = -tmp2*pi/180; % Phase of exciting force
+    hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) =  wrapToPi(-pi-tmp2*pi/180); % Phase of exciting force    
+    hydro(F).ex_ph(3,ind(2),ind(3))                           =  wrapToPi(-tmp2(3)*pi/180); % Phase of exciting force for heave
```
However, the phase angle read by readAQWA.m has positive and negative difference in surge and pitch directions compared with that of WAMIT, and perhaps also exsit in sway, roll and yaw directions
![Excitation_Phase](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/eb2215a3-6b54-4589-ae77-88d2e75234b6)
And also, the excitation IRF in surge and pitch directions is wrong
![Excitation_IRFs](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/e231ea74-978c-474f-8bdc-59b74e82d80d)


I therefore use ```hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) = -tmp2*pi/180; % Phase of exciting force``` read phase angle of AQWA and the results are satisfactory.
![Excitation_Phase](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/a2efee47-f4d0-4061-be17-331af94bd3f5)
![Excitation_IRFs](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/35121ea5-9598-432e-a2ae-c40fe76b6f22)

https://ars.els-cdn.com/content/image/1-s2.0-S0029801822025690-mmc1.zip

**Comment by salhus** [comment]
Hi @hachikoi1 ,

Nice to hear from you again.
refer https://github.com/WEC-Sim/WEC-Sim/pull/855
The convention for wave direction is $+x$-axis being positive from left-to-right in WAMIT, WEC-Sim and hydrodynamics literature in general.

AQWA uses the opposite convention, i.e., the $+x$-axis being positive from

**Comment by hachikoi1** [comment]
Dear [salhus](https://github.com/salhus)
To be more specific, I think the old version is right
```
hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) = -tmp2*pi/180; % Phase of exciting force
```
and present version has some problems
```
hydro(F).ex_ph(((ind(1)-1)*6+1):(ind(1)*6),ind(2),ind(3)) =  wrapToPi(-pi-tmp2*pi/180); % Phase of exciting force    
```

Best regards,

**Comment by salhus** [comment]
Hi @hachikoi1 
refer my last comment.
Simply adding a negative sign is not the correct approach to correct the direction (I actually did that initially as well). By adding a phase difference, all other dependent calculations stay consistent.

**Comment by kumarsmahmoodi** [comment]
Dear @salhus
As far as I understand, in AQWA, the wave direction is defined as the angle from the positive global X axis to the direction in which the wave is traveling. There for, waves travel along the X axis (from - X to +X) have a 0 degree wave direction (as shown in the attached picture). AQWA solves the velocity potential based on phi *exp(-iωt) not phi *exp(iωt). The phase difference with WAMIT is due to negative sign in exponential function used in AQWA.
![IMG-20230530-WA0020](https://github.com/WEC-Sim/WEC-Sim/assets/123304447/6198e030-1b78-495b-a527-a23546b59608)

**Comment by salhus** [comment]
@kumarsmahmoodi 

Yes, you are right about the phase. That's what I note when I referred https://github.com/WEC-Sim/WEC-Sim/pull/846

and that's why I resovled it by introducing a phase of $pi$ and not simply adding a negative sign.  In terms of interpretation of direction of the wave, refer this excerpt from https://books.google.com/books?id=_ogwDQAAQBAJ
![image](https://github.com/WEC-Sim/WEC-Sim/assets/84348506/8b2eed50-4c31-4a30-a63d-86a3bd8916d5)

**Comment by hachikoi1** [comment]
Dear [salhus](https://github.com/salhus)
Could you see the posted pictures https://github.com/WEC-Sim/WEC-Sim/issues/865#issuecomment-1568111700? Excitation IRFs calcualted using `wrapToPi(-pi-tmp2*pi/180)` do differ from WAMIT's results. Give me a few days to think this through.

Best regards,

**Comment by salhus** [comment]
hi @hachikoi1 ,

I looked at it again. Refer previous comments where I go over this in detail.

Cheers,
Sal

**Comment by kumarsmahmoodi** [comment]
Hi @salhus
You are right about the phase convertion. Thanks for your efforts in developing the wecsim code.
Best regards

**Comment by salhus** [comment]
thanks @kumarsmahmoodi !

**Comment by hachikoi1** [comment]
Dear [salhus](https://github.com/salhus)
I carefully think about the question and give my insights here. I described it as carefully as I could. Please correct me if there is any problem.
My description is a bit long, thank you very much for your patience in reading it
- In both WAMIT and AQWA, global coordinate origin is (X, Y, Z) = (0, 0, 0). Local coordinate origin (x, y, z) is specified by `XBODY` in WAMIT and is COG in AQWA
- In both WAMIT and AQWA, wave direction angle is defined as the angle between the wave propagating direction and the positive X axis measured anti-clockwise. 
- In WAMIT, the incident wave elevation is given at **global coordinate origin**: $\eta(t) = A_w\cos(\omega t)$ ($A_w$ is the regular wave amplitude), and the phases of some parameters, e.g., the exciting forces, motions, pressure and fluid velocity, are defined relative to the incident-wave elevation at global coordinate origin: $p(t) = A_p\cos(\omega t+\varphi)$, where $\varphi$ is the phase and $A_p$ is the amplitude of the parameter. 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/10aefdf5-477f-4795-9c23-783301ab67a8)
- In AQWA, the incident wave elevation is given at global coordinate origin, and the incident wave elevation at COG can then be defined by $\eta(t) = A_wcos[-\omega t + k (x\cos\beta+y\sin\beta)+ \alpha]$, where $\alpha$ is the wave phase angle
between COG and global coordinate origin.  A corresponding parameter are represented as $p(t) = A_p\cos(-\omega t + \alpha + \phi)$, where $\phi$ is the phase angle of the parameter and is defined according to the difference from the time when the regular wave crest is at COG to the time when the parameter reaches its peak value.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/e39f8f25-bced-44f4-8637-5a0f9988a026)
- By comparing the defination of phase angles in WAMIT and AQWA:
1. The phase angle $\varphi$ output by WAMIT is a global variable. For multi-body problems, the phase angle $\varphi$ of  each body can be directly used to calculate the real and imaginary parts of the excitation force.
2. The wave phase angle $\alpha$ in AQWA is a global variable, and parameter phase angle $\phi$ is a local variable. The sum of wave phase angle and parameter phase angle $\alpha + \phi$ is a global variable. $\alpha + \phi$ in AQWA is equivalent to $\varphi$ in WAMIT
- My questions are below:
1. I am not sure about the phase angle outputs in AQWA .AH1 and .LIS files. Are they separate parameter phase angle $\phi$ or the sum of wave phase angle and parameter phase angle $\alpha + \phi$? 
2. In the paper [A designed two-body hinged raft wave energy converter](https://www.sciencedirect.com/science/article/pii/S0029801822025690?via%3Dihub) mentioned that the phase angle output in AQWA is the parameter phase angle $\phi$ but not $\alpha + \phi$. They set the global coordinate to coincide 
with the COG of the fore raft, thus $\alpha = 0$ for the COG of the fore raft (I think there is a slight problem here in that $\alpha$ for the COG of the fore raft may not be strictly zero during the oscillation). Then they recalculated the phase angle of aft raft in the [Modified_Read_AQWA.m](https://ars.els-cdn.com/content/image/1-s2.0-S0029801822025690-mmc1.zip) by considering the parameter phase angle $\phi$ of aft raft and the phase angle between fore raft COG and aft raft COG.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/1a8aff6e-6268-4095-820f-7ee217830916)
```
hydro(F).gap=hydro(F).cg(1,2)-hydro(F).cg(1,1);
PhaseShift(i)=hydro(F).WaveNumber(i)*hydro(F).gap;
if k==1; % fore raft
hydro(F).ex_ph((k-1)*6+1:k*6,j,i) =-tmp2*pi/180;  
else % aft raft
hydro(F).ex_ph((k-1)*6+1:k*6,j,i) =-tmp2*pi/180-hydro(F).PhaseShift(i);
end 
```
3. In original readAQWA.m, I understand function `wrapToPi(-pi-tmp2*pi/180)` is euqal to $-\pi - \phi$ or $-\pi - \alpha - \phi$, then $p(t) = A_p\cos(-\omega t -\pi - \phi) = A_p\cos(\omega t + \phi)$ or $p(t) = A_p\cos(-\omega t -\pi - \alpha - \phi) = A_p\cos(\omega t + \alpha + \phi)$. Why `wrapToPi(-tmp2(3)*pi/180)` is still used for the phase angle in heave direction?

Thanks again for your patience

Best regards,

Tianyuan

**Comment by salhus** [comment]
Hi @hachikoi1 Tianyuan,

Thanks for looking into this in detail. I appreciate the rigor you went through. Unfortunately, I am not familiar with AQWA itself and the post-processing code was written to extract data. And, that's why the phasing issue went undetected as it is not easy to compare it with WAMIT as you have found out as well.

Your observation seems to make sense that AQWA has a local and a global phase, and the strategy taken by the paper you shared would then make sense for the sake of simplicity and the ability to compare results with other BEM codes. 

Regarding your questions,

re: 1,
 I am unable to verify whether the phase is global or a sum of local and global phase. I would recommend getting in touch with someone more familiar with AQWA phasing,
re: 2,
Again, I think commenting on their approach is beyond the scope of this issue. It is indeed relevant, and the way they modify by using a phase-shift seems to be a similar approach taken in readAQWA.m. 
re: 3,
I think that is a good observation.
First off, to check, I would recommend you to go the folder in ###\WEC-Sim\examples\BEMIO,  run the any of the AQWA examples so you have hydro structure in the workspace, make a new variable, say hydro_aqwa = hydro,
now do the same for the corresponding wamit example.
Next, you can use the plotBEMIO(hydro_aqwa, hydro_wamit), to compare the 2 hydro structures, and you would notice that the phase is a match. The image here is the cylinder example.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/84348506/6dda8dfe-25f5-4a62-bb9d-d7834fac15c9)

Now, to your question. 
As you observe, in AQWA, the wave-direction is aligned with $+x$ direction, the kernel has a phase difference of $\pi$. What that effectively means, is when comparing the frames (and in the code for readAQWA), the coordinate frame is first rotated by $\pi$ about the vertical $z$ and then $\pi$ again about the new $+x$.  

See https://github.com/WEC-Sim/WEC-Sim/pull/846,

Note, $\theta$ is the wave-direction measured about the $+z$ axis, but then as you note earlier, the phase difference $\phi$ has the opposite sign convention (e.g., phase-lag has the opposite sign as well - negative in WAMIT/WEC-Sim, but positive in AQWA), which means the $y$ axis also needs to be flipped. 

So actually, for the heave phase the phase has to re-written to have a negative sign and the code is not 'left' out. Note, rotations are NOT commutative.

![image](https://github.com/WEC-Sim/WEC-Sim/assets/84348506/585b552b-a75e-4e75-a22d-ba942b104248)


Let me know if this resolves the issue, or if you are still not convinced.

**Comment by hachikoi1** [comment]
Dear [salhus](https://github.com/salhus)
Many thanks for your reply. I compared the sphere case computed by WAMIT and AQWA. As you say, `wrapToPi(-pi-tmp2*pi/180)` (the first figure) works out well but `-tmp2*pi/180` (second figure) has some problems.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/106c13aa-0636-4210-ad37-fb4f1d8b19d4)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/209fb932-468c-43b4-82dd-e38a445819ed)
Conversely, for my studied floating platform, the results are completely opposite. `wrapToPi(-pi-tmp2*pi/180)` (the first figure) is no longer correct and `-tmp2*pi/180` (second figure) matches well with WAMIT results
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/30007973-c538-4df1-9846-d73d45167247)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/ae25c965-0622-40c8-afb6-ec0b63c7b032)
I am looking for the cause of this problem. The definition of the phase angle in AQWA will also be updated later
Best regards,
Tianyuan

**Comment by salhus** [comment]
Hi @hachikoi1 Tianyuan,

That would make sense since the runs made in aqwa will be using an incoming wave with its phase defined with aqwa convention. If you make that run with the incoming wave at a heading of $\pm \pi$, it should be consistent with wamit and the readaqwa script.

If that makes sense let me know if we can close this issue as the reading script itself seems to be working.

**Comment by hachikoi1** [comment]
Dear [salhus](https://github.com/salhus)
The issue can be closed. Many thanks for your valuable comments.
Salute to you
Tianyuan

**Comment by hachikoi1** [comment]
PS: I moved the sphere 10m in the positive direction of the x-axis (COG = 10, 0, 0) in AQWA and compared the result with unmoved result (COG = 0, 0, 0). Their phase angles are the same, impling that the phase angle output by AQWA is **parameter phase angle** but not the sum of wave and parameter phase angles.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/ef549909-9656-42f8-b9f0-d29e9bd670e7)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/844c95f3-db5b-4ed4-bfe1-06d50fd464b1)
Hope the results will help anyone stuck with AQWA phase angle problems
Best regards,

**Comment by salhus** [comment]
@hachikoi1 Tianyuan,

Thanks so much for trying that out ! I agree this discussion will be very helpful to other AQWA users. I appreciate your engagement.

Cheers,
Sal
