### ISSUE TITLE
[Feature request] Morison Element implementation

### ISSUE THREAD

**Issue by ahmedmetin** [WEC-Sim/WEC-Sim#883]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your feature request related to a problem? Please describe.**
Yes. WecSim calculates currently the drag force as a function of buoy velocity only, rather than the relative velocity. I would like to use the Morison Element force by setting inertia terms to 0 and just use the drag term in conjunction with a nonlinear hydrodynamic body. Meanwhile, in the quadratic friction model I only use the rotational friction terms. (The flow is assumed to be irrotational). I check the Morison element drag force and observe that the drag force is not continuous and becomes 0 every time the position of the buoy is above the mean water line, even though the buoy is still inside water. 
Then I see that inside the Morison force implementation the force is set to 0 if the point of application goes above the mean water line. See screenshot. 
<img width="907" alt="Screenshot 2022-06-12 at 07 22 01" src="https://user-images.githubusercontent.com/32479811/173217317-56bbb843-5d15-401a-84e2-114013716ad1.png">

**Describe the solution you'd like**
Why is the force set to 0? It feels that it is wrong at first sight, but of course I do not understand the reason. I think the Morison force should be set to 0 only if the buoy goes completely out of water. Therefore, one should check the position of the buoy with respect to the local wave elevation. And it feels better to check the centre of each mesh if it is under water, rather than if the point of application is under water. 

As a start maybe you can just remove this condition that sets the force to 0 from the code completely, since I think it makes the model more wrong than right. Or hint the users in the documentation maybe to choose a lower drag application point, so that this condition gets activated at a more reasonable point.

**Describe alternatives you've considered**
One can also maybe add a correction for the characteristic area depending on how much percent of the buoy is submerged. What do you think?

**Personal project context**
I have also a floating cylindrical buoy with centre of gravity at the centre of the cylinder. I assume the point of application of Morison force to be at centre of gravity. The cylindrical body is not slender. The Morison Element force is probably not intended for this kind of use. However, as I explained the inertia terms are not used. I have also tested it and it works as expected when I remove the condition that sets thee force to 0 completely. 

**Additional context**
N/A

Best regards,
Ahmed

**Comment by nathanmtom** [comment]
@ahmedmetin Thank you for your question; however, we require that any issues follow the issues template that we have made to ensure we receive the appropriate information to recreate your issue. Please update your issue above to follow the template, see Issue #881 as an example, or open a new issue. Once you have completed this the team can begin assisting with your issue. 

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by ahmedmetin** [comment]
@nathanmtom Thanks for your response. I have tried to put it in the template now. I am not sure if this classifies as a feature request, bug or just a question.

**Comment by ahmedmetin** [comment]
Thank you so much for the thorough explanation, @nathanmtom. I did not realize before that I can enter more than one Morison element. I will definitely try and see how it works. Thanks a lot! :)

Best regards,
Ahmed

**Comment by ahmedmetin** [comment]
Hello @nathanmtom, I have tried the Morison element force with more more Morison elements. However,  I get a difference between the case with more Morison elements and single Morison element where I remove the condition z > 0. 
Currently, I run a very simple case to compare the two cases. Just a decay test in heave. With more Morison elements I get a much more damped response. The reason is that the characteristic area is constant for each Morison element in the axial direction (heave direction), because of constant water plane area of cylinder. So when one has more Morison elements, the total characteristic area increases with the number of Morison elements. I have the same drag coefficient in both cases, i.e. the drag coefficients of the Morison elements with the case with multiple Morison elements is equal to the drag coefficient of the case with single Morison element. I guess the answer should be they should not be equal, at least for the axial case to have a matching response, right? 

Thanks! 

Best regards,
Ahmed

**Comment by ahmedmetin** [comment]
Update. It seems I need to divide the area by the number of Morison elements, because the total characteristic area basically increases if I do not do that.
Please see the figure below. I get basically convergence with only 4 elements as you suggested.

![HeavedecatTestMorisonElementConvergenceZoomed](https://user-images.githubusercontent.com/32479811/174486282-3d26f0ef-4cce-4f89-98c0-1bbc1091fa2a.png)

Thanks a lot for your help. I think we can  close the issue. 
Best regards,
Ahmed
