### ISSUE TITLE
[Theory or Implementation]

### ISSUE THREAD

**Issue by hresing** [WEC-Sim/WEC-Sim#891]
**Is your question request related to a problem? Please describe.**
I am unsure of the units used/composition of the added mass structure in the hydro structure that BEMIO outputs.
 

**Describe the theory or implementation approach that you have a question**
In the terminology table in the theory manual, added mass, A(w), is listed as having units of kg. 
Is kg the units of the A(w) in the hydro structure that the BEMIO code outputs? 
Is kg the units of the A(w) for all added mass terms in this structure, or are the rotational terms in kg*m^2? 

In addition, the developer manual brings in the Adjusted Mass matrix - does this impact the added mass values seen in the hydro structure at all, or is this something that only comes into play later in the simulation.

**Personal project context**
I would like to compare Added Mass values in the pitching mode between an OSWEC simulation and existing values in kg*m^2. 

**Describe the type of conclusion or resolution you are looking for**
I would like to know the units of and whether there are additional components in (as the adjusted mass matrix seems to indicate) the Added Mass in pitch in the hydro structure that is output by BEMIO.

**Additional context**
n/a

**Comment by dforbush2** [comment]
Hi @hresing 

The added mass matrix is in units of kg for linear modes and kg-m^2 for rotational. This will be clarified in the documentation. 

The adjusted mass matrix is a work-around implemented in WEC-Sim to allow us to vary the inertia tensor at every time step which is not readily allowed in Simscape multibody. Though there are some edge cases where this can affect results, for the OSWEC and similar devices the adjusted mass matrix does not need to be considered.
