### ISSUE TITLE
[WEC-Sim Applications] How to calculate the efficiency of the RM3 with Hydraulic PTO?

### ISSUE THREAD

**Issue by sinclairwan** [WEC-Sim/WEC-Sim#897]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
WEC-Sim_Applications PTO-Sim RM3/RM3_cHydraulic_PTO/

**Describe the bug or issue**
I have modified the userdefinedfunctions.m file, and obtained the output voltage, current and electric power of the device . I hope to get the input energy of the irregular wave, and then calculate the wave energy conversion efficiency of the device. Now I have found the power option in the waveclass in the work area, but I don't know whether the power here refers to the total input wave energy, because I found that the calculated output electric power is not in the same order of magnitude as the values in the table, so does it need to multiply the values in the table by a constant to be the real input wave energy?

**To Reproduce**
_Steps to reproduce the behavior:_

1. _Go to 'WEC-Sim_Applications PTO-Sim RM3/RM3_cHydraulic_PTO'_
2. Run the program
3. Click on "waves",and you will see the property "power"

**Expected behavior**
I want to know how to calculate the energy of incoming waves。

**Screenshots**
![Quicker_20220628_213616](https://user-images.githubusercontent.com/101490252/176192455-3397f238-2a00-4665-a5c7-b0a1b51425f5.png)

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - [MATLAB/Simulink Release] 2021a
 - [WEC-Sim Release] v5.0

**Additional context**
Since computing efficiency is a very important part of my graduation thesis, I am looking forward to your answer

**Comment by jtgrasb** [comment]
Hi @sinclairwan,

The waves.power variable can be found in the waveClass (WEC-Sim/source/objects/waveClass.m). In this file, the wave power is defined as Wave Power Per Unit Wave Crest [W/m]. The wave power needs to be converted to W in order to compare directly to the output electric power.
