### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by POGULURI** [WEC-Sim/WEC-Sim#924]
Hello, this is a follow-up to my question in the WEC-Sim Applications tag (Please see the link below). David Ogden requested that I file it in a Bug report, which I am doing here.

The external damping is simply the sum of PTO and viscous (linear) damping simulated in WEC-Sim using the "linear damping" option, as shown in the attachment.

It is clear that when simulations using WEC-Sim are performed, the COG and COR results are similar for a small wave height (H=0.1 m), whereas the results obtained are different for a larger wave height (H=2.0 m).

In the WEC-Sim, the hydrodynamic coefficient and body moment of inertia are calculated based on the simulation results for COR/COG. The link below may provide additional information.

Thanks!

Link: https://github.com/WEC-Sim/WEC-Sim/issues/921#issue-1319015812

![3](https://user-images.githubusercontent.com/43121156/181422775-14a42a42-d963-4dad-b9a6-87cc7b69f48a.png)

![4](https://user-images.githubusercontent.com/43121156/181422801-287b8f1d-1b56-4e1f-a545-c23f5dccc3b5.png)

**Comment by dav-og** [comment]
Hi @POGULURI, sorry if I wasn't clear - I meant to open a new issue with some extra information that can help us to look into this further.

You can hit new issue:
![image](https://user-images.githubusercontent.com/12831266/181478376-ca81649a-fadd-417b-9995-a148fe938d82.png)

Then bug report:
![image](https://user-images.githubusercontent.com/12831266/181478460-00649674-2744-4758-9cc3-e55f35f7da1d.png)

Then fill in the template:
![image](https://user-images.githubusercontent.com/12831266/181478552-ebf71062-6f16-410f-a685-f34a795bbea2.png)

If you could share two folders - one to reproduce CoR results, one to reproduce CoG results, that would help.
