### ISSUE TITLE
[Theory or Implementation] PTO-Sim Question

### ISSUE THREAD

**Issue by niyurui** [WEC-Sim/WEC-Sim#932]
**Is your question request related to a problem? Please describe.**
I don't understand how the components of hydraulic PTOsimulink model work in harmony in RM3 case with hydraulic PTO, that is, the working principle of hydraulic PTO.

**Describe the theory or implementation approach that you have a question**
Working principle of hydraulic PTO

**Personal project context**
I tried to describe the working principle of hydraulic PTO to readers in my paper.

**Describe the type of conclusion or resolution you are looking for**
Figure shows the simlink simulation model of hydraulic PTO used in RM3 case. What puzzles me is how the rectifier valve, high-pressure accumulator, low-pressure accumulator and hydraulic motor work together to drive the rotary generator to generate electricity. Could you please tell me the working principle of the hydraulic PTOsimlink model, or if there is any relevant text description for reference? I would be very grateful for your opinion.

**Additiona
![微信图片_20220809153137](https://user-images.githubusercontent.com/107034647/183591138-20d43ff6-29f2-4cd5-ba94-76c228d9261a.png)
l context**

**Comment by dav-og** [comment]
Hi @niyurui,

I would recommend reading So's original PTO-Sim paper: https://energy.sandia.gov/wp-content/uploads/2014/06/2015-IEEE-PES_PTO-Sim_Nak.pdf

And Yu's paper on a hydraulic PTO model for RM3: https://www.nrel.gov/docs/fy19osti/71078.pdf

Cheers,
Dave

**Comment by jleonqu** [comment]
Hello @niyurui 

Does this answer your question?
