### ISSUE TITLE
how to link WEC-sim with external programs

### ISSUE THREAD

**Issue by JackyzhangHJ** [WEC-Sim/WEC-Sim#953]
Hello, I have recently learned WEC-sim and would like to know how to link WEC-sim with external programs. I would like to know how to link WEC-sim with external dynamic link libraries (.dll files). In other words, I want to build the equations of motion of the upper structure of floating body through the dynamic link library, and I need to call the motion response of the floating body obtained by WEC-sim in real time. At the same time, the dynamic link library will output the load at the location where the upper structure is connected to the floating body as an external load to WEC-sim. This creates a data exchange to achieve full coupling. Can this idea be realized?
In a sense, moordyn seems to be formed in this way. But I didn't find a specific way to implement it with the code though.
Best wishes.

**Comment by akeeste** [comment]
Hi @JackyzhangHJ 

We require users to use a template when creating an issue. This helps our development team get needed information up front and answer questions more efficiently. Can you please modify your issue to use a template? (or create a new issue). I suggest the implementation or feature request templates for your question.

![image](https://user-images.githubusercontent.com/72414466/194893115-083bb5c2-5e91-4e9e-889c-fb08acea4406.png)
![image](https://user-images.githubusercontent.com/72414466/194892835-cbd45fb8-6450-489f-a05c-495c635e4e39.png)
![image](https://user-images.githubusercontent.com/72414466/194893020-aa95b919-4428-48d9-b95f-598013d1237d.png)

Thanks
Adam

**Comment by JackyzhangHJ** [comment]
Hi, @akeeste 
   According to your comments, I have add a new issue in #954 by the template 'Theory implementation clarfication'. And I supply some my research progress in it. Thanks!
