### ISSUE TITLE
[Theory or Implementation]

### ISSUE THREAD

**Issue by AmirRahimi70** [WEC-Sim/WEC-Sim#960]
First of all, I would like to appreciate WEC-sim team.
Can we implement a translational PTO with damping coefficient, c_pto, Stiffness, k_pto and mass, m_pto? the mass of the pto is important for me.
f_pto = m_pto.xddot_rel + c_pto.xdot_rel + k_pto.x_rel

thank you in advance.
A. Rahimi

**Comment by nathanmtom** [comment]
@AmirRahimi70 Thank you for your inquiry, unfortunately we require new issues to follow one of the assigned templates, see image below. Please answer each question or respond with an N/A (Not applicable) and leave the questions bolded so we know what question you are responding too. You can either update your previous issue text above or submit a new issue following the template.

![image](https://user-images.githubusercontent.com/7635064/197420468-e04eea72-4571-4345-979f-dce5277ab83c.png)

Cheers,
Nathan
National Renewable Energy Laboratory
