### ISSUE TITLE
[Feature request]: GBM and NL hydro.

### ISSUE THREAD

**Issue by dforbush2** [WEC-Sim/WEC-Sim#961]
**Is your feature request related to a problem? Please describe.**
Generalized body modes cannot be used correctly with non-linear hydrodynamics because the position of panel centers are determined from the rigid body motion alone. 

**Describe the solution you'd like**
Because the user has defined the generalized body mode(s) it should be possible use the GBM displacements and a series of coordinate transformations to accurately calculate panel center locations that account for rigid body and generalized body mode displacements.

This will be of increasing interest for flexible device developers.

**Comment by kmruehl** [comment]
moved to project board
