### ISSUE TITLE
Unrecognized readCAPYTAINE 

### ISSUE THREAD

**Issue by hfpim** [WEC-Sim/WEC-Sim#963]
I'm trying to generate a .h5 file from a .nc file but I keep getting the following error:
*Unrecognized function or variable 'readCAPYTAINE'.*

I thought it was some wrongdoing of my part so I tried multiple WEC-Sim examples but I keep getting the same error.
How can I fix that?

**Comment by dav-og** [comment]
hello @hfpim,

Please can you fill in one of our issues templates to help us figure this out?:

If you hit 'New issue' you should see the following options:
![image](https://user-images.githubusercontent.com/12831266/200331226-c8958318-4ff2-45d7-a568-c15fc2217df7.png)

(I suggest filling in the first one)

cheers,
Dave

**Comment by hfpim** [comment]
That option didn't show up before. Did it work now?

**Comment by dav-og** [comment]
I'm not sure whats changed but if you open up a new issue & hit bug report then you should see the following template:
![image](https://user-images.githubusercontent.com/12831266/200357876-bf92a9f4-a980-402b-acf9-e5c5c43fae1e.png)
if you fill in these fields it can help us to advise you on your issue.
