### ISSUE TITLE
[BUG] Unrecognized readCAPYTAINE

### ISSUE THREAD

**Issue by hfpim** [WEC-Sim/WEC-Sim#964]
I'm trying to generate a .h5 file from a .nc file but I keep getting the following error:
_Unrecognized function or variable 'readCAPYTAINE'.

I thought it was some wrongdoing of my part so I tried multiple WEC-Sim examples but I keep getting the same error. I tried sphere and cylinder examples without success
How can I fix that?

**Here is the code**

```
hydro = struct();
hydro = readCAPYTAINE(hydro,'cylinder_full.nc');
hydro = radiationIRF(hydro,15,[],[],[],[]);
hydro = radiationIRFSS(hydro,[],[]);
hydro = excitationIRF(hydro,15,[],[],[],[]);
writeBEMIOH5(hydro)
plotBEMIO(hydro)
```

The path to folder is: 
_\...\WEC-Sim-master\examples\BEMIO\CAPYTAINE\cylinder_
To run it, I just click "Run" on Matlab.

![image](https://user-images.githubusercontent.com/112897638/200369349-40d1cb84-9803-488e-a83c-bbb42f40fd5f.png)

**Workstation Information:**
 OS: Windows 10
 [MATLAB/Simulink Release]: R2021b

**Comment by dav-og** [comment]
Hi @hfpim thanks for the additional information,

I just did a fresh install of WEC-Sim-master and ran the Capytaine cylinder example...but it worked fine for me, so I couldn't reproduce your error:

![image](https://user-images.githubusercontent.com/12831266/200391347-8fe89c03-8859-45d4-bec1-fb4758ca2b1a.png)

Can I just check if you ran the 'addWecSimSource.m' script? (to install WEC-Sim and add it to your path)

(Full installation instructions available here: https://wec-sim.github.io/WEC-Sim/master/user/getting_started.html#install-wec-sim)

**Comment by dav-og** [comment]
Hi @hfpim, are you still having a problem with the readCAPYTAINE() function or can we close out this issue?

**Comment by hfpim** [comment]
I figured it out, you can close this issue, thank you!
