### ISSUE TITLE
Creating H5 file from Nemoh output

### ISSUE THREAD

**Issue by arash1988a** [WEC-Sim/WEC-Sim#98]
We are trying to reconstruct the RM3 simulation in WEC-Sim, but with obtaining the hydrodynamic coefficients from Nemoh, the problem that we are encountering is that in Bemio we don't know how to describe the correlation between two different bodies (float and plate), because they don't act separately and somehow we need to define the interaction between these two bodies. We are wondering if Bemio is able to do so or if there is any solution for that.

**Comment by cmichelen** [comment]
Nemoh has the ability to do generalized degrees of freedom, which should allow you to define your constraints. BUT WEC-Sim (and BEMIO) cannot use these. They need your BEM solution to be 6 DOF for each body. You still get body-to-body interactions. You define your constraints in the WEC-Sim model, and turn the ``simu.b2b = 1;`` flag in the input file. See the body-to-body interaction section in the documentation: http://wec-sim.github.io/WEC-Sim/features.html#body-to-body-interaction
