### ISSUE TITLE
Using WEC-Sim for 1D Motion

### ISSUE THREAD

**Issue by Yohan231** [WEC-Sim/WEC-Sim#985]
Hello! I'm doing an undergraduate research project and will need to use a WEC-Sim model and results to write it up my report. I've derived equations of motion for a 1D motion system. But since WEC-Sim uses a 3D coordinate system (6 DoF range of motion), can I simplify the WEC-Sim model for a 1 DoF system?

**Comment by dav-og** [comment]
Hi @Yohan231,

Yes - there are multiple approaches to model a 1 DoF system & there are some examples in the [WEC-Sim Applications repo](https://github.com/WEC-Sim/WEC-Sim_Applications). [Free_Decay](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/Free_Decay) shows a translational example and [WECCCOMP](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/WECCCOMP) shows a rotational example.

Please have a go and if you need additional help fill in one of issues templates: probably 'implementation clarification' would make most sense in your case.

![image](https://user-images.githubusercontent.com/12831266/215497753-379b8319-663e-408a-9d3e-5fd0afc75c85.png)

Cheers,
Dave
